import json, re

food_extras = [
    {"civWord": "Pancakes", "civWordMal": "Pancakes", "imposters": [{"word": "Waffles", "wordMal": "Waffles", "relationEN": "Both are sweet breakfast dishes often served with syrup.", "relationML": "Both are sweet breakfast dishes often served with syrup."}, {"word": "Crepes", "wordMal": "Crepes", "relationEN": "Both are flat batter-based treats cooked on a griddle.", "relationML": "Both are flat batter-based treats cooked on a griddle."}]},
    {"civWord": "Donut", "civWordMal": "Donut", "imposters": [{"word": "Bagel", "wordMal": "Bagel", "relationEN": "Both are circular baked goods with a hole in the middle.", "relationML": "Both are circular baked goods with a hole in the middle."}, {"word": "Croissant", "wordMal": "Croissant", "relationEN": "Both are popular breakfast pastries.", "relationML": "Both are popular breakfast pastries."}]},
    {"civWord": "Soup", "civWordMal": "Soup", "imposters": [{"word": "Stew", "wordMal": "Stew", "relationEN": "Both are liquid-based warm meals cooked in a pot.", "relationML": "Both are liquid-based warm meals cooked in a pot."}, {"word": "Broth", "wordMal": "Broth", "relationEN": "Both are savory liquids often served in a bowl.", "relationML": "Both are savory liquids often served in a bowl."}]},
    {"civWord": "Salad", "civWordMal": "Salad", "imposters": [{"word": "Coleslaw", "wordMal": "Coleslaw", "relationEN": "Both are cold, vegetable-based side dishes.", "relationML": "Both are cold, vegetable-based side dishes."}, {"word": "Wrap", "wordMal": "Wrap", "relationEN": "Both often feature fresh veggies and a light dressing.", "relationML": "Both often feature fresh veggies and a light dressing."}]},
    {"civWord": "Cheese", "civWordMal": "Cheese", "imposters": [{"word": "Butter", "wordMal": "Butter", "relationEN": "Both are popular dairy products used in cooking.", "relationML": "Both are popular dairy products used in cooking."}, {"word": "Yogurt", "wordMal": "Yogurt", "relationEN": "Both are cultured milk products.", "relationML": "Both are cultured milk products."}]},
    {"civWord": "Cake", "civWordMal": "Cake", "imposters": [{"word": "Pie", "wordMal": "Pie", "relationEN": "Both are classic baked desserts often sliced and shared.", "relationML": "Both are classic baked desserts often sliced and shared."}, {"word": "Brownie", "wordMal": "Brownie", "relationEN": "Both are sweet baked goods typically served at parties.", "relationML": "Both are sweet baked goods typically served at parties."}]},
    {"civWord": "Chocolate", "civWordMal": "Chocolate", "imposters": [{"word": "Caramel", "wordMal": "Caramel", "relationEN": "Both are sweet, rich confections.", "relationML": "Both are sweet, rich confections."}, {"word": "Vanilla", "wordMal": "Vanilla", "relationEN": "Both are classic, globally popular dessert flavors.", "relationML": "Both are classic, globally popular dessert flavors."}]},
    {"civWord": "Fries", "civWordMal": "Fries", "imposters": [{"word": "Onion Rings", "wordMal": "Onion Rings", "relationEN": "Both are deep-fried side dishes popular in fast food.", "relationML": "Both are deep-fried side dishes popular in fast food."}, {"word": "Potato Chips", "wordMal": "Potato Chips", "relationEN": "Both are salty potato snacks.", "relationML": "Both are salty potato snacks."}]},
    {"civWord": "Fried Chicken", "civWordMal": "Fried Chicken", "imposters": [{"word": "Chicken Nuggets", "wordMal": "Chicken Nuggets", "relationEN": "Both are breaded, crispy poultry dishes.", "relationML": "Both are breaded, crispy poultry dishes."}, {"word": "Buffalo Wings", "wordMal": "Buffalo Wings", "relationEN": "Both are popular finger-foods made of chicken.", "relationML": "Both are popular finger-foods made of chicken."}]},
    {"civWord": "Bacon", "civWordMal": "Bacon", "imposters": [{"word": "Sausage", "wordMal": "Sausage", "relationEN": "Both are savory breakfast meats.", "relationML": "Both are savory breakfast meats."}, {"word": "Ham", "wordMal": "Ham", "relationEN": "Both are cured pork products.", "relationML": "Both are cured pork products."}]},
    {"civWord": "Omelette", "civWordMal": "Omelette", "imposters": [{"word": "Scrambled Eggs", "wordMal": "Scrambled Eggs", "relationEN": "Both are common breakfast egg dishes.", "relationML": "Both are common breakfast egg dishes."}, {"word": "Pancake", "wordMal": "Pancake", "relationEN": "Both are flat breakfast items cooked in a pan.", "relationML": "Both are flat breakfast items cooked in a pan."}]},
    {"civWord": "Muffin", "civWordMal": "Muffin", "imposters": [{"word": "Cupcake", "wordMal": "Cupcake", "relationEN": "Both are small baked goods shaped similarly.", "relationML": "Both are small baked goods shaped similarly."}, {"word": "Scone", "wordMal": "Scone", "relationEN": "Both are popular baked treats paired with tea or coffee.", "relationML": "Both are popular baked treats paired with tea or coffee."}]},
    {"civWord": "Popcorn", "civWordMal": "Popcorn", "imposters": [{"word": "Pretzels", "wordMal": "Pretzels", "relationEN": "Both are classic, salty movie theater snacks.", "relationML": "Both are classic, salty movie theater snacks."}, {"word": "Nachos", "wordMal": "Nachos", "relationEN": "Both are popular shared snacks at events.", "relationML": "Both are popular shared snacks at events."}]},
    {"civWord": "Curry", "civWordMal": "Curry", "imposters": [{"word": "Stew", "wordMal": "Stew", "relationEN": "Both are hearty, slow-cooked savory dishes with gravy.", "relationML": "Both are hearty, slow-cooked savory dishes with gravy."}, {"word": "Biryani", "wordMal": "Biryani", "relationEN": "Both are intensely spiced, flavorful dishes.", "relationML": "Both are intensely spiced, flavorful dishes."}]}
]

animal_extras = [
    {"civWord": "Monkey", "civWordMal": "Monkey", "imposters": [{"word": "Ape", "wordMal": "Ape", "relationEN": "Both are intelligent primates.", "relationML": "Both are intelligent primates."}, {"word": "Chimpanzee", "wordMal": "Chimpanzee", "relationEN": "Both are highly social, tree-dwelling mammals.", "relationML": "Both are highly social, tree-dwelling mammals."}]},
    {"civWord": "Bear", "civWordMal": "Bear", "imposters": [{"word": "Wolf", "wordMal": "Wolf", "relationEN": "Both are large, dangerous forest predators.", "relationML": "Both are large, dangerous forest predators."}, {"word": "Gorilla", "wordMal": "Gorilla", "relationEN": "Both are massive, powerful woodland animals.", "relationML": "Both are massive, powerful woodland animals."}]},
    {"civWord": "Fox", "civWordMal": "Fox", "imposters": [{"word": "Wolf", "wordMal": "Wolf", "relationEN": "Both are wild, dog-like carnivores.", "relationML": "Both are wild, dog-like carnivores."}, {"word": "Coyote", "wordMal": "Coyote", "relationEN": "Both are clever, adaptable predators.", "relationML": "Both are clever, adaptable predators."}]},
    {"civWord": "Rabbit", "civWordMal": "Rabbit", "imposters": [{"word": "Hare", "wordMal": "Hare", "relationEN": "Both are fast, long-eared leaping mammals.", "relationML": "Both are fast, long-eared leaping mammals."}, {"word": "Squirrel", "wordMal": "Squirrel", "relationEN": "Both are small, common woodland critters.", "relationML": "Both are small, common woodland critters."}]},
    {"civWord": "Deer", "civWordMal": "Deer", "imposters": [{"word": "Elk", "wordMal": "Elk", "relationEN": "Both are large, antlered herbivores of the forest.", "relationML": "Both are large, antlered herbivores of the forest."}, {"word": "Moose", "wordMal": "Moose", "relationEN": "Both are majestic woodland animals.", "relationML": "Both are majestic woodland animals."}]},
    {"civWord": "Horse", "civWordMal": "Horse", "imposters": [{"word": "Donkey", "wordMal": "Donkey", "relationEN": "Both are domesticated beasts of burden.", "relationML": "Both are domesticated beasts of burden."}, {"word": "Zebra", "wordMal": "Zebra", "relationEN": "Both are fast-running hooved animals.", "relationML": "Both are fast-running hooved animals."}]},
    {"civWord": "Cow", "civWordMal": "Cow", "imposters": [{"word": "Bull", "wordMal": "Bull", "relationEN": "Both are large, domesticated bovines.", "relationML": "Both are large, domesticated bovines."}, {"word": "Goat", "wordMal": "Goat", "relationEN": "Both are common farm animals raised for milk.", "relationML": "Both are common farm animals raised for milk."}]},
    {"civWord": "Pig", "civWordMal": "Pig", "imposters": [{"word": "Boar", "wordMal": "Boar", "relationEN": "Both are stout, snouted animals.", "relationML": "Both are stout, snouted animals."}, {"word": "Sheep", "wordMal": "Sheep", "relationEN": "Both are staple livestock animals.", "relationML": "Both are staple livestock animals."}]},
    {"civWord": "Sheep", "civWordMal": "Sheep", "imposters": [{"word": "Goat", "wordMal": "Goat", "relationEN": "Both are small, grazing herd animals.", "relationML": "Both are small, grazing herd animals."}, {"word": "Alpaca", "wordMal": "Alpaca", "relationEN": "Both are fluffy animals raised for wool.", "relationML": "Both are fluffy animals raised for wool."}]},
    {"civWord": "Crocodile", "civWordMal": "Crocodile", "imposters": [{"word": "Alligator", "wordMal": "Alligator", "relationEN": "Both are large, dangerous aquatic reptiles.", "relationML": "Both are large, dangerous aquatic reptiles."}, {"word": "Snake", "wordMal": "Snake", "relationEN": "Both are fearsome, cold-blooded predators.", "relationML": "Both are fearsome, cold-blooded predators."}]},
    {"civWord": "Turtle", "civWordMal": "Turtle", "imposters": [{"word": "Tortoise", "wordMal": "Tortoise", "relationEN": "Both are slow-moving reptiles with shells.", "relationML": "Both are slow-moving reptiles with shells."}, {"word": "Snail", "wordMal": "Snail", "relationEN": "Both are slow creatures that carry a shell on their back.", "relationML": "Both are slow creatures that carry a shell on their back."}]},
    {"civWord": "Frog", "civWordMal": "Frog", "imposters": [{"word": "Toad", "wordMal": "Toad", "relationEN": "Both are common leaping amphibians.", "relationML": "Both are common leaping amphibians."}, {"word": "Lizard", "wordMal": "Lizard", "relationEN": "Both are small, cold-blooded creatures often found near water.", "relationML": "Both are small, cold-blooded creatures often found near water."}]},
    {"civWord": "Eagle", "civWordMal": "Eagle", "imposters": [{"word": "Hawk", "wordMal": "Hawk", "relationEN": "Both are large, sharp-sighted birds of prey.", "relationML": "Both are large, sharp-sighted birds of prey."}, {"word": "Falcon", "wordMal": "Falcon", "relationEN": "Both are powerful, predatory raptors.", "relationML": "Both are powerful, predatory raptors."}]},
    {"civWord": "Owl", "civWordMal": "Owl", "imposters": [{"word": "Bat", "wordMal": "Bat", "relationEN": "Both are nocturnal flying animals.", "relationML": "Both are nocturnal flying animals."}, {"word": "Hawk", "wordMal": "Hawk", "relationEN": "Both are skilled avian predators.", "relationML": "Both are skilled avian predators."}]}
]

with open("words.js", "r", encoding="utf-8") as f:
    text = f.read()

def replacer_intl(match):
    packs = json.loads(match.group(1))
    for p in packs:
        if p["id"] == "foodintl" or p["id"] == "famousfoods": 
            p["words"].extend(food_extras)
        elif p["id"] == "animals": 
            p["words"].extend(animal_extras)
    return match.group(0).replace(match.group(1), json.dumps(packs, indent=2, ensure_ascii=False))

text = re.sub(r'const intlPacks = (\[.*?\]);', replacer_intl, text, flags=re.DOTALL)

with open("words.js", "w", encoding="utf-8") as f:
    f.write(text)

print("Added more words")
