var packs = (typeof window !== 'undefined' && window.packs) || (typeof packs !== 'undefined' ? packs : []);
const STORAGE_KEY = 'aaraanu_imposter_saved_players';
function loadSavedPlayers() {
  if (typeof window === 'undefined' || !window.localStorage) return ['Player 1', 'Player 2', 'Player 3'];
  try {
    const saved = JSON.parse(window.localStorage.getItem(STORAGE_KEY));
    if (Array.isArray(saved) && saved.length >= 3 && saved.length <= 10) {
      return saved;
    }
  } catch(e) {}
  return ['Player 1', 'Player 2', 'Player 3'];
}
function savePlayers() {
  if (typeof window === 'undefined' || !window.localStorage) return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(players));
  } catch(e) {}
}
let players=loadSavedPlayers(),selected=new Set((packs||[]).map(p=>p.id)),round=1,currentPlayer=0,imposters=new Set(),imposterCount=1,word=null,showMalayalam=false,selectedVote=-1,timerId;
const $=id=>typeof document!=='undefined'?document.getElementById(id):null;const show=id=>{if(typeof document==='undefined')return;document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));if($(id))$(id).classList.add('active');if(id==='home'){document.body.style.background='#060509';document.documentElement.style.background='#060509';var sh=document.querySelector('.app-shell');if(sh)sh.style.background='#060509';}else{document.body.style.background='#0d0c13';document.documentElement.style.background='#0d0c13';var sh=document.querySelector('.app-shell');if(sh)sh.style.background='';}if(typeof window!=='undefined'&&window.scrollTo)window.scrollTo(0,0)};
const hideLoader=()=>{if(typeof document==='undefined')return;const l=document.getElementById('loader');if(l&&!l.classList.contains('done')){const startTime=window.__loaderStartTime||(Date.now()-5000);const elapsed=Date.now()-startTime;const rem=Math.max(0,5000-elapsed);setTimeout(()=>{l.classList.add('done');document.body.style.background='#060509';document.documentElement.style.background='#060509';var sh=document.querySelector('.app-shell');if(sh)sh.style.background='#060509';var h=document.getElementById('home');if(h){window.dispatchEvent(new Event('resize'));}setTimeout(()=>{if(l&&l.parentNode)l.style.display='none'},450)},rem)}};
if(typeof window!=='undefined'&&typeof document!=='undefined'){hideLoader();window.addEventListener('load',hideLoader);window.addEventListener('DOMContentLoaded',hideLoader);setTimeout(hideLoader,5000);}
function renderPlayers(){if(typeof document==='undefined')return;const list=$('playerList');if(!list)return;list.innerHTML='';players.forEach((name,i)=>{const row=document.createElement('div');row.className='player-row';row.innerHTML=`<span class="player-number">${i+1}</span><input value="${name.replace(/"/g,'&quot;')}" aria-label="Player ${i+1} name"><button class="remove-player" aria-label="Remove player"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"></path><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path></svg></button>`;row.querySelector('input').oninput=e=>{players[i]=e.target.value||`Player ${i+1}`;savePlayers();};row.querySelector('button').onclick=()=>{if(players.length>3){players.splice(i,1);if(imposterCount>Math.floor(players.length/2)){imposterCount=Math.max(1,Math.floor(players.length/2));if($('imposterTotal'))$('imposterTotal').textContent=imposterCount}renderPlayers();savePlayers();}};list.append(row)});if($('playerTotal'))$('playerTotal').textContent=`${players.length} / 10`;}
function renderCategories(){if(typeof document==='undefined')return;const grid=$('categoryGrid');if(!grid)return;grid.innerHTML='';packs.forEach(p=>{const b=document.createElement('button');b.className=`category-card ${selected.has(p.id)?'selected':''}`;b.innerHTML=`<span class="cat-icon">${p.icon}</span><b>${p.name}</b><small>${p.words.length} words</small>`;b.onclick=()=>{selected.has(p.id)?selected.delete(p.id):selected.add(p.id);renderCategories();updateCategoryText()};grid.append(b)});if($('categoryCount'))$('categoryCount').textContent=`${selected.size} of ${packs.length} selected`;}
function updateCategoryText(){if($('categorySummary'))$('categorySummary').textContent=selected.size===packs.length?'All categories selected':`${selected.size} of ${packs.length} selected`;}
const IMPOSTER_SINGLE_WORDS = {
  'Adipoli': 'Celebration', 'Poli Scene': 'Party', 'Sadhanam Kayyil Undo': 'Suitcase', 'Thenga': 'Tree', 'Chetta': 'Tea', 'Eda Mone': 'Friend', 'Kidilan': 'Award', 'Chali': 'Joke', 'Koppu': 'Anger', 'Pani Paali': 'Trouble', 'Ambada': 'Laughter', 'Poda Pulle': 'Escape', 'Vattaano': 'Doctor', 'Athu Sheri': 'Question', 'Thallumala': 'Crowd', 'Chummadive': 'Game', 'Oodayi': 'Trick', 'Jada': 'Style', 'Vera Level': 'Sky', 'Blunder': 'Mistake', 'Suhurthe': 'Meeting', 'Kittu': 'Prize', 'Scene Contra': 'Police', 'Chamakku': 'Fashion',
  'Shavapetti': 'Wood', 'Pothu': 'Animal', 'Kuthikazhapp': 'Dance', 'Manavalan': 'Wedding', 'Ganga': 'Jewelry', 'Rukmini': 'Song', 'Dashamoolam Damu': 'Fight', 'Ramanan': 'Garden', 'Gafoor Ka Dost': 'Ship', 'Nagavalli': 'Palace', 'Appukuttan': 'Hospital', 'Kuttahs': 'Camera', 'C.I.D Moosa': 'Dog', 'Aadu Thoma': 'Ray-Ban', 'Dr. Sunny': 'Mystery', 'Rajavinte Makan': 'Briefcase', 'Sethurama Iyer': 'Perfume', 'Thomas Kutty': 'Car', 'Dharam Bhai': 'Gold', 'Pavayi': 'Dress', 'Charly': 'Motorcycle', 'Kattappana Hrithik': 'Audition',
  'Onam': 'Flower', 'Vishu': 'Crackers', 'Thrissur Pooram': 'Elephant', 'Nehru Trophy Boat Race': 'River', 'Attukal Pongala': 'Fire', 'Theyyam': 'Paint', 'Pulikali': 'Tiger',
  'Munnar': 'Hill', 'Alappuzha': 'Boat', 'Wayanad': 'Forest', 'Kochi': 'Port', 'Kozhikode': 'Beach', 'Thiruvananthapuram': 'Capital', 'Bekal Fort': 'Wall', 'Varkala': 'Cliff', 'Vagamon': 'Valley', 'Kumarakom': 'Lake', 'Athirappilly': 'Water', 'Sabarimala': 'Mountain', 'Guruvayur': 'Temple', 'Edakkal Caves': 'Rock', 'Parambikulam': 'Wildlife', 'Thekkady': 'Spice',
  'Puttu': 'Steamer', 'Appam': 'Stew', 'Porotta': 'Flour', 'Dosa': 'Pan', 'Idiyappam': 'String', 'Karimeen Pollichathu': 'Banana-leaf', 'Thalassery Biriyani': 'Spice', 'Payasam': 'Milk', 'Banana Chips': 'Oil', 'Pazham Pori': 'Batter', 'Sadhya': 'Feast', 'Avial': 'Vegetable', 'Kappa': 'Root', 'Pathiri': 'Rice', 'Beef Fry': 'Pepper', 'Chatti Pathiri': 'Layer', 'Kallappam': 'Toddy', 'Unniyappam': 'Jaggery', 'Sulaimani': 'Glass', 'Halwa': 'Sweet', 'Achappam': 'Mold', 'Kuzhalappam': 'Tube', 'Banana Fritters': 'Snack', 'Mixture': 'Crunch', 'Churuttu': 'Sugar', 'Murukku': 'Spiral', 'Laddoo': 'Ball', 'Jalebi': 'Syrup', 'Mysore Pak': 'Ghee', 'Parippu Vada': 'Lentil', 'Uzhunnu Vada': 'Donut', 'Boli': 'Lentil', 'Neyyappam': 'Oil', 'Vattayappam': 'Steam', 'Elayappam': 'Leaf', 'Sukhiyan': 'Green-gram', 'Kozhukatta': 'Dumpling', 'Pazham Nirachathu': 'Stuffing', 'Mutta Mala': 'Egg',
  'Nilavilakku': 'Lamp', 'Kindhi': 'Brass', 'Uruli': 'Vessel', 'Chiruva': 'Kitchen', 'Puttukutti': 'Cylinder', 'Ammikallu': 'Stone', 'Cheenachatti': 'Iron', 'Kindi': 'Spout', 'Muram': 'Bamboo', 'Kattil': 'Wood', 'Oonjal': 'Rope', 'Kudam': 'Clay', 'Kithli': 'Kettle', 'Chumbak': 'Magnet',
  'Plavu': 'Jackfruit', 'Thegu': 'Coconut', 'Vaazha': 'Leaf', 'Aanakutty': 'Forest',
  'Auto Rickshaw': 'Meter', 'KSRTC Bus': 'Red', 'Houseboat': 'Water', 'Junkar': 'Ferry', 'Vellam': 'River', 'Lorry': 'Truck', 'Private Bus': 'Route', 'Tempo Traveller': 'Trip', 'Scooter': 'Helmet', 'Cycle': 'Wheel', 'Bullet': 'Engine', 'Train': 'Track', 'Metro': 'Station', 'Flight': 'Airport', 'Ambi': 'Car', 'Jeep': 'Mountain', 'Tractor': 'Farm', 'Excavator': 'Dig', 'Ambulance': 'Siren', 'Fire Engine': 'Ladder'
};
const IMPOSTER_MALAYALAM_SINGLE_WORDS = {
  'Adipoli': 'ആഘോഷം', 'Poli Scene': 'പാർട്ടി', 'Sadhanam Kayyil Undo': 'പെട്ടി', 'Thenga': 'മരം', 'Chetta': 'ചായ', 'Eda Mone': 'കൂട്ടുകാരൻ', 'Kidilan': 'സമ്മാനം', 'Chali': 'തമാശ', 'Koppu': 'ദേഷ്യം', 'Pani Paali': 'കുഴപ്പം', 'Ambada': 'ചിരി', 'Poda Pulle': 'യാത്ര', 'Vattaano': 'ഡോക്ടർ', 'Athu Sheri': 'ചോദ്യം', 'Thallumala': 'കൂട്ടം', 'Chummadive': 'കളി', 'Oodayi': 'വിദ്യ', 'Jada': 'സ്റ്റൈൽ', 'Vera Level': 'ആകാശം', 'Blunder': 'തെട്ട്', 'Suhurthe': 'യോഗം', 'Kittu': 'സമ്മാനം', 'Scene Contra': 'പോലീസ്', 'Chamakku': 'ഫാഷൻ',
  'Shavapetti': 'മരം', 'Pothu': 'മൃഗം', 'Kuthikazhapp': 'നൃത്തം', 'Manavalan': 'കല്യാണം', 'Ganga': 'ആഭരണം', 'Rukmini': 'പാട്ട്', 'Dashamoolam Damu': 'സംഘർഷം', 'Ramanan': 'തോട്ടം', 'Gafoor Ka Dost': 'കപ്പൽ', 'Nagavalli': 'കൊട്ടാരം', 'Appukuttan': 'ആശുപത്രി', 'Kuttahs': 'ക്യാമറ', 'C.I.D Moosa': 'നായ', 'Aadu Thoma': 'കണ്ണട', 'Dr. Sunny': 'രഹസ്യം', 'Rajavinte Makan': 'പെട്ടി', 'Sethurama Iyer': 'സുഗന്ധം', 'Thomas Kutty': 'കാർ', 'Dharam Bhai': 'സ്വർണം', 'Pavayi': 'വസ്ത്രം', 'Charly': 'ബൈക്ക്', 'Kattappana Hrithik': 'ഓഡിഷൻ',
  'Onam': 'പൂവ്', 'Vishu': 'പടക്കം', 'Thrissur Pooram': 'ആന', 'Nehru Trophy Boat Race': 'നദി', 'Attukal Pongala': 'തീ', 'Theyyam': 'ചായം', 'Pulikali': 'പുലി',
  'Munnar': 'മല', 'Alappuzha': 'ബോട്ട്', 'Wayanad': 'കാട്', 'Kochi': 'തുറമുഖം', 'Kozhikode': 'കടൽതീരം', 'Thiruvananthapuram': 'തലസ്ഥാനം', 'Bekal Fort': 'മതിൽ', 'Varkala': 'കുന്ന്', 'Vagamon': 'താഴ്വര', 'Kumarakom': 'കായൽ', 'Athirappilly': 'വെള്ളം', 'Sabarimala': 'പർവ്വതം', 'Guruvayur': 'ക്ഷേത്രം', 'Edakkal Caves': 'പാറ', 'Parambikulam': 'മൃഗം', 'Thekkady': 'സുഗന്ധം',
  'Puttu': 'പാത്രം', 'Appam': 'കറി', 'Porotta': 'മാവ്', 'Dosa': 'ചട്ടി', 'Idiyappam': 'നൂൽ', 'Karimeen Pollichathu': 'ഇല', 'Thalassery Biriyani': 'മസാല', 'Payasam': 'പാൽ', 'Banana Chips': 'എണ്ണ', 'Pazham Pori': 'മാവ്', 'Sadhya': 'വിരുന്ന്', 'Avial': 'പച്ചക്കറി', 'Kappa': 'കിഴങ്ങ്', 'Pathiri': 'അരി', 'Beef Fry': 'കുരുമുളക്', 'Chatti Pathiri': 'അടുക്ക്', 'Kallappam': 'കള്ള്', 'Unniyappam': 'ശർക്കര', 'Sulaimani': 'ഗ്ലാസ്', 'Halwa': 'മധുരം', 'Achappam': 'അച്ച്', 'Kuzhalappam': 'കുഴൽ', 'Banana Fritters': 'പലഹാരം', 'Mixture': 'മിക്സ്', 'Churuttu': 'പഞ്ചസാര', 'Murukku': 'വളയം', 'Laddoo': 'ഉരുള', 'Jalebi': 'പാനി', 'Mysore Pak': 'നെയ്യ്', 'Parippu Vada': 'പരിപ്പ്', 'Uzhunnu Vada': 'വട', 'Boli': 'പരിപ്പ്', 'Neyyappam': 'എണ്ണ', 'Vattayappam': 'ആവി', 'Elayappam': 'ഇല', 'Sukhiyan': 'പയർ', 'Kozhukatta': 'ഉരുള', 'Pazham Nirachathu': 'പലഹാരം', 'Mutta Mala': 'മുട്ട',
  'Nilavilakku': 'വിളക്ക്', 'Kindhi': 'പാത്രം', 'Uruli': 'പാത്രം', 'Chiruva': 'അടുക്കള', 'Puttukutti': 'കുറ്റി', 'Ammikallu': 'കല്ല്', 'Cheenachatti': 'ഇരുമ്പ്', 'Kindi': 'പാത്രം', 'Muram': 'മുള', 'Kattil': 'മരം', 'Oonjal': 'കയർ', 'Kudam': 'മണ്ണ്', 'Kithli': 'പാത്രം', 'Chumbak': 'കാന്തം',
  'Plavu': 'ചക്ക', 'Thegu': 'തേങ്ങ', 'Vaazha': 'ഇല', 'Aanakutty': 'കാട്',
  'Auto Rickshaw': 'മീറ്റർ', 'KSRTC Bus': 'ചുവപ്പ്', 'Houseboat': 'വെള്ളം', 'Junkar': 'യാത്ര', 'Vellam': 'നദി', 'Lorry': 'വണ്ടി', 'Private Bus': 'റൂട്ട്', 'Tempo Traveller': 'യാത്ര', 'Scooter': 'ഹെൽമെറ്റ്', 'Cycle': 'ചക്രം', 'Bullet': 'എഞ്ചിൻ', 'Train': 'ട്രാക്ക്', 'Metro': 'സ്റ്റേഷൻ', 'Flight': 'വിമാനത്താവളം', 'Ambi': 'കാർ', 'Jeep': 'മല', 'Tractor': 'പാടം', 'Excavator': 'യന്ത്രം', 'Ambulance': 'ശബ്ദം', 'Fire Engine': 'ഏണി',
  'Aanavandi': 'വണ്ടി', 'Vallam': 'കായൽ', 'Autorickshaw': 'മീറ്റർ', 'Bullet': 'ശബ്ദം', 'Kalolsavam': 'വേദി', 'Arts Day': 'ആഘോഷം', 'College Canteen': 'ചായ', 'PTA Meeting': 'യോഗം', 'Onam Celebration': 'സദ്യ', 'Football': 'മൈതാനം', 'Cricket': 'റൺസ്', 'Kabaddi': 'കളി', 'Volleyball': 'നെറ്റ്', 'Vallamkali': 'ആവേശം', 'Pravasi': 'യാത്ര', 'Dubai': 'നഗരം', 'Gulf Money': 'സമ്പത്ത്', 'Chakka': 'മരം', 'Naatilekku': 'വീട്'
};
const CATEGORY_SINGLE_WORDS = {
  'Funny Malayalam': 'Vibe', 'Movies': 'Cinema', 'Characters': 'Actor', 'Festivals': 'Celebration', 'Places': 'Travel', 'Kerala Food': 'Dish', 'Bakery & Snacks': 'Snack', 'Household Items': 'Home', 'People': 'Person', 'Kerala Life': 'Culture', 'Vehicles': 'Travel', 'College & School': 'Campus', 'Sports': 'Match', 'Gulf & NRI': 'Abroad'
};
const CATEGORY_MALAYALAM_SINGLE_WORDS = {
  'Funny Malayalam': 'വൈബ്', 'Movies': 'സിനിമ', 'Characters': 'നടൻ', 'Festivals': 'ആഘോഷം', 'Places': 'യാത്ര', 'Kerala Food': 'ഭക്ഷണം', 'Bakery & Snacks': 'പലഹാരം', 'Household Items': 'വീട്', 'People': 'ആൾ', 'Kerala Life': 'സംസ്കാരം', 'Vehicles': 'യാത്ര', 'College & School': 'ക്യാമ്പസ്', 'Sports': 'മത്സരം', 'Gulf & NRI': 'വിദേശം'
};
const MOVIE_DETAILS = {
  'Manichitrathazhu': { role: 'Iconic psychological horror thriller starring Mohanlal & Shobana about an ancient haunted mansion and split personality', roleMalayalam: 'മോഹൻലാലും ശോഭനയും തകർത്തഭിനയിച്ച പൈതൃക തറവാട്ടിലെ മാനസിക പ്രശ്നങ്ങളുടെയും നാഗവല്ലിയുടെയും കഥ' },
  'Drishyam': { role: 'Clever family thriller starring Mohanlal where a resourceful father covers up an accidental crime to save his family', roleMalayalam: 'കുടുംബത്തെ രക്ഷിക്കാൻ ബുദ്ധിപൂർവ്വം തെളിവുകൾ നശിപ്പിച്ച് പൊലീസിനെ കബളിപ്പിക്കുന്ന ജോർജ്ജുകുട്ടിയുടെ കഥ' },
  'Kumbalangi Nights': { role: 'Heartwarming coastal drama about four dysfunctional brothers finding love and brotherhood while facing Shammi', roleMalayalam: 'കുമ്പളങ്ങിയിലെ നാല് സഹോദരന്മാരുടെ ജീവിതവും സ്നേഹവും ഷമ്മിയുമായുള്ള ഏറ്റുമുട്ടലും പറയുന്ന സിനിമ' },
  'Bangalore Days': { role: 'Feel-good celebration of friendship and cousinhood starring Dulquer, Fahadh, and Nazriya exploring life in Bangalore', roleMalayalam: 'ബാംഗ്ലൂരിലേക്ക് ചേക്കേറുന്ന മൂന്ന് കസിൻസിന്റെ സൗഹൃദവും പ്രണയവും ജീവിത മാറ്റങ്ങളും' },
  'Premam': { role: 'Romantic blockbuster starring Nivin Pauly following George through three distinct stages of love across his life', roleMalayalam: 'ജോർജ്ജിന്റെ സ്കൂൾ, കോളേജ്, യുവത്വ കാലഘട്ടങ്ങളിലെ മൂന്ന് പ്രണയങ്ങളുടെ കഥ' },
  'Traffic': { role: 'High-stakes multi-narrative thriller racing against time to transport a donor organ through heavy road traffic', roleMalayalam: 'അപകടത്തിൽപ്പെട്ട കുട്ടിയുടെ ജീവൻ രക്ഷിക്കാൻ ഹൃദയവുമായി റോഡിലൂടെ നടത്തുന്ന അടിയന്തര യാത്ര' },
  'Indian Rupee': { role: 'Satirical drama starring Prithviraj about a real-estate broker chasing quick wealth and moral realities', roleMalayalam: 'എളുപ്പത്തിൽ പണക്കാരനാകാൻ റിയൽ എസ്റ്റേറ്റ് ബിസിനസിലേക്ക് ഇറങ്ങുന്ന ജയപ്രകാശിന്റെ കഥ' },
  'Romancham': { role: 'Hilarious horror-comedy about bachelors playing with an Ouija board and inviting a quirky ghost named Anamika', roleMalayalam: 'ബാംഗ്ലൂരിൽ ഒന്നിച്ച് താമസിക്കുന്ന കൂട്ടുകാർ ഓജോ ബോർഡ് കളിച്ച് അനാമിക എന്ന പ്രേതത്തെ വിളിച്ചുവരുത്തുന്ന തമാശ' },
  'Premalu': { role: 'Lighthearted romantic comedy set in Hyderabad between Sachin and Reenu exploring modern youth relationships', roleMalayalam: 'ഹൈദരാബാദിൽ വെച്ച് സച്ചിനും രേണുവും തമ്മിൽ ഉണ്ടാകുന്ന രസകരമായ പ്രണയവും സൗഹൃദവും' },
  'Aavesham': { role: 'High-octane action comedy starring Fahadh Faasil as Ranga Annan, a dancing Bangalore gangster helping three college kids', roleMalayalam: 'കോളേജിലെ സീനിയർമാരെ നേരിടാൻ ബാംഗ്ലൂരിലെ പ്രാഞ്ചിയേട്ടൻ ഗുണ്ടയായ രംഗ അണ്ണന്റെ സഹായം തേടുന്ന കുട്ടികളുടെ കഥ' },
  'Bramayugam': { role: 'Monochrome folk-horror mystery starring Mammootty inside a cursed, time-twisted ancient mana ruled by Kodumon Potti', roleMalayalam: 'മമ്മൂട്ടി അഭിനയിച്ച ഭയപ്പെടുത്തുന്ന പഴയകാല മനയിലെ നിഗൂഢതകളും കാലത്തിന്റെ കളിപ്പാട്ടമായ മനുഷ്യരും' },
  'Manjummel Boys': { role: 'Gripping survival thriller based on true events where friends risk their lives to rescue a buddy from Guna Caves', roleMalayalam: 'കൊടൈക്കനാലിലെ ഗുണ കേവ്സിൽ വീണുപോയ കൂട്ടുകാരനെ ജീവൻ പണയം വെച്ച് രക്ഷിക്കുന്ന സുഹൃത്തുക്കളുടെ കഥ' },
  'Godfather': { role: 'Evergreen comedy classic about the fierce rivalry between Anjooran’s all-male family and Achamma’s household', roleMalayalam: 'അഞ്ഞൂറാന്റെയും ആനപ്പാറ അച്ചമ്മയുടെയും കുടുംബങ്ങൾ തമ്മിലുള്ള വൈരാഗ്യവും തമാശ നിറഞ്ഞ പ്രണയവും' },
  'Malaikottai Vaaliban': { role: 'Periodic action fantasy about an undisputed traveling wrestler who conquers champions across desert lands', roleMalayalam: 'നാടോടി ഗുസ്തിക്കാരനായ വാലിബൻ വിവിധ നാടുകളിലെ വീരന്മാരെ പരാജയപ്പെടുത്തുന്ന നാടോടിക്കഥ' },
  'Minnal Murali': { role: 'Superhero origin story starring Tovino Thomas where a tailor gains lightning superpowers alongside a tragic villain', roleMalayalam: 'മിന്നലേറ്റു സൂപ്പർ പവറുകൾ ലഭിച്ച തയ്യൽക്കാരനായ ജെയ്സന്റെയും വില്ലനായ ഷിബുവിന്റെയും കഥ' },
  'Kishkindha Kaandam': { role: 'Intense forest-border psychological mystery involving a retired military father, his son, and a missing child inquiry', roleMalayalam: 'വനമേഖലയോട് ചേർന്ന വീട്ടിൽ നടക്കുന്ന നിഗൂഢമായ അന്വേഷണങ്ങളും മുൻ പട്ടാളക്കാരനായ അച്ഛന്റെയും മകന്റെയും കഥ' },
  'Rorschach': { role: 'Dark psychological revenge thriller starring Mammootty tracking down a faceless ghost-like enemy with a white mask', roleMalayalam: 'തന്റെ ഭാര്യയെ കൊന്ന മുഖംമൂടിക്കാരനായ പ്രതിയെ തേടി ലൂക്ക് ആന്റണി നടത്തുന്ന നിഗൂഢമായ പ്രതികാരം' },
  'Kattappanayile Rithwik Roshan': { role: 'Inspirational comedy about an ordinary village guy aspiring to become a cinema hero despite societal stereotypes', roleMalayalam: 'സിനിമാ നടനാകാൻ ആഗ്രഹിച്ച് കട്ടപ്പനയിൽ ജീവിക്കുന്ന കിച്ചുവിന്റെ സിനിമാ മോഹങ്ങളും തമാശകളും' },
  'Varathan': { role: 'Action-packed home-invasion thriller starring Fahadh Faasil defending his remote plantation estate from hostile locals', roleMalayalam: 'നാട്ടിൻപുറത്തെ എസ്റ്റേറ്റ് വീട്ടിൽ അതിക്രമിച്ചുകയറുന്ന നാട്ടുകാരെ ധീരമായി നേരിടുന്ന അബിയുടെയും പ്രിയയുടെയും കഥ' },
  'Bheeshma Parvam': { role: 'Stylish gangster family saga starring Mammootty as Michael Anjoottikkaran reigning over Mattancherry', roleMalayalam: 'മട്ടാഞ്ചേരിയിലെ അഞ്ചൂട്ടി കുടുംബത്തിന്റെ കാരണവരും കരുത്തനുമായ മൈക്കിൾ അപ്പന്റെ കഥ' },
  'Memories': { role: 'Edge-of-the-seat crime investigative thriller where an alcoholic police officer tracks a twisted serial killer', roleMalayalam: 'കുടുംബം നഷ്ടപ്പെട്ട ദുഃഖത്തിൽ മദ്യപാനിയായ പോലീസ് ഉദ്യോഗസ്ഥൻ ഒരു സീരിയൽ കില്ലറെ കണ്ടെത്തുന്ന അന്വേഷണം' },
  'Classmates': { role: 'Nostalgic campus romance and murder mystery surrounding a college reunion and long-buried secret diaries', roleMalayalam: 'കോളേജ് റീയൂണിയനിടയിൽ നടക്കുന്ന കൊലപാതക ശ്രമവും പഴയകാല ക്യാമ്പസ് പ്രണയ സൗഹൃദങ്ങളുടെയും കഥ' },
  'Spadikam': { role: 'Cult action drama starring Mohanlal as Aadu Thoma, the rebellious quarry owner and Ray-Ban wearing lorry driver', roleMalayalam: 'കണക്കുമാഷായ അച്ഛന്റെ കർക്കശ സ്വഭാവം മൂലം നാടുവിട്ടുപോയി ആടുകളെയും ലോറികളെയും സ്നേഹിക്കുന്ന ആടു തോമയുടെ കഥ' }
};
const CHARACTER_DETAILS = {
  'Georgekutty': { movie: 'Drishyam', movieMalayalam: 'ദൃശ്യം', role: 'Resourceful cable operator who cleverly covers up an accidental crime to protect his family', roleMalayalam: 'കുടുംബത്തെ രക്ഷിക്കാൻ അപകടകരമായ ഒരു രഹസ്യം മറച്ചുവെക്കുന്ന കേബിൾ ടിവി ഓപ്പറേറ്റർ' },
  'Nagavalli': { movie: 'Manichitrathazhu', movieMalayalam: 'മണിച്ചിത്രത്താഴ്', role: 'Vengeful spirit of an ancient Tamil dancer whose persona takes over Ganga', roleMalayalam: 'പഴയകാലത്തെ ദുരന്തകഥയുള്ള തമിഴ് നർത്തകിയുടെ പ്രതികാരദാഹിയായ ആത്മാവ്' },
  'Sethumadhavan': { movie: 'Kireedam', movieMalayalam: 'കിരീടം', role: 'Innocent young man aspiring to be a police officer whose life turns tragic after fighting a local goon', roleMalayalam: 'പോലീസുകാരനാകാൻ ആഗ്രഹിച്ച് സാഹചര്യങ്ങൾ കൊണ്ട് ഗുണ്ടയുമായി ഏറ്റുമുട്ടേണ്ടി വന്ന ചെറുപ്പക്കാരൻ' },
  'Dasan': { movie: 'Nadodikkattu', movieMalayalam: 'നാടോടിക്കാറ്റ്', role: 'Unemployed youth who dreams of going to Dubai but gets tricked into landing in Madras and becomes a CID', roleMalayalam: 'ദുബായിലേക്ക് പോകാൻ ആഗ്രഹിച്ച് ഗഫൂർ ചതിച്ചതുകൊണ്ട് മദ്രാസിൽ എത്തി സിഐഡി ആയ യുവാവ്' },
  'Mangalassery Neelakandan': { movie: 'Devasuram', movieMalayalam: 'ദേവാസുരം', role: 'Proud and powerful feudal lord whose life and arrogance transform through love and rivalry', roleMalayalam: 'അഭിമാനിയും പ്രബലനുമായ ജന്മിയും ശേഖരനുമായുള്ള വൈരാഗ്യത്തിലൂടെ ജീവിതം മാറിയ വ്യക്തിയും' },
  'Appukuttan': { movie: 'Ramji Rao Speaking', movieMalayalam: 'റാംജി റാവു സ്പീക്കിംഗ്', role: 'Innocent, talkative, and humorous bachelor friend who always causes funny misunderstandings', roleMalayalam: 'എപ്പോഴും തമാശയുള്ള അബദ്ധങ്ങൾ വരുത്തിവെക്കുന്ന സംസാരപ്രിയനായ സുഹൃത്ത്' },
  'Ramanan': { movie: 'Punjabi House', movieMalayalam: 'പഞ്ചാബി ഹൗസ്', role: 'Hilarious and loyal servant of Muthalali famous for his witty retorts and unforgettable dialogues', roleMalayalam: 'മുതലാളിയുടെ വിശ്വസ്തനും തമാശ നിറഞ്ഞ മറുപടികളിലൂടെ ചിരിപ്പിക്കുന്നതുമായ സഹായി' },
  'Induchoodan': { movie: 'Narasimham', movieMalayalam: 'നരസിംഹം', role: 'Bold, fiery, and righteous hero who fights for justice and family honor', roleMalayalam: 'നീതിക്കും കുടുംബത്തിന്റെ അഭിമാനത്തിനും വേണ്ടി പോരാടുന്ന തന്റേടമുള്ള നായകൻ' },
  'Kunjikoonan': { movie: 'Kunjikoonan', movieMalayalam: 'കുഞ്ഞിക്കൂനൻ', role: 'Kind-hearted and selfless village hunchback whose pure love touches everyone around him', roleMalayalam: 'നിഷ്കളങ്കമായ സ്നേഹത്തോടെ എല്ലാവരെയും സഹായിക്കുന്ന ഗ്രാമത്തിലെ കൂനൻ' },
  'Koshy Kurien': { movie: 'Ayyappan & Koshiyum', movieMalayalam: 'അയ്യപ്പനും കോശിയും', role: 'Wealthy, influential ex-havildar whose ego clash with a police officer sparks an intense feud', roleMalayalam: 'പോലീസ് ഉദ്യോഗസ്ഥനുമായുള്ള ഈഗോ പ്രശ്നം വലിയ തർക്കത്തിന് വഴിവെക്കുന്ന സമ്പന്നനായ മുൻ പട്ടാളക്കാരൻ' },
  'Ayyappan Nair': { movie: 'Ayyappan & Koshiyum', movieMalayalam: 'അയ്യപ്പനും കോശിയും', role: 'Strict and principled senior police officer who reveals his fierce past when his self-respect is challenged', roleMalayalam: 'ആത്മാഭിമാനത്തെ ചോദ്യം ചെയ്തപ്പോൾ തന്റെ പഴയ കരുത്ത് പുറത്തെടുക്കുന്ന സീനിയർ പോലീസ് ഉദ്യോഗസ്ഥൻ' },
  'Mahesh Bhavana': { movie: 'Maheshinte Prathikaaram', movieMalayalam: 'മഹേഷിന്റെ പ്രതികാരം', role: 'Simple village photographer who takes a vow not to wear slippers until he avenges his public humiliation', roleMalayalam: 'തനിക്ക് നേരിട്ട അപമാനത്തിന് പകരം ചോദിക്കുന്നതുവരെ ചെരുപ്പിടില്ലെന്ന് പ്രതിജ്ഞ ചെയ്ത സ്റ്റുഡിയോ ഫോട്ടോഗ്രാഫർ' },
  'Biju Paulose': { movie: 'Action Hero Biju', movieMalayalam: 'ആക്ഷൻ ഹീറോ ബിജു', role: 'Dedicated and realistic Sub-Inspector of Police handling everyday city crimes and human situations', roleMalayalam: 'ദൈനംദിന കേസുകളും സാധാരണക്കാരുടെ പ്രശ്നങ്ങളും കൈകാര്യം ചെയ്യുന്ന സിൻസിയറായ സബ് ഇൻസ്പെക്ടർ' },
  'Rameshan Nair': { movie: 'Thanmathra', movieMalayalam: 'തന്മാത്ര', role: 'Caring government employee and loving father whose heartbreaking struggle with Alzheimer’s touches deeply', roleMalayalam: 'അൽസ്ഹൈമേഴ്സ് രോഗം ബാധിച്ച് ഓർമ്മകൾ നഷ്ടപ്പെടുന്ന സ്നേഹസമ്പന്നനായ സർക്കാർ ഉദ്യോഗസ്ഥനും പിതാവും' },
  'Pachu': { movie: 'Pachuvum Athbutha Vilakkum', movieMalayalam: 'പാച്ചുവും അത്ഭുത വിളക്കും', role: 'Helpful and resourceful young man whose journey to rescue a young girl changes his perspective on life', roleMalayalam: 'ഒരു അമ്മൂമ്മയെയും പെൺകുട്ടിയെയും സഹായിക്കാനായി യാത്ര തിരിച്ച സ്നേഹമുള്ള ചെറുപ്പക്കാരൻ' },
  'Kunjiraman': { movie: 'Kunjiramayanam', movieMalayalam: 'കുഞ്ഞിരാമായണം', role: 'Well-meaning village youth whose hilarious rivalry and attempts to get married keep the village entertained', roleMalayalam: 'കല്യാണം കഴിക്കാൻ ശ്രമിക്കുന്നതും ഗ്രാമത്തിൽ രസകരമായ തർക്കങ്ങളുണ്ടാക്കുന്നതുമായ യുവാവ്' },
  'Pavanayi': { movie: 'Nadodikkattu', movieMalayalam: 'നാടോടിക്കാറ്റ്', role: 'Overconfident and comical underworld hitman (P.V. Narayanan) from Bombay whose weapons and plans fail miserably', roleMalayalam: 'ബോംബെയിൽ നിന്നും ആയുധങ്ങളുമായി വന്ന വലിയ അവകാശവാദങ്ങൾ ഉന്നയിച്ച തമാശക്കാരനായ കൊലയാളി' },
  'Manavalan': { movie: 'Pulival Kalyanam', movieMalayalam: 'പുലിവാൽ കല്യാണം', role: 'Hilarious taxi company owner famous for his yellow shirt, quirky business ideas, and legendary dialogues', roleMalayalam: 'മഞ്ഞ ഷർട്ടിട്ട് രസകരമായ തട്ടിപ്പുകളും തമാശ ഡയലോഗുകളുമായി നടക്കുന്ന ടാക്സി കമ്പനി ഉടമ' },
  'Ganga': { movie: 'Manichitrathazhu', movieMalayalam: 'മണിച്ചിത്രത്താഴ്', role: 'Innocent young wife whose fascination with ancient folklore leads her split personality to embody Nagavalli', roleMalayalam: 'പഴയ തറവാട്ടിലെ ഐതിഹ്യങ്ങളിൽ ആകൃഷ്ടയായി നാഗവല്ലിയുടെ ഭാവം ഉൾക്കൊണ്ട യുവതി' },
  'Rukmini': { movie: 'Nandanam', movieMalayalam: 'നന്ദനം', role: 'Traditional, innocent elderly maid whose devoted nature and humorous confusion bring warmth to the ancestral home', roleMalayalam: 'തറവാട്ടിലെ കാര്യങ്ങൾ നോക്കിനടത്തുന്ന നിഷ്കളങ്കയും ഭക്തയുമായ പ്രായമുള്ള വേലക്കാരി' },
  'Girish M.A.': { movie: 'Premalu', movieMalayalam: 'പ്രേമലു', role: 'Hilariously confident yet clumsy IT bachelor whose attempts at romance and rivalry create non-stop fun', roleMalayalam: 'പ്രണയിക്കാൻ ശ്രമിക്കുന്നതിനിടയിൽ രസകരമായ അബദ്ധങ്ങൾ കാണിക്കുന്ന ഐടി ചെറുപ്പക്കാരൻ' },
  'Shammi': { movie: 'Kumbalangi Nights', movieMalayalam: 'കുമ്പളങ്ങി നൈറ്റ്സ്', role: 'Hyper-masculine, controlling, and eerily smiling houseguest who obsessively claims to be the complete man', roleMalayalam: 'വീട്ടിലെ കാര്യങ്ങളെല്ലാം നിയന്ത്രിക്കാൻ ശ്രമിക്കുന്ന ഭയാനകമായ ചിരിയുള്ള വ്യക്തി' },
  'Ranga': { movie: 'Aavesham', movieMalayalam: 'ആവേശം', role: 'Flamboyant, kind-hearted Bangalore gangster (Ranga Annan) who loves dancing, reels, and protecting college kids', roleMalayalam: 'കോളേജ് പിള്ളേരെ സഹായിക്കാനും റീൽസ് ചെയ്യാനും ഇഷ്ടപ്പെടുന്ന ആവേശക്കാരനായ ബാംഗ്ലൂർ ഗുണ്ട' },
  'Dashamoolam Damu': { movie: 'Chattambinadu', movieMalayalam: 'ചട്ടമ്പിനാട്', role: 'Boastful and cowardly local goon whose hilarious facial expressions made him Kerala’s ultimate meme king', roleMalayalam: 'വലിയ വീരവാദം പറയുമെങ്കിലും പേടിത്തൊണ്ടനായ ട്രോളുകളിലെ പ്രിയപ്പെട്ട കഥാപാത്രം' },
  'Gafoor Ka Dosth': { movie: 'Nadodikkattu', movieMalayalam: 'നാടോടിക്കാറ്റ്', role: 'Sly and humorous boat captain (Gafoor) who tricks Dasan and Vijayan into boarding a boat to Madras instead of Dubai', roleMalayalam: 'ദാസനെയും വിജയനെയും ദുബായിലാക്കാമെന്ന് പറഞ്ഞ് കബളിപ്പിച്ച് മദ്രാസിലെത്തിച്ച വഞ്ചിക്കാരൻ' },
  'Anandavalli': { movie: 'Achuvinte Amma', movieMalayalam: 'അച്ചുവിന്റെ അമ്മ', role: 'Resilient, cheerful, and loving single mother who shares a beautiful, friend-like bond with her daughter', roleMalayalam: 'മകളോട് കൂട്ടുകാരിയെപ്പോലെ ഇടപെടുന്ന കരുത്തയും സ്നേഹസമ്പന്നയുമായ അമ്മ' },
  'Beemboy': { movie: 'CID Moosa', movieMalayalam: 'സിഐഡി മൂസ', role: 'Immensely strong yet gentle-hearted mute assistant of CID Moosa who easily lifts heavy opponents and doors', roleMalayalam: 'സിഐഡി മൂസയുടെ സഹായിയും വലിയ ഭാരങ്ങളും ആളുകളെയും നിഷ്പ്രയാസം ഉയർത്തുന്ന കരുത്തനും' },
  'Kattalan Porinchu': { movie: 'Porinju Mariam Jose', movieMalayalam: 'പൊറിഞ്ചു മറിയം ജോസ്', role: 'Fearless market butcher whose loyal friendships and silent, undying love form the emotional core of the town', roleMalayalam: 'ചന്തയിലെ കരുത്തനും കൂട്ടുകാരോടും പ്രിയപ്പെട്ടവളോടും ആഴത്തിലുള്ള സ്നേഹം സൂക്ഷിക്കുന്നവനും' },
  'Digambaran': { movie: 'Anandabhadram', movieMalayalam: 'അനന്തഭദ്രം', role: 'Dark, powerful, and mesmerizing sorcerer who performs occult rituals and body transformation to gain immortality', roleMalayalam: 'അമാനുഷിക ശക്തിയും അനശ്വരതയും നേടാനായി മന്ത്രവാദവും ആഭിചാരവും ചെയ്യുന്ന മാന്ത്രികൻ' },
  'Dileep Role': { movie: 'CID Moosa', movieMalayalam: 'സിഐഡി മൂസ', role: 'Enthusiastic private detective (Sahadevan / CID Moosa) whose funny gadgets and slapstick methods solve big crimes', roleMalayalam: 'രസകരമായ ഉപകരണങ്ങളും തമാശകളുമായി കേസുകൾ അന്വേഷിക്കുന്ന പ്രൈവറ്റ് ഡിറ്റക്ടീവ് സിഐഡി മൂസ' },
  'Kuttan': { movie: 'Bangalore Days', movieMalayalam: 'ബാംഗ്ലൂർ ഡെയ്സ്', role: 'Naive and traditional village youth (Joshy / Kuttan) who moves to Bangalore for IT work and discovers city life', roleMalayalam: 'ബാംഗ്ലൂരിൽ ഐടി ജോലിക്ക് പോയ നിഷ്കളങ്കനും നാട്ടിൻപുറത്തുകാരനുമായ കസിൻ' },
  'Krishnan': { movie: 'Kammatipaadam', movieMalayalam: 'കമ്മട്ടിപ്പാടം', role: 'Loyal friend who returns to Kochi to search for his missing buddy and uncovers the gritty history of their old colony', roleMalayalam: 'കാണാതായ തന്റെ പഴയ സുഹൃത്തിനെ തേടി നാട്ടിലെത്തി കമ്മട്ടിപ്പാടത്തിന്റെ ചരിത്രം ഓർത്തെടുക്കുന്നയാൾ' },
  'Sachy': { movie: 'Driving Licence', movieMalayalam: 'ഡ്രൈവിംഗ് ലൈസൻസ്', role: 'Strict Motor Vehicle Inspector and die-hard superstar fan (Kuruvila Joseph) whose hurt pride leads to a public clash', roleMalayalam: 'തന്റെ പ്രിയപ്പെട്ട സിനിമാ നടനുമായുള്ള തെറ്റിദ്ധാരണ മൂലം വാശിയിലാകുന്ന മോട്ടോർ വെഹിക്കിൾ ഇൻസ്പെക്ടർ' },
  'Aadu Thoma': { movie: 'Spadikam', movieMalayalam: 'സ്ഫടികം', role: 'Rebellious quarry owner and lorry driver (Thomas Chacko) with Ray-Ban glasses who defied his strict mathematician father', roleMalayalam: 'റെയ്ബാൻ ഗ്ലാസ്സുവെച്ച് ജീവിക്കുന്ന ധീരനായ ലോറി ഡ്രൈവറും ക്വാറി ഉടമയുമായ തോമസ് ചാക്കോ' },
  'Keeleri Achu': { movie: 'Kalyanaraman', movieMalayalam: 'കല്യാണരാമൻ', role: 'Comical muscleman and gym master whose harmless boasting and physical stunts create riotous wedding laughter', roleMalayalam: 'വലിയ ഗുണ്ടയാണെന്ന് ഭാവിക്കുന്ന തമാശക്കാരനായ ജിം മാസ്റ്റർ' },
  'Niranjan': { movie: 'Summer in Bethlehem', movieMalayalam: 'സമ്മർ ഇൻ ബേത്‌ലഹേം', role: 'Philosophical death-row prisoner who shares a deeply moving final meeting with his beloved before his execution', roleMalayalam: 'വധശിക്ഷയ്ക്ക് മുമ്പ് തനിക്ക് പ്രിയപ്പെട്ടവളെ അവസാനമായി കാണുന്ന വൈകാരികമായ കഥാപാത്രം' }
};
function chooseWord(){const usable=packs.filter(p=>selected.has(p.id));if(!usable.length){packs.forEach(p=>selected.add(p.id));}const category=usable[Math.floor(Math.random()*usable.length)]||packs[0];const picked=category.words[Math.floor(Math.random()*category.words.length)];const impWord=IMPOSTER_SINGLE_WORDS[picked[0]]||(picked[2]?picked[2].split(' ')[0].replace(/[^a-zA-Z]/g,''):'')||CATEGORY_SINGLE_WORDS[category.name]||'Secret';const impMalWord=IMPOSTER_MALAYALAM_SINGLE_WORDS[picked[0]]||(picked[3]?picked[3].trim().split(/\s+/)[0].replace(/[^a-zA-Z\u0D00-\u0D7F]/g,''):'')||CATEGORY_MALAYALAM_SINGLE_WORDS[category.name]||'രഹസ്യം';word={latin:picked[0],malayalam:picked[1],hintLatin:impWord,hintMalayalam:impMalWord,imposterWord:impWord,category:category.name};const charDetails=CHARACTER_DETAILS[picked[0]];const movieDetails=MOVIE_DETAILS?MOVIE_DETAILS[picked[0]]:null;if(charDetails){word.movieName=charDetails.movie;word.movieMalayalam=charDetails.movieMalayalam;word.characterRole=charDetails.role;word.characterRoleMalayalam=charDetails.roleMalayalam;word.detailType='character';}else if(movieDetails){word.movieName=picked[0];word.movieMalayalam=picked[1]||picked[0];word.characterRole=movieDetails.role;word.characterRoleMalayalam=movieDetails.roleMalayalam;word.detailType='movie';}else if(category.id==='characters'||category.name==='Characters'){word.movieName='Malayalam Movie';word.movieMalayalam='മലയാള സിനിമ';word.characterRole=picked[2]||'Famous Character';word.characterRoleMalayalam=picked[3]||'പ്രശസ്ത കഥാപാത്രം';word.detailType='character';}const indices=players.map((_,idx)=>idx);for(let i=indices.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[indices[i],indices[j]]=[indices[j],indices[i]];}imposters=new Set(indices.slice(0,Math.min(imposterCount,players.length-1)))}
function startRound(){chooseWord();currentPlayer=0;showPass()};
let isSwipedUp = false;
function showPass(){if($('passName'))$('passName').textContent=players[currentPlayer]||`Player ${currentPlayer+1}`;if($('roundNumber'))$('roundNumber').textContent=round;showMalayalam=false;renderRoleView();show('pass');isSwipedUp=false;const card=$('roleSwipeCard');if(card){card.style.transition='none';card.style.transform='translateY(0)';const span=card.querySelector('.swipe-card-overlay span');if(span)span.textContent='Swipe up to reveal';}};
function showReveal(){showMalayalam=false;renderRoleView();show('pass');}
function renderRoleView(){if(typeof document==='undefined')return;const isImposter=imposters.has(currentPlayer);if($('roleBadge')){$('roleBadge').textContent=isImposter?(imposters.size>1?'You are one of the Imposters!':'You are the Imposter!'):'You are a player';$('roleBadge').className=`role-badge ${isImposter?'imposter':''}`}if(isImposter){if($('secretLabel'))$('secretLabel').style.display='none';if($('secretWord'))$('secretWord').textContent=showMalayalam?word.hintMalayalam:word.imposterWord;if($('scriptToggle')){$('scriptToggle').hidden=!(word&&(word.hintLatin||word.hintMalayalam));$('scriptToggle').textContent=showMalayalam?'Show in Manglish':'Show in Malayalam'}if($('secretHint')){$('secretHint').innerHTML=`<small style="color:var(--muted);font-size:12px;display:block;margin-top:6px;line-height:1.4;">Related to the actual word, but far from it. Blend in without guessing!</small>`;}}else{if($('secretLabel')){$('secretLabel').style.display='';$('secretLabel').textContent='SECRET WORD'}if($('scriptToggle')){$('scriptToggle').hidden=false;$('scriptToggle').textContent=showMalayalam?'Show in Manglish':'Show in Malayalam'}if($('secretWord'))$('secretWord').textContent=showMalayalam?word.malayalam:word.latin;if($('secretHint')){let hintHTML=[];if($('seeCategory')?.checked&&word&&word.category){hintHTML.push(`<span style="color:#a9a4b3;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;display:block;">Category</span><b style="color:var(--accent);font-size:16px;display:block;margin-top:2px;">${word.category}</b>`)}if(word&&word.movieName&&word.characterRole){const mov=showMalayalam?(word.movieMalayalam||word.movieName):word.movieName;const rol=showMalayalam?(word.characterRoleMalayalam||word.characterRole):word.characterRole;const isMovie=word.detailType==='movie'||word.category==='Movies';const movLbl=showMalayalam?'സിനിമ: ':'Movie: ';const rolLbl=showMalayalam?(isMovie?'കഥാസാരം: ':'കഥാപാത്രം: '):(isMovie?'Synopsis/Story: ':'Role: ');hintHTML.push(`<div style="background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.14);border-radius:10px;padding:10px 12px;margin-top:4px;text-align:left;"><div style="font-size:13px;color:var(--accent);margin-bottom:4px;"><b>🎬 ${movLbl}${mov}</b></div><div style="font-size:12.5px;color:var(--text);line-height:1.4;"><b>${rolLbl}</b>${rol}</div></div>`)}if(hintHTML.length===0){$('secretHint').innerHTML='Everyone else has this word too. Keep it hidden!'}else{$('secretHint').innerHTML=hintHTML.join('<div style="height:8px"></div>')}}}}
function startTimer(){clearInterval(timerId);const minutes=parseInt($('durationSelect')?.value||2,10);let left=minutes*60;const total=left;const draw=()=>{const m=Math.floor(left/60),s=left%60;if($('timer'))$('timer').textContent=`${m}:${String(s).padStart(2,'0')}`;if($('timerRing'))$('timerRing').style.strokeDashoffset=327*(1-left/total)};draw();timerId=setInterval(()=>{left--;draw();if(left<=0){clearInterval(timerId);showVote()}},1000)}
function showVote(){if(typeof document==='undefined')return;clearInterval(timerId);selectedVote=-1;const list=$('voteList');if(!list)return;list.innerHTML='';players.forEach((name,i)=>{const b=document.createElement('button');b.className='vote-option';b.innerHTML=`<span class="avatar">${i+1}</span><span>${name}</span>`;b.onclick=()=>{document.querySelectorAll('.vote-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedVote=i;if($('revealResult')){$('revealResult').disabled=false;$('revealResult').classList.remove('disabled')}};list.append(b)});if($('revealResult')){$('revealResult').disabled=true;$('revealResult').classList.add('disabled')} show('vote')}
function result(){const caught=imposters.has(selectedVote);const who=Array.from(imposters).map(i=>players[i]).join(', ');if($('resultIcon')){$('resultIcon').className=`result-icon ${caught?'':'fail'}`;$('resultIcon').textContent=caught?'✦':'!'}if($('resultEyebrow'))$('resultEyebrow').textContent=caught?'GOT THEM!':'OH NO!';if($('resultTitle'))$('resultTitle').textContent=caught?'The Imposter is caught!':(imposters.size>1?'The Imposters win!':'The Imposter wins!');if($('resultText'))$('resultText').textContent=`${who} ${imposters.size>1?'were the Imposters':'was the Imposter'}.`;if($('answerWord'))$('answerWord').textContent=word?.latin||'';show('result')}
const bindClick=(id,fn)=>{const el=$(id);if(el)el.onclick=fn;};
if(typeof window!=='undefined'&&typeof document!=='undefined'){
bindClick('themeToggle',()=>{document.body.classList.toggle('light');if($('themeToggle'))$('themeToggle').textContent=document.body.classList.contains('light')?'☾':'☀'});
bindClick('startSetup',()=>show('setup'));
bindClick('openHelp',()=>show('help'));
bindClick('openSettings',()=>show('setup'));
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
bindClick('addPlayer',()=>{if(players.length<10){players.push(`Player ${players.length+1}`);if($('playerList'))renderPlayers();savePlayers();}});
bindClick('openCategories',()=>{if($('categoryGrid'))renderCategories();show('categories')});
bindClick('selectAll',()=>{packs.forEach(p=>selected.add(p.id));if($('categoryGrid'))renderCategories();if($('categorySummary'))updateCategoryText()});
bindClick('clearAll',()=>{selected.clear();if($('categoryGrid'))renderCategories();if($('categorySummary'))updateCategoryText()});
bindClick('beginRound',startRound);
const card=$('roleSwipeCard');
if(card){
  let startY=0, currentY=0, isDragging=false;
  const updateOverlayText=(swiped)=>{const span=card.querySelector('.swipe-card-overlay span');if(span)span.textContent=swiped?'Swiped ↑ (Swipe down)':'Swipe up to reveal';};
  const onDragStart=(y)=>{startY=y;currentY=y;isDragging=true;card.style.transition='none';};
  const onDragMove=(y)=>{if(!isDragging)return;currentY=y;const delta=currentY-startY;if(!isSwipedUp){if(delta<0)card.style.transform=`translateY(${delta}px)`;}else{if(delta>0)card.style.transform=`translateY(calc(-100% + 25vh + ${delta}px))`;}};
  const onDragEnd=()=>{if(!isDragging)return;isDragging=false;const delta=currentY-startY;card.style.transition='transform 0.4s cubic-bezier(0.16, 1, 0.3, 1)';if(!isSwipedUp){if(delta<-55){card.style.transform='translateY(calc(-100% + 25vh))';isSwipedUp=true;updateOverlayText(true);}else{card.style.transform='translateY(0)';}}else{if(delta>25||Math.abs(delta)<8){card.style.transform='translateY(0)';isSwipedUp=false;updateOverlayText(false);}else{card.style.transform='translateY(calc(-100% + 25vh))';}}};
  card.addEventListener('touchstart',e=>{if(e.touches&&e.touches[0])onDragStart(e.touches[0].clientY);},{passive:true});
  card.addEventListener('touchmove',e=>{if(e.touches&&e.touches[0])onDragMove(e.touches[0].clientY);},{passive:true});
  card.addEventListener('touchend',()=>onDragEnd(),{passive:true});
  card.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;card.setPointerCapture(e.pointerId);onDragStart(e.clientY);});
  card.addEventListener('pointermove',e=>onDragMove(e.clientY));
  card.addEventListener('pointerup',e=>{card.releasePointerCapture(e.pointerId);onDragEnd();});
  card.addEventListener('pointercancel',()=>onDragEnd());
}
const revealScreen=$('reveal');
if(revealScreen){
  let rStartY=0,rCurrentY=0,rDragging=false;
  const onRStart=(y)=>{rStartY=y;rCurrentY=y;rDragging=true;};
  const onRMove=(y)=>{if(!rDragging)return;rCurrentY=y;};
  const onREnd=()=>{if(!rDragging)return;rDragging=false;if(rCurrentY-rStartY>80&&$('hideRole')){$('hideRole').click();}};
  revealScreen.addEventListener('touchstart',e=>{if(e.touches&&e.touches[0])onRStart(e.touches[0].clientY);},{passive:true});
  revealScreen.addEventListener('touchmove',e=>{if(e.touches&&e.touches[0])onRMove(e.touches[0].clientY);},{passive:true});
  revealScreen.addEventListener('touchend',()=>onREnd(),{passive:true});
}
bindClick('scriptToggle',()=>{showMalayalam=!showMalayalam;renderRoleView()});
bindClick('hideRole',()=>{currentPlayer++;if(currentPlayer<players.length){showPass();}else{show('clues');startTimer();}});
bindClick('skipDiscussion',showVote);
bindClick('revealResult',result);
bindClick('nextRound',()=>{round++;startRound()});
bindClick('goHome',()=>show('home'));
bindClick('removeImposter',()=>{if(imposterCount>1){imposterCount--;if($('imposterTotal'))$('imposterTotal').textContent=imposterCount}});
bindClick('addImposter',()=>{const maxImp=Math.max(1,Math.floor(players.length/2));if(imposterCount<maxImp){imposterCount++;if($('imposterTotal'))$('imposterTotal').textContent=imposterCount}});
const exitGameHandler=(e)=>{if(e&&e.stopPropagation)e.stopPropagation();if(confirm('Do you want to leave the game?')){show('setup');}};
if($('exitGame'))$('exitGame').onclick=exitGameHandler;
if($('exitReveal'))$('exitReveal').onclick=exitGameHandler;
bindClick('roleHelp',()=>show('help'));
if($('playerList'))renderPlayers();if($('categorySummary'))updateCategoryText();hideLoader();
}
