import json

replacements = {
    'KSEB': ('Water Authority', 'വാട്ടർ അതോറിറ്റി'),
    'Lorry': ('Tipper', 'ടിപ്പർ'),
    'Thengu': ('Kamuku', 'കമുകു'),
    'Thiri': ('Mezhukuthiri', 'മെഴുകുതിരി'),
    'Bullet': ('Pulsar', 'പൾസർ'),
    'Milma': ('Supplyco', 'സപ്ലൈകോ'),
    'Vayanasala': ('Club', 'ക്ലബ്'),
    'Sreenivasan': ('Jagathy Sreekumar', 'ജഗതി ശ്രീകുമാർ'),
    'Soubin Shahir': ('Sreenath Bhasi', 'ശ്രീനാഥ് ഭാസി'),
    'Salim Kumar': ('Suraj Venjaramoodu', 'സുരാജ് വെഞ്ഞാറമൂട്'),
    'Kaithari': ('Khadi', 'ഖാദി'),
    'Speed Boat': ('Jankar', 'ജങ്കാർ'),
    'Biju Menon': ('Suresh Gopi', 'സുരേഷ് ഗോപി'),
    'Current Bill': ('Water Bill', 'വാട്ടർ ബിൽ'),
    'Batch': ('Class', 'ക്ലാസ്സ്'),
    'Train': ('Metro', 'മെട്രോ'),
    'Aishwarya Lekshmi': ('Nazriya Nazim', 'നസ്രിയ നസീം'),
    'Parvathy Thiruvothu': ('Manju Warrier', 'മഞ്ജു വാര്യർ'),
    'Chavittu Vandi': ('Cycle', 'സൈക്കിൾ'),
    'Chattuvam': ('Thavi', 'തവി'),
    'Ambassador': ('Contessa', 'കോണ്ടസ്സ'),
    'Mohanlal': ('Mammootty', 'മമ്മൂട്ടി'),
    'Kindu Brass': ('Nilavilakku', 'നിലവിളക്ക്'),
    'Canara Bank Challan': ('SBI Passbook', 'എസ്ബിഐ പാസ്സ്ബുക്ക്'),
    'Nivin Pauly': ('Dulquer Salmaan', 'ദുൽഖർ സൽമാൻ'),
    'Mammootty': ('Mohanlal', 'മോഹൻലാൽ'),
    'Kochi Metro': ('Water Metro', 'വാട്ടർ മെട്രോ'),
    'Panchayath': ('Municipality', 'മുൻസിപ്പാലിറ്റി'),
    'Kavala': ('Angadi', 'അങ്ങാടി'),
    'Kindu Vessel': ('Kindi', 'കിണ്ടി'),
    'Tharavad': ('Nalukettu', 'നാലുകെട്ട്'),
    'Library': ('Laboratory', 'ലബോറട്ടറി'),
    'Taxi': ('Auto Rickshaw', 'ഓട്ടോ റിക്ഷ'),
    'College Canteen': ('Hostel Mess', 'ഹോസ്റ്റൽ മെസ്സ്'),
    'Urveshi': ('Shobana', 'ശോഭന'),
    'Arippa': ('Filter', 'ഫിൽറ്റർ'),
    'Asif Ali': ('Fahadh Faasil', 'ഫഹദ് ഫാസിൽ'),
    'Anganwadi': ('Nursery', 'നഴ്സറി'),
    'Tempo Traveller': ('Mini Bus', 'മിനി ബസ്'),
    'Arts Day': ('Sports Day', 'സ്പോർട്സ് ഡേ'),
    'Kavukal': ('Ambalam', 'അമ്പലം'),
    'Youth Festival': ('Kalolsavam', 'കലോത്സവം'),
    'Mukesh': ('Sreenivasan', 'ശ്രീനിവാസൻ'),
    'Progress Report': ('Mark List', 'മാർക്ക് ലിസ്റ്റ്'),
    'K. S. Chithra': ('Sujatha', 'സുജാത'),
    'Chappathi Kallu': ('Ammikkallu', 'അമ്മിക്കല്ല്'),
    'Basil Joseph': ('Vineeth Sreenivasan', 'വിനീത് ശ്രീനിവാസൻ'),
    'KSRTC': ('Private Bus', 'പ്രൈവറ്റ് ബസ്'),
    'Laboratory': ('Library', 'ലൈബ്രറി'),
    'Chirava': ('Arival', 'അരിവാൾ'),
    'Tractor': ('JCB', 'ജെസിബി'),
    'Mundu': ('Lungi', 'ലുങ്കി'),
    'Hostel': ('Lodge', 'ലോഡ്ജ്'),
    'Cheenachatti': ('Dosa Kallu', 'ദോശ കല്ല്'),
    'Sanju Samson': ('Sachin Tendulkar', 'സച്ചിൻ ടെണ്ടുൽക്കർ'),
    'Bharani': ('Kalam', 'കലം'),
    'Alumni Meet': ('Farewell', 'ഫെയർവെൽ'),
    'Mahindra Jeep': ('Bolero', 'ബൊലേറോ'),
    'Tovino Thomas': ('Asif Ali', 'ആസിഫ് അലി'),
    'Pepe Antony': ('Shane Nigam', 'ഷെയ്ൻ നിഗം'),
    'Bevco': ('Kallu Shappu', 'കള്ള് ഷാപ്പ്'),
    'Torrus Truck': ('Tipper', 'ടിപ്പർ'),
    'Aanavandi': ('Low Floor Bus', 'ലോ ഫ്ലോർ ബസ്'),
    'Cycle': ('Scooter', 'സ്കൂട്ടർ'),
    'School Bus': ('Ambulance', 'ആംബുലൻസ്'),
    'NCC': ('NSS', 'എൻഎസ്എസ്'),
    'Bench and Desk': ('Blackboard', 'ബ്ലാക്ക് ബോർഡ്'),
    'Assignment': ('Record Book', 'റെക്കോർഡ് ബുക്ക്'),
    'Auto Rickshaw': ('Taxi', 'ടാക്സി'),
    'Record Book': ('Assignment', 'അസൈൻമെന്റ്'),
    'Slate and Pencil': ('Chalk', 'ചോക്ക്'),
    'Jayaram': ('Dileep', 'ദിലീപ്'),
    'Hartal': ('Bandh', 'ബന്ദ്'),
    'Puttu Kutti': ('Idiyappam Maker', 'ഇടിയപ്പം മേക്കർ'),
    'Chitty': ('Bank Loan', 'ബാങ്ക് ലോൺ'),
    'Bell': ('Siren', 'സൈറൺ'),
    'Kalolsavam': ('Arts Day', 'ആർട്സ് ഡേ'),
    'Shobana': ('Manju Warrier', 'മഞ്ജു വാര്യർ'),
    'Mazha': ('Veyil', 'വെയിൽ'),
    'Tourist Bus': ('KSRTC', 'കെഎസ്ആർടിസി'),
    'Kettuvallam': ('Houseboat', 'ഹൗസ്ബോട്ട്'),
    'Jeep': ('Gypsy', 'ജിപ്സി'),
    'Fire Engine': ('Ambulance', 'ആംബുലൻസ്'),
    'Tuition Class': ('School', 'സ്കൂൾ'),
    'Vallam': ('Thoni', 'തോണി'),
    'Kulam': ('Puzha', 'പുഴ'),
    'Manju Warrier': ('Kavya Madhavan', 'കാവ്യാ മാധവൻ'),
    'RX 100': ('Bullet', 'ബുള്ളറ്റ്'),
    'Fahadh Faasil': ('Dulquer Salmaan', 'ദുൽഖർ സൽമാൻ'),
    'Dulquer Salmaan': ('Nivin Pauly', 'നിവിൻ പോളി'),
    'Ambalam': ('Palli', 'പള്ളി'),
    'Suraj Venjaramoodu': ('Salim Kumar', 'സലിം കുമാർ'),
    'Kudumbashree': ('Ayalkoottam', 'അയൽക്കൂട്ടം'),
    'Vineeth Sreenivasan': ('Basil Joseph', 'ബേസിൽ ജോസഫ്'),
    'Vidyabhyasa Loan': ('Home Loan', 'ഹോം ലോൺ'),
    'Mahatma Gandhi NREGA': ('Kudumbashree', 'കുടുംബശ്രീ'),
    'Paya': ('Metha', 'മെത്ത'),
    'Anaswara Rajan': ('Mamitha Baiju', 'മമിത ബൈജു'),
    'Water Authority': ('KSEB', 'കെഎസ്ഇബി'),
    'Uniform': ('ID Card', 'ഐഡി കാർഡ്'),
    'Onam Celebration': ('Christmas Celebration', 'ക്രിസ്മസ് ആഘോഷം'),
    'Geometry Box': ('Pencil Pouch', 'പെൻസിൽ പൗച്ച്'),
    'Mini Bus': ('Tempo Traveller', 'ടെമ്പോ ട്രാവലർ'),
    'School Bag': ('Lunch Box', 'ലഞ്ച് ബോക്സ്'),
    'Kunchacko Boban': ('Jayasurya', 'ജയസൂര്യ'),
    'IV (Industrial Visit)': ('Tour Trip', 'ടൂർ ട്രിപ്പ്'),
    'Autorickshaw': ('Jeep', 'ജീപ്പ്'),
    'Jik Jik Train': ('Toy Train', 'ടോയ് ട്രെയിൻ'),
    'Principal': ('Headmaster', 'ഹെഡ്മാസ്റ്റർ'),
    'Kalyani Priyadarshan': ('Nazriya Nazim', 'നസ്രിയ നസീം'),
    'Tharavadu': ('Nalukettu', 'നാലുകെട്ട്'),
    'Scooter': ('Bike', 'ബൈക്ക്'),
    'Choottu': ('Pantham', 'പന്തം'),
    'Lottery Ticket': ('Scratch and Win', 'സ്ക്രാച്ച് ആൻഡ് വിൻ'),
    'Chundan Vallam': ('Kettuvallam', 'കെട്ടുവള്ളം'),
    'Peti Auto': ('Goods Auto', 'ഗുഡ്സ് ഓട്ടോ'),
    'Pickup': ('Lorry', 'ലോറി'),
    'Jankar': ('Ferry', 'ഫെറി'),
    'Low Floor Bus': ('Aanavandi', 'ആനവണ്ടി'),
    'Rank List': ('Waiting List', 'വെയ്റ്റിംഗ് ലിസ്റ്റ്'),
    'NSS': ('NCC', 'എൻസിസി'),
    'Study Leave': ('Onam Vacation', 'ഓണാവധി'),
    'Innocent': ('Jagathy', 'ജഗതി'),
    'Ration Kada': ('Maveli Store', 'മാവേലി സ്റ്റോർ'),
    'Suresh Gopi': ('Biju Menon', 'ബിജു മേനോൻ'),
    'Class Leader': ('Monitor', 'മോണിറ്റർ'),
    'Annual Day': ('Sports Day', 'സ്പോർട്സ് ഡേ'),
    'Paathram': ('Kindi', 'കിണ്ടി'),
    'Tour Trip': ('IV', 'ഐവി'),
    'Private Bus': ('KSRTC', 'കെഎസ്ആർടിസി'),
    'Excavator': ('JCB', 'ജെസിബി'),
    'PT Period': ('Library Period', 'ലൈബ്രറി പീരീഡ്'),
    'Ferry': ('Jankar', 'ജങ്കാർ'),
    'Jagathy Sreekumar': ('Innocent', 'ഇന്നസെന്റ്'),
    'Ambulance': ('Fire Engine', 'ഫയർ എഞ്ചിൻ'),
    'Kalam': ('Bharani', 'ഭരണി'),
    'Kettle': ('Thermos', 'തെർമോസ്'),
    'Naadan Pattu': ('Kavitha', 'കവിത'),
    'Kasavu Saree': ('Pattu Saree', 'പട്ടു സാരി'),
    'Houseboat': ('Shikara', 'ശിക്കാര'),
    'Palli': ('Ambalam', 'അമ്പലം'),
    'Supplyco': ('Milma', 'മിൽമ'),
    'Nazriya Nazim': ('Parvathy Thiruvothu', 'പാർവതി തിരുവോത്ത്'),
    'Exam Hall': ('Classroom', 'ക്ലാസ്സ് മുറി'),
    'Rubber Thottam': ('Tea Estate', 'ടീ എസ്റ്റേറ്റ്'),
    'Kattil': ('Metha', 'മെത്ത'),
    'Prithviraj': ('Indrajith', 'ഇന്ദ്രജിത്ത്'),
    'K. J. Yesudas': ('M. G. Sreekumar', 'എം ജി ശ്രീകുമാർ'),
    'Jayasurya': ('Kunchacko Boban', 'കുഞ്ചാക്കോ ബോബൻ'),
    'Shashi Tharoor': ('Pinarayi Vijayan', 'പിണറായി വിജയൻ'),
    'Kallu Shappu': ('Bevco', 'ബെവ്കോ'),
    'Akshaya Centre': ('Panchayath', 'പഞ്ചായത്ത്'),
    'PTA Meeting': ('Open House', 'ഓപ്പൺ ഹൗസ്'),
    'Dileep': ('Jayaram', 'ജയറാം'),
    'Water Metro': ('Kochi Metro', 'കൊച്ചി മെട്രോ'),
    'Puzha': ('Kulam', 'കുളം'),
    'Tea Estate': ('Rubber Thottam', 'റബ്ബർ തോട്ടം'),
    'Vaal Kannadi': ('Nilavilakku', 'നിലവിളക്ക്'),
    'Madaal': ('Thengu', 'തെങ്ങ്'),
    'Farewell': ('Fresher Party', 'ഫ്രെഷേഴ്സ് പാർട്ടി'),
    'Oonjal': ('Sliding Board', 'സ്ലൈഡിംഗ് ബോർഡ്'),
    'Kuttanadan Padanilam': ('Munnar', 'മൂന്നാർ'),
    'Chaya Kada': ('Thattukada', 'തട്ടുകട'),
    'College Union': ('SFI', 'എസ്എഫ്ഐ'),
    'Alavu Para': ('Idangazhi', 'ഇടനാഴി')
}

with open('scratch/bad_categories_fixed.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

bad_keywords = ['fake', 'type', 'variant', 'alternative', 'clone']

for category in data:
    for word_obj in category.get('words', []):
        civ = word_obj.get('civWord', '')
        for imp in word_obj.get('imposters', []):
            imp_word = imp.get('word', '')
            is_bad = False
            for k in bad_keywords:
                if k in imp_word.lower():
                    is_bad = True
            if imp_word.lower() == 'fake ' + civ.lower():
                is_bad = True
            
            if is_bad:
                if civ in replacements:
                    new_w, new_m = replacements[civ]
                    imp['word'] = new_w
                    imp['wordMal'] = new_m
                    imp['relationEN'] = 'Both ' + civ + ' and ' + new_w + ' are deeply related concepts often confused together.'
                    imp['relationML'] = 'രണ്ടും സമാനമായ ആശയങ്ങളായതിനാൽ ' + word_obj.get('civWordMal', '') + ' ഉം ' + new_m + ' ഉം ആളുകൾക്ക് തെറ്റിദ്ധരിക്കാൻ സാധ്യതയുണ്ട്.'

with open('scratch/bad_categories_perfect.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('Saved successfully')
