import json

relations_data = [
    (["Jagathy Sreekumar", "Innocent"], "Both Jagathy Sreekumar and Innocent are legendary Malayalam comedy actors who ruled the industry during the 80s and 90s.", "ജഗതി ശ്രീകുമാറും ഇന്നസെൻ്റും 80-കളിലും 90-കളിലും മലയാള സിനിമ ഭരിച്ച ഇതിഹാസ ഹാസ്യ നടന്മാരാണ്."),
    (["Shobana", "Manju Warrier"], "Both Shobana and Manju Warrier are highly acclaimed leading actresses in Malayalam cinema known for their powerful female-centric roles.", "ശോഭനയും മഞ്ജു വാര്യരും മലയാള സിനിമയിലെ ശക്തമായ സ്ത്രീപക്ഷ കഥാപാത്രങ്ങളിലൂടെ ശ്രദ്ധേയരായ മുൻനിര നടിമാരാണ്."),
    (["Kallu Shappu", "Bevco"], "Both Kallu Shappu and Bevco are popular establishments in Kerala where alcoholic beverages are legally sold to the public.", "കള്ളുഷാപ്പും ബെവ്കോയും കേരളത്തിൽ നിയമപരമായി മദ്യം വിൽക്കുന്ന ജനപ്രിയ സ്ഥാപനങ്ങളാണ്."),
    (["Dileep", "Jayaram"], "Both Dileep and Jayaram are popular Malayalam leading men who built their careers primarily through family-oriented comedy movies.", "ദിലീപും ജയറാമും കുടുംബ പ്രേക്ഷകരെ ലക്ഷ്യമിട്ടുള്ള ഹാസ്യ ചിത്രങ്ങളിലൂടെ കരിയർ പടുത്തുയർത്തിയ ജനപ്രിയ മലയാള നടന്മാരാണ്."),
    (["Ration Kada", "Maveli Store"], "Both Ration Kada and Maveli Store are government-subsidized retail shops in Kerala that provide essential groceries at lower prices.", "റേഷൻ കടയും മാവേലി സ്റ്റോറും കേരളത്തിൽ കുറഞ്ഞ വിലയ്ക്ക് അവശ്യ സാധനങ്ങൾ നൽകുന്ന സർക്കാർ സബ്‌സിഡിയുള്ള കടകളാണ്."),
    (["Shashi Tharoor", "Pinarayi Vijayan"], "Both Shashi Tharoor and Pinarayi Vijayan are highly prominent political figures representing Kerala on the national and state level.", "ശശി തരൂരും പിണറായി വിജയനും ദേശീയ, സംസ്ഥാന തലങ്ങളിൽ കേരളത്തെ പ്രതിനിധീകരിക്കുന്ന പ്രമുഖ രാഷ്ട്രീയ നേതാക്കളാണ്."),
    (["Kuttanadan Padanilam", "Munnar"], "Both Kuttanadan Padanilam and Munnar are iconic scenic landscapes in Kerala, representing its distinct backwaters and hill stations.", "കുട്ടനാടൻ പാടശേഖരവും മൂന്നാറും കേരളത്തിൻ്റെ കായൽ സൗന്ദര്യത്തെയും മലയോരങ്ങളെയും പ്രതിനിധീകരിക്കുന്ന പ്രശസ്തമായ പ്രകൃതിദൃശ്യങ്ങളാണ്."),
    (["Mazha", "Veyil"], "Both Mazha and Veyil are basic weather phenomena that dictate the everyday tropical climate and agricultural cycle of Kerala.", "മഴയും വെയിലും കേരളത്തിൻ്റെ ദൈനംദിന ഉഷ്ണമേഖലാ കാലാവസ്ഥയെയും കാർഷിക चक्रത്തെയും നിയന്ത്രിക്കുന്ന അടിസ്ഥാന കാലാവസ്ഥാ പ്രതിഭാസങ്ങളാണ്."),
    (["Vineeth Sreenivasan", "Basil Joseph"], "Both Vineeth Sreenivasan and Basil Joseph are contemporary Malayalam directors who also frequently act in feel-good emotional comedies.", "വിനീത് ശ്രീനിവാസനും ബേസിൽ ജോസഫും ഫീൽ ഗുഡ് കോമഡി ചിത്രങ്ങൾ സംവിധാനം ചെയ്യുകയും അഭിനയിക്കുകയും ചെയ്യുന്ന സമകാലിക മലയാള സിനിമാപ്രവർത്തകരാണ്."),
    (["Akshaya Centre", "Panchayath"], "Both Akshaya Centre and Panchayath are localized public service institutions in Kerala where citizens go for administrative paperwork and certificates.", "അക്ഷയ കേന്ദ്രവും പഞ്ചായത്തും കേരളത്തിലെ പൗരന്മാർ ഭരണപരമായ ആവശ്യങ്ങൾക്കും സർട്ടിഫിക്കറ്റുകൾക്കും ആശ്രയിക്കുന്ന പ്രാദേശിക പൊതുസേവന സ്ഥാപനങ്ങളാണ്."),
    (["Prithviraj", "Indrajith"], "Both Prithviraj and Indrajith are brothers and versatile actors in Malayalam cinema hailing from a prominent film family.", "പൃഥ്വിരാജും ഇന്ദ്രജിത്തും പ്രശസ്തമായ സിനിമാ കുടുംബത്തിൽ നിന്നുള്ള സഹോദരങ്ങളും മലയാള സിനിമയിലെ പ്രതിഭാധനരായ നടന്മാരുമാണ്."),
    (["Supplyco", "Milma"], "Both Supplyco and Milma are state-run cooperative enterprises in Kerala that distribute daily consumer goods and dairy products.", "സപ്ലൈകോയും മിൽമയും കേരളത്തിൽ നിത്യോപയോഗ സാധനങ്ങളും പാലുൽപ്പന്നങ്ങളും വിതരണം ചെയ്യുന്ന സർക്കാർ സഹകരണ സംരംഭങ്ങളാണ്."),
    (["Vidyabhyasa Loan", "Home Loan"], "Both Vidyabhyasa Loan and Home Loan are common long-term financial borrowings that middle-class families in Kerala rely on to secure their future.", "വിദ്യാഭ്യാസ ലോണും ഭവന വായ്പയും കേരളത്തിലെ ഇടത്തരം കുടുംബങ്ങൾ അവരുടെ ഭാവി സുരക്ഷിതമാക്കാൻ ആശ്രയിക്കുന്ന സാധാരണ ദീർഘകാല വായ്പകളാണ്."),
    (["Dulquer Salmaan", "Nivin Pauly"], "Both Dulquer Salmaan and Nivin Pauly are leading youth icons of Malayalam cinema who rose to stardom during the 2010s new wave.", "ദുൽഖർ സൽമാനും നിവിൻ പോളിയും 2010-കളിലെ പുതിയ തരംഗത്തിലൂടെ താരപദവിയിലേക്ക് ഉയർന്ന മലയാള സിനിമയിലെ യുവതാരങ്ങളാണ്."),
    (["Chaya Kada", "Thattukada"], "Both Chaya Kada and Thattukada are quintessential local street food stalls in Kerala where people gather for hot tea, snacks, and conversations.", "ചായക്കടയും തട്ടുകടയും ആളുകൾ ചൂടുചായക്കും പലഹാരങ്ങൾക്കും സംഭാഷണങ്ങൾക്കുമായി ഒത്തുകൂടുന്ന കേരളത്തിലെ തനത് നാടൻ കടകളാണ്."),
    (["Suresh Gopi", "Biju Menon"], "Both Suresh Gopi and Biju Menon are tall, deep-voiced Malayalam actors known for their iconic police roles and strong screen presence.", "സുരേഷ് ഗോപിയും ബിജു മേനോനും മികച്ച പോലീസ് കഥാപാത്രങ്ങളിലൂടെയും ശബ്ദഗാംഭീര്യത്തിലൂടെയും ശ്രദ്ധേയരായ മലയാള നടന്മാരാണ്."),
    (["Urveshi", "Shobana"], "Both Urvashi and Shobana are legendary Malayalam actresses who dominated the silver screen in the 1990s with their immense acting and dancing talents.", "ഉർവ്വശിയും ശോഭനയും 1990-കളിൽ തങ്ങളുടെ അതുല്യമായ അഭിനയ-നൃത്ത പാടവം കൊണ്ട് വെള്ളിത്തിര അടക്കിഭരിച്ച പ്രഗത്ഭരായ മലയാള നടിമാരാണ്."),
    (["Pepe Antony", "Shane Nigam"], "Both Antony Varghese (Pepe) and Shane Nigam are new-generation Malayalam actors known for their raw, realistic portrayals in gritty dramas.", "ആൻ്റണി വർഗീസും ഷെയിൻ നിഗമും റിയലിസ്റ്റിക് സിനിമകളിലെ തങ്ങളുടെ സ്വാഭാവിക അഭിനയം കൊണ്ട് ശ്രദ്ധേയരായ പുതിയ തലമുറയിലെ മലയാള നടന്മാരാണ്."),
    (["Aishwarya Lekshmi", "Nazriya Nazim"], "Both Aishwarya Lekshmi and Nazriya Nazim are popular contemporary Malayalam actresses who gained massive fan followings through romantic blockbuster movies.", "ഐശ്വര്യ ലക്ഷ്മിയും നസ്രിയ നസീമും റൊമാൻ്റിക് ഹിറ്റ് ചിത്രങ്ങളിലൂടെ വലിയ ആരാധക പിന്തുണ നേടിയ ജനപ്രിയ സമകാലിക മലയാള നടിമാരാണ്."),
    (["Salim Kumar", "Suraj Venjaramoodu"], "Both Salim Kumar and Suraj Venjaramoodu are National Award-winning Malayalam actors who started out as slapstick comedians before transitioning to serious character roles.", "സലിം കുമാറും സുരാജ് വെഞ്ഞാറമൂടും ഹാസ്യ വേഷങ്ങളിലൂടെ സിനിമയിലെത്തി പിന്നീട് സ്വഭാവ നടന്മാരായി മാറി ദേശീയ പുരസ്കാരം നേടിയ മലയാള നടന്മാരാണ്."),
    (["KSEB", "Water Authority"], "Both KSEB and Water Authority are the primary state-run utility boards responsible for delivering essential resources to households across Kerala.", "കെ.എസ്.ഇ.ബിയും വാട്ടർ അതോറിറ്റിയും കേരളത്തിലുടനീളമുള്ള വീടുകളിൽ അവശ്യ സേവനങ്ങൾ എത്തിക്കാൻ ചുമതലപ്പെട്ട പ്രധാന സർക്കാർ ബോർഡുകളാണ്."),
    (["Anaswara Rajan", "Mamitha Baiju"], "Both Anaswara Rajan and Mamitha Baiju are highly successful Gen-Z actresses in Malayalam cinema who starred in recent coming-of-age superhits.", "അനശ്വര രാജനും മമിത ബൈജുവും അടുത്തിടെ ഇറങ്ങിയ സൂപ്പർഹിറ്റ് യുവത്വ സിനിമകളിലൂടെ ശ്രദ്ധേയരായ മലയാള സിനിമയിലെ പുതിയ തലമുറ നടിമാരാണ്."),
    (["Mammootty", "Mohanlal"], "Both Mammootty and Mohanlal are the undisputed twin pillars and superstars of the Malayalam film industry for over four decades.", "മമ്മൂട്ടിയും മോഹൻലാലും നാല് പതിറ്റാണ്ടിലേറെയായി മലയാള സിനിമാ വ്യവസായത്തിൻ്റെ അനിഷേധ്യരായ രണ്ട് നെടുംതൂണുകളും സൂപ്പർസ്റ്റാറുകളുമാണ്."),
    (["Palli", "Ambalam"], "Both Palli and Ambalam are traditional places of worship in Kerala serving as spiritual and cultural gathering centers for local communities.", "പള്ളിയും അമ്പലവും പ്രാദേശിക സമൂഹങ്ങളുടെ ആത്മീയവും സാംസ്കാരികവുമായ ഒത്തുചേരൽ കേന്ദ്രങ്ങളായി വർത്തിക്കുന്ന കേരളത്തിലെ പരമ്പരാഗത ആരാധനാലയങ്ങളാണ്."),
    (["Panchayath", "Municipality"], "Both Panchayath and Municipality are local self-government bodies in Kerala responsible for grassroots administration and civic infrastructure development.", "പഞ്ചായത്തും മുൻസിപ്പാലിറ്റിയും അടിസ്ഥാന ഭരണത്തിനും അടിസ്ഥാന സൗകര്യ വികസനത്തിനും ചുമതലപ്പെട്ട കേരളത്തിലെ തദ്ദേശ സ്വയംഭരണ സ്ഥാപനങ്ങളാണ്."),
    (["Kavukal", "Ambalam"], "Both Kavukal and Ambalam are sacred spaces in Kerala's Hindu tradition, representing ancient ecological conservation and formal temple worship.", "കാവുകളും അമ്പലങ്ങളും കേരളത്തിലെ ഹൈന്ദവ പാരമ്പര്യത്തിലെ പുണ്യസ്ഥലങ്ങളാണ്, ഇവ യഥാക്രമം പ്രകൃതി സംരക്ഷണത്തെയും ക്ഷേത്രാരാധനയെയും പ്രതിനിധീകരിക്കുന്നു."),
    (["Innocent", "Jagathy"], "Both Innocent and Jagathy are unparalleled veterans of Malayalam comedy whose unique dialogue delivery styles shaped the industry's humor.", "ഇന്നസെൻ്റും ജഗതിയും തങ്ങളുടെ സവിശേഷമായ സംഭാഷണ ശൈലികൊണ്ട് സിനിമാ ഹാസ്യത്തെ മാറ്റിയെഴുതിയ മലയാള സിനിമയിലെ അതുല്യ പ്രതിഭകളാണ്."),
    (["Kudumbashree", "Ayalkoottam"], "Both Kudumbashree and Ayalkoottam are grassroots women's empowerment networks in Kerala focusing on micro-finance and community development.", "കുടുംബശ്രീയും അയൽക്കൂട്ടവും മൈക്രോ ഫിനാൻസിലും സാമൂഹിക വികസനത്തിലും ശ്രദ്ധ കേന്ദ്രീകരിക്കുന്ന കേരളത്തിലെ താഴെത്തട്ടിലുള്ള സ്ത്രീ ശാക്തീകരണ ശൃംഖലകളാണ്."),
    (["Tea Estate", "Rubber Thottam"], "Both Tea Estate and Rubber Thottam are vast commercial cash crop plantations that dominate the hilly agricultural landscapes of Kerala.", "തേയിലത്തോട്ടവും റബ്ബർ തോട്ടവും കേരളത്തിൻ്റെ മലയോര കാർഷിക മേഖലകളിൽ വ്യാപകമായി കാണപ്പെടുന്ന പ്രധാന നാണ്യവിള തോട്ടങ്ങളാണ്."),
    (["Fahadh Faasil", "Dulquer Salmaan"], "Both Fahadh Faasil and Dulquer Salmaan are widely celebrated contemporary stars from film families who brought a modern sensibility to Malayalam cinema.", "ഫഹദ് ഫാസിലും ദുൽഖർ സൽമാനും സിനിമാ പശ്ചാത്തലത്തിൽ നിന്നെത്തി മലയാള സിനിമയിൽ ആധുനിക മാറ്റങ്ങൾ കൊണ്ടുവന്ന പ്രശസ്തരായ സമകാലിക താരങ്ങളാണ്."),
    (["Current Bill", "Water Bill"], "Both Current Bill and Water Bill are recurring monthly or bi-monthly utility expenses that households in Kerala must regularly pay to the state government.", "കറൻ്റ് ബില്ലും വാട്ടർ ബില്ലും കേരളത്തിലെ വീടുകളിൽ കൃത്യമായി സർക്കാർ ഓഫീസുകളിൽ അടയ്ക്കേണ്ട പ്രധാന പ്രതിമാസ അല്ലെങ്കിൽ ദ്വൈമാസ ചെലവുകളാണ്."),
    (["Kunchacko Boban", "Jayasurya"], "Both Kunchacko Boban and Jayasurya are well-established leading actors in Malayalam cinema who evolved from romantic boys to critically acclaimed character artists.", "കുഞ്ചാക്കോ ബോബനും ജയസൂര്യയും പ്രണയ നായകന്മാരായി തുടങ്ങി പിന്നീട് മികച്ച സ്വഭാവ നടന്മാരായി മാറിയ മലയാള സിനിമയിലെ പ്രശസ്തരായ നായകന്മാരാണ്."),
    (["Kavala", "Angadi"], "Both Kavala and Angadi refer to bustling local junctions and market centers in Kerala towns where people shop and gather.", "കവലയും അങ്ങാടിയും ആളുകൾ സാധനങ്ങൾ വാങ്ങാനും ഒത്തുകൂടാനുമായി എത്തുന്ന കേരളത്തിലെ തിരക്കേറിയ പ്രാദേശിക ജംഗ്ഷനുകളെയും മാർക്കറ്റുകളെയും സൂചിപ്പിക്കുന്നു."),
    (["K. J. Yesudas", "M. G. Sreekumar"], "Both K. J. Yesudas and M. G. Sreekumar are legendary Malayalam playback singers whose iconic voices defined generations of film music in Kerala.", "കെ.ജെ. യേശുദാസും എം.ജി. ശ്രീകുമാറും തങ്ങളുടെ ഇതിഹാസ ശബ്ദങ്ങളിലൂടെ കേരളത്തിലെ പല തലമുറകളുടെ സിനിമാഗാനങ്ങളെ അടയാളപ്പെടുത്തിയ പ്രശസ്ത പിന്നണി ഗായകരാണ്."),
    (["Thengu", "Kamuku"], "Both Thengu (Coconut) and Kamuku (Arecanut) are essential, tall unbranched palm trees extensively cultivated across Kerala for their valuable nuts.", "തേങ്ങും കവുങ്ങും കേരളത്തിലുടനീളം കാർഷിക ആവശ്യങ്ങൾക്കായി വ്യാപകമായി കൃഷി ചെയ്യുന്ന ശാഖകളില്ലാത്ത പ്രധാനപ്പെട്ട നാണ്യവിള മരങ്ങളാണ്."),
    (["Sanju Samson", "Sachin Tendulkar"], "Both Sanju Samson and Sachin Tendulkar are massively popular cricket players who command intense, loyal fanbases among cricket enthusiasts in Kerala.", "സഞ്ജു സാംസണും സച്ചിൻ ടെണ്ടുൽക്കറും കേരളത്തിലെ ക്രിക്കറ്റ് പ്രേമികൾക്കിടയിൽ വലിയ ആരാധക പിന്തുണയുള്ള ജനപ്രിയ ക്രിക്കറ്റ് താരങ്ങളാണ്."),
    (["Puzha", "Kulam"], "Both Puzha and Kulam are vital freshwater bodies in Kerala traditionally used by locals for bathing, washing, and agricultural irrigation.", "പുഴയും കുളവും പരമ്പരാഗതമായി ആളുകൾ കുളിക്കാനും അലക്കാനും കാർഷിക ആവശ്യങ്ങൾക്കും ഉപയോഗിക്കുന്ന കേരളത്തിലെ പ്രധാന ശുദ്ധജല സ്രോതസ്സുകളാണ്."),
    (["Mukesh", "Sreenivasan"], "Both Mukesh and Sreenivasan are veteran Malayalam actors renowned for their exceptional comedic timing and satirical middle-class relatable characters.", "മുകേഷും ശ്രീനിവാസനും തങ്ങളുടെ മികച്ച ഹാസ്യ സമയവും ഇടത്തരക്കാരുടെ ജീവിതം പ്രതിഫലിപ്പിക്കുന്ന കഥാപാത്രങ്ങളും കൊണ്ട് പ്രശസ്തരായ മുതിർന്ന മലയാള നടന്മാരാണ്."),
    (["Kalyani Priyadarshan", "Nazriya Nazim"], "Both Kalyani Priyadarshan and Nazriya Nazim are bubbly, energetic Malayalam actresses who are widely loved for their cute and expressive on-screen personas.", "കല്യാണി പ്രിയദർശനും നസ്രിയ നസീമും തങ്ങളുടെ ഊർജ്ജസ്വലവും ക്യൂട്ടുമായ സ്ക്രീൻ പ്രസൻസ് കൊണ്ട് പ്രേക്ഷകരുടെ പ്രിയങ്കരികളായ മലയാള നടിമാരാണ്."),
    (["Hartal", "Bandh"], "Both Hartal and Bandh are forms of political strikes and mass protests in Kerala that result in the widespread shutdown of shops and transport.", "ഹർത്താലും ബന്ദും കേരളത്തിൽ കടകമ്പോളങ്ങളും ഗതാഗതവും സ്തംഭിപ്പിക്കുന്ന രാഷ്ട്രീയ സമരങ്ങളുടെയും പ്രതിഷേധങ്ങളുടെയും രൂപങ്ങളാണ്."),
    (["Naadan Pattu", "Kavitha"], "Both Naadan Pattu and Kavitha are expressive forms of Malayalam literature and oral tradition used to convey stories, emotions, and cultural heritage.", "നാടൻ പാട്ടും കവിതയും കഥകളും വികാരങ്ങളും സാംസ്കാരിക പൈതൃകവും പങ്കുവെക്കാൻ ഉപയോഗിക്കുന്ന മലയാള സാഹിത്യത്തിൻ്റെയും വാമൊഴി പാരമ്പര്യത്തിൻ്റെയും രൂപങ്ങളാണ്."),
    (["Soubin Shahir", "Sreenath Bhasi"], "Both Soubin Shahir and Sreenath Bhasi are trendy new-generation Malayalam actors famous for their quirky styling and natural, localized Kochi slang.", "സൗബിൻ ഷാഹിറും ശ്രീനാഥ് ഭാസിയും കൊച്ചി സ്ലാങ്ങിലൂടെയും വ്യത്യസ്തമായ അഭിനയ ശൈലിയിലൂടെയും ശ്രദ്ധേയരായ പുതിയ തലമുറയിലെ ട്രെൻഡി മലയാള നടന്മാരാണ്."),
    (["Manju Warrier", "Kavya Madhavan"], "Both Manju Warrier and Kavya Madhavan are beloved leading actresses of Malayalam cinema who delivered numerous blockbuster performances alongside major superstars.", "മഞ്ജു വാര്യരും കാവ്യ മാധവനും സൂപ്പർതാരങ്ങൾക്കൊപ്പം നിരവധി സൂപ്പർഹിറ്റ് ചിത്രങ്ങളിൽ മികച്ച പ്രകടനം കാഴ്ചവെച്ച പ്രിയപ്പെട്ട മുൻനിര മലയാള നടിമാരാണ്."),
    (["Tharavadu", "Nalukettu"], "Both Tharavadu and Nalukettu refer to the traditional ancestral homes of Kerala featuring distinct wooden architecture and central courtyards.", "തറവാടും നാലുകെട്ടും കേരളത്തിൻ്റെ തനത് വാസ്തുവിദ്യയും നടുമുറ്റവും ഉൾക്കൊള്ളുന്ന പരമ്പരാഗത തറവാട്ടു വീടുകളെ സൂചിപ്പിക്കുന്നു."),
    (["Tharavad", "Nalukettu"], "Both Tharavad and Nalukettu refer to the traditional ancestral homes of Kerala featuring distinct wooden architecture and central courtyards.", "തറവാടും നാലുകെട്ടും കേരളത്തിൻ്റെ തനത് വാസ്തുവിദ്യയും നടുമുറ്റവും ഉൾക്കൊള്ളുന്ന പരമ്പരാഗത തറവാട്ടു വീടുകളെ സൂചിപ്പിക്കുന്നു."),
    (["Chitty", "Bank Loan"], "Both Chitty and Bank Loan are standard financial instruments used by Kerala households to raise lump-sum money for major expenses like weddings or construction.", "ചിട്ടിയും ബാങ്ക് വായ്പയും കേരളത്തിലെ കുടുംബങ്ങൾ വിവാഹം, വീടുപണി തുടങ്ങിയ വലിയ ആവശ്യങ്ങൾക്കായി പണം കണ്ടെത്താൻ ഉപയോഗിക്കുന്ന പ്രധാന സാമ്പത്തിക മാർഗ്ഗങ്ങളാണ്."),
    (["Vayanasala", "Club"], "Both Vayanasala and Club are local community gathering spaces in Kerala villages where youth and elders meet for discussions, reading, and cultural activities.", "വായനശാലയും ക്ലബ്ബും ഗ്രാമങ്ങളിലെ യുവാക്കളും മുതിർന്നവരും വായനയ്ക്കും ചർച്ചകൾക്കും സാംസ്കാരിക പരിപാടികൾക്കുമായി ഒത്തുകൂടുന്ന പ്രാദേശിക കേന്ദ്രങ്ങളാണ്."),
    (["Parvathy Thiruvothu", "Manju Warrier"], "Both Parvathy Thiruvothu and Manju Warrier are critically acclaimed powerhouse actresses who lead female-centric movies in the Malayalam film industry.", "പാർവ്വതി തിരുവോത്തും മഞ്ജു വാര്യരും മലയാള സിനിമയിൽ സ്ത്രീപക്ഷ ചിത്രങ്ങളെ നയിക്കുന്ന മികച്ച അഭിനയശേഷിയുള്ള പ്രഗത്ഭ നടിമാരാണ്."),
    (["Asif Ali", "Fahadh Faasil"], "Both Asif Ali and Fahadh Faasil are prominent actors who debuted around the same time and played key roles in revitalizing new-age Malayalam cinema.", "ആസിഫ് അലിയും ഫഹദ് ഫാസിലും ഒരേ കാലഘട്ടത്തിൽ സിനിമയിലെത്തി മലയാള സിനിമയുടെ പുതിയ മാറ്റങ്ങളിൽ പ്രധാന പങ്കുവഹിച്ച പ്രമുഖ നടന്മാരാണ്."),
    (["KSRTC", "Private Bus"], "Both KSRTC and Private Bus are the lifelines of public road transportation connecting cities, towns, and remote villages across Kerala.", "കെ.എസ്.ആർ.ടി.സിയും പ്രൈവറ്റ് ബസും കേരളത്തിലെ നഗരങ്ങളെയും ഗ്രാമങ്ങളെയും ബന്ധിപ്പിക്കുന്ന പൊതുഗതാഗത സംവിധാനത്തിൻ്റെ ജീവനാഡികളാണ്."),
    (["Auto Rickshaw", "Taxi"], "Both Auto Rickshaw and Taxi are essential localized hired transport vehicles available at specific stands in every Kerala town for daily commuting.", "ഓട്ടോറിക്ഷയും ടാക്സിയും കേരളത്തിലെ എല്ലാ നഗരങ്ങളിലും യാത്രകൾക്കായി സ്റ്റാൻഡുകളിൽ നിന്ന് വാടകയ്ക്ക് ലഭിക്കുന്ന പ്രധാന ഗതാഗത വാഹനങ്ങളാണ്."),
    (["Kaithari", "Khadi"], "Both Kaithari and Khadi are traditional, eco-friendly handloom textile industries in Kerala celebrated for their authentic spun cotton garments.", "കൈത്തറിയും ഖാദിയും തനതായ പരുത്തി വസ്ത്രങ്ങൾക്ക് പേരുകേട്ട കേരളത്തിലെ പരമ്പരാഗതവും പരിസ്ഥിതി സൗഹൃദവുമായ നെയ്ത്ത് വ്യവസായങ്ങളാണ്."),
    (["K. S. Chithra", "Sujatha"], "Both K. S. Chithra and Sujatha are profoundly beloved female playback singers whose melodious voices defined Malayalam film music for decades.", "കെ.എസ്. ചിത്രയും സുജാതയും പതിറ്റാണ്ടുകളോളം മലയാള സിനിമാ സംഗീതത്തെ തങ്ങളുടെ മനോഹരമായ ശബ്ദം കൊണ്ട് സമ്പന്നമാക്കിയ പ്രിയപ്പെട്ട പിന്നണി ഗായികമാരാണ്."),
    (["Lottery Ticket", "Scratch and Win"], "Both Lottery Ticket and Scratch and Win are chance-based gambling systems authorized by the state government offering life-changing cash prizes.", "ലോട്ടറി ടിക്കറ്റും സ്ക്രാച്ച് ആൻഡ് വിന്നും കേരള സർക്കാർ അംഗീകൃതമായതും വലിയ ക്യാഷ് പ്രൈസുകൾ വാഗ്ദാനം ചെയ്യുന്നതുമായ ഭാഗ്യപരീക്ഷണ സംവിധാനങ്ങളാണ്."),
    (["Tovino Thomas", "Asif Ali"], "Both Tovino Thomas and Asif Ali are popular, charming leading men in contemporary Malayalam cinema known for taking up diverse and risky roles.", "ടൊവിനോ തോമസും ആസിഫ് അലിയും വ്യത്യസ്തവും വെല്ലുവിളി നിറഞ്ഞതുമായ കഥാപാത്രങ്ങളെ അവതരിപ്പിക്കുന്ന സമകാലിക മലയാള സിനിമയിലെ ജനപ്രിയ നായകന്മാരാണ്."),
    (["Anganwadi", "Nursery"], "Both Anganwadi and Nursery are early childhood education and care centers in Kerala focusing on the health, nutrition, and foundational learning of toddlers.", "അങ്കണവാടിയും നഴ്സറിയും കുട്ടികളുടെ ആരോഗ്യത്തിനും പോഷകാഹാരത്തിനും പ്രാഥമിക വിദ്യാഭ്യാസത്തിനും ഊന്നൽ നൽകുന്ന കേരളത്തിലെ ശിശുപരിപാലന കേന്ദ്രങ്ങളാണ്."),
    (["Mahatma Gandhi NREGA", "Kudumbashree"], "Both Mahatma Gandhi NREGA and Kudumbashree are government-backed rural empowerment schemes in Kerala that provide employment and financial independence to local women.", "തൊഴിലുറപ്പ് പദ്ധതിയും കുടുംബശ്രീയും പ്രാദേശിക സ്ത്രീകൾക്ക് തൊഴിലും സാമ്പത്തിക സ്വാശ്രയത്വവും നൽകുന്ന കേരളത്തിലെ സർക്കാർ പിന്തുണയുള്ള ഗ്രാമീണ ശാക്തീകരണ പദ്ധതികളാണ്."),
    (["Sreenivasan", "Jagathy Sreekumar"], "Both Sreenivasan and Jagathy Sreekumar are iconic pillars of classic Malayalam cinema, celebrated for their unmatched acting brilliance and sharp comedic wit.", "ശ്രീനിവാസനും ജഗതി ശ്രീകുമാറും തങ്ങളുടെ അതുല്യമായ അഭിനയ മികവിനാലും മൂർച്ചയുള്ള നർമ്മബോധത്താലും പ്രശസ്തരായ ക്ലാസിക് മലയാള സിനിമയിലെ ഇതിഹാസ താരങ്ങളാണ്.")
]

rel_dict = {}
for pair, en, ml in relations_data:
    rel_dict[frozenset(pair)] = {"en": en, "ml": ml}

def normalize(name):
    return name.strip()

input_path = 'c:/Users/HP/Desktop/Imposter/scratch/rel_chunk_2.json'
output_path = 'c:/Users/HP/Desktop/Imposter/scratch/rel_chunk_2_done.json'

with open(input_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

for p in data:
    for w in p.get('words', []):
        civ_word = normalize(w['civWord'])
        for i in w.get('imposters', []):
            imp_word = normalize(i['word'])
            key = frozenset([civ_word, imp_word])
            
            if key in rel_dict:
                i['relationEN'] = rel_dict[key]['en']
                i['relationML'] = rel_dict[key]['ml']
            else:
                # Fallback generator for anything missing
                i['relationEN'] = f"Both {civ_word} and {imp_word} are deeply related cultural or entertainment concepts in Kerala often confused by outsiders."
                i['relationML'] = f"{civ_word} ഉം {imp_word} ഉം കേരളത്തിലെ സാംസ്കാരിക അല്ലെങ്കിൽ വിനോദ മേഖലയുമായി ബന്ധപ്പെട്ട ആശയങ്ങളാണ്, ഇവ പലപ്പോഴും പുറത്തുനിന്നുള്ളവർക്ക് തെറ്റിദ്ധരിക്കപ്പെടാറുണ്ട്."

with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done writing relations.")
