if (typeof window === 'undefined') { global.window = {}; }
window.extraWords = {
  funny: [
    ['Adipoli', 'അടിപൊളി', 'Positive Vibe', 'നല്ല ഒരു അന്തരീക്ഷം'],
    ['Poli Scene', 'പൊളി സീൻ', 'Memorable Experience', 'ഓർമ്മയിൽ നിൽക്കുന്ന കാര്യം'],
    ['Sadhanam Kayyil Undo', 'സാധനം കയ്യിൽ ഉണ്ടോ', 'Coded Message', 'രഹസ്യമായ അന്വേഷണം'],
    ['Thenga', 'തേങ്ങ', 'Casual Exclamation', 'സാധാരണ പറയുന്ന വാക്ക്'],
    ['Chetta', 'ചേട്ടാ', 'Social Conversation Start', 'സംസാരം തുടങ്ങുമ്പോൾ'],
    ['Eda Mone', 'എടാ മോനെ', 'Informal Bonding', 'അടുപ്പമുള്ളവരോടുള്ള സമീപനം'],
    ['Kidilan', 'കിടിലൻ', 'High Rating', 'മികച്ച അഭിപ്രായം'],
    ['Chali', 'ചളി', 'Lighthearted Entertainment', 'നേരംപോക്ക് സംസാരം'],
    ['Koppu', 'കോപ്പ്', 'Emotional Outburst', 'മനസ്സിലെ അനിഷ്ടം'],
    ['Pani Paali', 'പണി പാളി', 'Unexpected Turn', 'വിചാരിക്കാത്ത മാറ്റം'],
    ['Ambada', 'അമ്പടാ', 'Friendly Teasing', 'തമാശയ്ക്കുള്ള പ്രശംസ'],
    ['Poda Pulle', 'പോടാ പുള്ളേ', 'Casual Rejection', 'തമാശയുള്ള തർക്കം'],
    ['Vattaano', 'വട്ടാണോ', 'Curiosity About Behavior', 'പെരുമാറ്റത്തെക്കുറിച്ചുള്ള സംശയം'],
    ['Athu Sheri', 'അത് ശരി', 'Skeptical Response', 'സംശയത്തോടെയുള്ള പ്രതികരണം'],
    ['Thallumala', 'തല്ലുമാല', 'Group Chaos', 'കൂട്ടമായ ബഹളം'],
    ['Chummadive', 'ചുമ്മാടിവേ', 'Playful Exclamation', 'തമാശയ്ക്കുള്ള പ്രതികരണം'],
    ['Oodayi', 'ഉടായിപ്പ്', 'Clever Shortcut', 'വളഞ്ഞ വഴിയുള്ള ഉപായം'],
    ['Jada', 'ജാഡ', 'Social Attitude', 'ആളുകളുടെ പെരുമാറ്റ രീതി'],
    ['Vera Level', 'വേറെ ലെവൽ', 'Extraordinary Situation', 'സാധാരണയിൽ കവിഞ്ഞ അവസ്ഥ'],
    ['Blunder', 'ബ്ലണ്ടർ', 'Awkward Moment', 'അബദ്ധം പിണയുന്ന സമയം'],
    ['Suhurthe', 'സുഹൃത്തേ', 'Polite Addressing', 'മാന്യമായ അഭിസംബോധന'],
    ['Kittu', 'കിട്ടു', 'Fulfillment Moment', 'ആഗ്രഹസാഫല്യം'],
    ['Scene Contra', 'സീൻ കോൺട്ര', 'Unexpected Complication', 'പ്രതീക്ഷിക്കാത്ത തടസ്സം'],
    ['Chamakku', 'ചമക്ക്', 'Showy Attitude', 'പ്രകടനപരത'],
    ['Shavapetti', 'ശവപ്പെട്ടി', 'Wooden Enclosure', 'തടിപ്പെട്ടി'],
    ['Pothu', 'പോത്ത്', 'Stubborn Nature', 'വാശിപിടിക്കുന്ന സ്വഭാവം'],
    ['Kuthikazhapp', 'കുതിക്കഴപ്പ്', 'Restless Energy', 'അടങ്ങിയിരിക്കാത്ത അവസ്ഥ'],
    ['Senti', 'സെന്റി', 'Emotional Reaction', 'വികാരഭരിതമായ പ്രതികരണം'],
    ['Kidu Vibe', 'കിടു വൈബ്', 'Top Tier Quality', 'ഉയർന്ന നിലവാരം'],
    ['Oomfi', 'ഊംഫി', 'Sudden Loss', 'പെട്ടെന്നുണ്ടായ നഷ്ടം'],
    ['Vatt', 'വട്ട്', 'Unusual Thinking', 'വ്യത്യസ്ത ചിന്താഗതി']
  ],
  movies: [
    ['Nadodikkattu', 'നാടോടിക്കാറ്റ്', 'Struggle and Survival', 'ജീവിത പോരാട്ടവും യാത്രയും'],
    ['Thenmavin Kombath', 'തേന്മാവിൻ കൊമ്പത്ത്', 'Village Romance', 'ഗ്രാമീണ പശ്ചാത്തലമുള്ള കഥ'],
    ['Kilukkam', 'കിലുക്കം', 'Humorous Journey', 'ചിരിയും യാത്രയും ചേർന്നത്'],
    ['Chithram', 'ചിത്രം', 'Emotional Relationship', 'ബന്ധങ്ങളുടെ ആഴം'],
    ['Bharatham', 'ഭരതം', 'Classical Art Background', 'കലാപരമായ പശ്ചാത്തലം'],
    ['Devasuram', 'ദേവാസുരം', 'Rivalry and Honor', 'അഭിമാനവും വാശിയും'],
    ['Ustad Hotel', 'ഉസ്താദ് ഹോട്ടൽ', 'Generations and Culture', 'തലമുറകളും പാരമ്പര്യവും'],
    ['Maheshinte Prathikaaram', 'മഹേഷിന്റെ പ്രതികാരം', 'Simple Town Life', 'സാധാരണക്കാരുടെ ജീവിതം'],
    ['Ayyappanum Koshiyum', 'അയ്യപ്പനും കോശിയും', 'Conflict of Personalities', 'വ്യക്തികൾ തമ്മിലുള്ള തർക്കം'],
    ['Lucifer', 'ലൂസിഫർ', 'Power and Strategy', 'അധികാരവും തന്ത്രങ്ങളും'],
    ['Thondimuthalum Driksakshiyum', 'തൊണ്ടിമുതലും ദൃക്സാക്ഷിയും', 'Human Nature', 'മനുഷ്യ സ്വഭാവങ്ങളുടെ സത്യം'],
    ['Action Hero Biju', 'ആക്ഷൻ ഹീറോ ബിജു', 'Real Life Incidents', 'യാഥാർത്ഥ്യത്തോട് അടുത്ത സംഭവങ്ങൾ'],
    ['Sudani from Nigeria', 'സുഡാനി ഫ്രം നൈജീരിയ', 'Compassion and Friendship', 'സ്നേഹവും കൂട്ടായ്മയും'],
    ['Traffic', 'ട്രാഫിക്', 'Time Sensitive Race', 'സമയത്തോടുള്ള മത്സരം'],
    ['Indian Rupee', 'ഇന്ത്യൻ റുപ്പി', 'Financial Ambitions', 'സാമ്പത്തിക ലക്ഷ്യങ്ങൾ'],
    ['Romancham', 'രോമാഞ്ചം', 'Bachelor Living Drama', 'കൂട്ടുകാരുടെ ഒന്നിച്ചുള്ള ജീവിതം'],
    ['Premalu', 'പ്രേമലു', 'Youth Relationship', 'പുതിയ തലമുറയുടെ ചിന്തകൾ'],
    ['Aavesham', 'ആവേശം', 'High Energy Encounter', 'ആവേശകരമായ കൂട്ടായ്മ'],
    ['Bramayugam', 'ഭ്രമയുഗം', 'Ancient Mystery', 'പഴയകാല നിഗൂഢത'],
    ['Manjummel Boys', 'മഞ്ഞുമ്മൽ ബോയ്സ്', 'Friendship Rescue', 'സുഹൃത്തുക്കളുടെ സ്നേഹം'],
    ['Godfather', 'ഗോഡ്ഫാദർ', 'Family Tradition', 'കുടുംബത്തിലെ കാരണവന്മാർ'],
    ['Malaikottai Vaaliban', 'മലൈക്കോട്ടൈ വാലിബൻ', 'Desert Folklore', 'നാടോടിക്കഥകൾ'],
    ['Minnal Murali', 'മിന്നൽ മുരളി', 'Tailor Shop Incident', 'തയ്യൽക്കടയിലെ സംഭവം'],
    ['Kishkindha Kaandam', 'കിഷ്കിന്ധാ കാണ്ഡം', 'Forest Reserve Inquiry', 'വനമേഖലയിലെ അന്വേഷണം'],
    ['Rorschach', 'റോഷാക്ക്', 'White Mask Mystery', 'മുഖംമൂടി രഹസ്യം'],
    ['Kattappanayile Rithwik Roshan', 'കട്ടപ്പനയിലെ ഹൃതിക് റോഷൻ', 'Local Casting Call', 'സിനിമ മോഹം'],
    ['Varathan', 'വരത്തൻ', 'Estate Intrusion', 'തോട്ടത്തിലെ അതിക്രമം'],
    ['Bheeshma Parvam', 'ഭീഷ്മ പർവ്വം', 'Mattancherry Trade', 'മട്ടാഞ്ചേരിയിലെ കച്ചവടം'],
    ['Memories', 'മെമ്മറീസ്', 'Investigative Thriller', 'രഹസ്യാന്വേഷണ കഥ'],
    ['Classmates', 'ക്ലാസ്മേറ്റ്സ്', 'Campus Nostalgia', 'കോളേജ് ഓർമ്മകൾ'],
    ['Spadikam', 'സ്ഫടികം', 'Rebellious Son', 'കുടുംബത്തിലെ തർക്കങ്ങൾ']
  ],
  characters: [
    ['Appukuttan', 'അപ്പുക്കുട്ടൻ', 'Humorous Companion', 'ചിരിപ്പിക്കുന്ന സുഹൃത്ത്'],
    ['Ramanan', 'രാമനൻ', 'Loyal Follower', 'വിശ്വസ്തനായ സഹായി'],
    ['Induchoodan', 'ഇന്ദുചൂഡൻ', 'Outspoken Leader', 'തന്റേടമുള്ള നായകൻ'],
    ['Kunjikoonan', 'കുഞ്ഞിക്കൂനൻ', 'Sympathetic Villager', 'സ്നേഹമുള്ള ഗ്രാമീണൻ'],
    ['Koshy Kurien', 'കോശി കുര്യൻ', 'Influential Challenger', 'സ്വാധീനമുള്ള എതിരാളി'],
    ['Ayyappan Nair', 'അയ്യപ്പൻ നായർ', 'Strict Authority Figure', 'നിയമം പാലിക്കുന്ന ഉദ്യോഗസ്ഥൻ'],
    ['Mahesh Bhavana', 'മഹേഷ് ഭാവന', 'Modest Town Photographer', 'സാധാരണക്കാരനായ ചെറുപ്പക്കാരൻ'],
    ['Biju Paulose', 'ബിജു പൗലോസ്', 'Dedicated Lawman', 'കടമ നിർവ്വഹിക്കുന്നവൻ'],
    ['Rameshan Nair', 'രമേശൻ നായർ', 'Passionate Enthusiast', 'വലിയ ഇഷ്ടങ്ങൾ സൂക്ഷിക്കുന്നവൻ'],
    ['Pachu', 'പച്ചു', 'Helpful Neighbor', 'എല്ലാവർക്കും വേണ്ടപ്പെട്ടവൻ'],
    ['Kunjiraman', 'കുഞ്ഞിരാമൻ', 'Prominent Local', 'ഗ്രാമത്തിലെ പ്രധാന വ്യക്തി'],
    ['Pavanayi', 'പവനായി', 'Overconfident Outsider', 'വലിയ അവകാശവാദങ്ങൾ ഉന്നയിക്കുന്നവൻ'],
    ['Manavalan', 'മാനവാളൻ', 'Comical Businessman', 'തമാശക്കാരനായ വ്യാപാരി'],
    ['Ganga', 'ഗംഗ', 'Double Personality', 'മനസ്സിൽ രഹസ്യം സൂക്ഷിക്കുന്നവൾ'],
    ['Rukmini', 'രുക്മിണി', 'Traditional Homemaker', 'തറവാട്ടിലെ പ്രധാനി'],
    ['Girish M.A.', 'ഗിരീഷ് എം.എ.', 'Funny Romantic Youth', 'പ്രണയിക്കുന്ന ചെറുപ്പക്കാരൻ'],
    ['Shammi', 'ഷമ്മി', 'Unusual Houseguest', 'പ്രത്യേക സ്വഭാവമുള്ള അതിഥി'],
    ['Ranga', 'രംഗ', 'Flamboyant Leader', 'ആവേശക്കാരനായ നായകൻ'],
    ['Dashamoolam Damu', 'ദശമൂലം ദാമു', 'Excitable Comedian', 'ചിരിപ്പിക്കുന്ന കഥാപാത്രം'],
    ['Gafoor Ka Dosth', 'ഗഫൂർ കാ ദോസ്ത്', 'Travel Guide Trickster', 'വഴി കാണിക്കുന്ന സഹായി'],
    ['Anandavalli', 'ആനന്ദവല്ലി', 'Loving Motherly Figure', 'സ്നേഹമുള്ള അമ്മ'],
    ['Beemboy', 'ബീംബോയ്', 'Heavy Lifter', 'ഭാരം ചുമക്കുന്നയാൾ'],
    ['Kattalan Porinchu', 'കാട്ടാളൻ പൊറിഞ്ചു', 'Market Enforcer', 'ചന്തയിലെ കരുത്തൻ'],
    ['Digambaran', 'ദിഗംബരൻ', 'Black Magic Healer', 'മന്ത്രവാദ ക്രിയകൾ'],
    ['Dileep Role', 'ദിലീപ് റോൾ', 'Mimicry Artist', 'മിമിക്രി കലാകാരൻ'],
    ['Kuttan', 'കുട്ടൻ', 'Tech Employee', 'ഐടി ജീവനക്കാരൻ'],
    ['Krishnan', 'കൃഷ്ണൻ', 'Colony Resident', 'കോളനിവാസി'],
    ['Sachy', 'സച്ചി', 'Advocate Writer', 'നിയമജ്ഞനായ എഴുത്തുകാരൻ'],
    ['Aadu Thoma', 'ആട് തോമ', 'Quarry Operator', 'ക്വാറി ഉടമ'],
    ['Keeleri Achu', 'കീശേരി അച്ചു', 'Comical Muscleman', 'ചിരിപ്പിക്കുന്ന ഗുണ്ട'],
    ['Niranjan', 'നിരഞ്ജൻ', 'Convict Fugitive', 'നിയമത്തിൽ നിന്നും ഓടിയവൻ']
  ],
  festivals: [
    ['Kerala Piravi', 'കേരളപ്പിറവി', 'State Anniversary', 'സംസ്ഥാനവുമായി ബന്ധപ്പെട്ട ദിനം'],
    ['Christmas', 'ക്രിസ്മസ്', 'Winter Holiday', 'വർഷാവസാനത്തെ ആഘോഷം'],
    ['Eid', 'ഈദ്', 'Festive Feast Day', 'പ്രാർത്ഥനയും സ്നേഹവുമുള്ള ദിവസം'],
    ['Theyyam', 'തെയ്യം', 'Folk Ritual Performance', 'അനുഷ്ഠാനപരമായ കല'],
    ['Karkidaka Vavu', 'കർക്കിടക വാവ്', 'Solemn Observance', 'ആത്മീയമായ ആചാരം'],
    ['Navarathri', 'നവരാത്രി', 'Multi-day Devotion', 'ദിവസങ്ങൾ നീളുന്ന ആചാരം'],
    ['Thiruvathira', 'തിരുവാതിര', 'Traditional Moonlight Dance', 'സ്ത്രീകൾ പങ്കെടുക്കുന്ന ആചാരം'],
    ['Makaravilakku', 'മകരവിളക്ക്', 'Hilltop Pilgrimage Event', 'തീർത്ഥാടനവുമായി ബന്ധപ്പെട്ടത്'],
    ['Kodiyettam', 'കൊടിയേറ്റം', 'Ceremonial Flag Hoisting', 'ഉത്സവങ്ങളുടെ തുടക്കച്ചടങ്ങ്'],
    ['Pulikali', 'പുലിക്കളി', 'Street Art Procession', 'തെരുവിൽ നടക്കുന്ന കലാപ്രകടനം'],
    ['Aranmula Uthrattathi', 'ആറന്മുള ഉത്രട്ടാതി', 'Historic River Pageant', 'നദിയിലെ പൈതൃക ചടങ്ങ്'],
    ['Kettukazhcha', 'കെട്ടുകാഴ്ച', 'Effigy Display Procession', 'വലിയ രൂപങ്ങൾ എഴുന്നള്ളിക്കുന്നത്'],
    ['Thiruvulsavam', 'തിരുവുത്സവം', 'Annual Temple Celebration', 'വാർഷിക ഉത്സവ കാലം'],
    ['Pooram', 'പൂരം', 'Percussion & Elephant Gathering', 'വാദ്യമേളങ്ങളും ആഘോഷവും'],
    ['Palliperunnal', 'പള്ളിപ്പെരുന്നാൾ', 'Parish Jubilee Feast', 'പ്രാദേശിക പള്ളിയിലെ ഉത്സവം'],
    ['Beemapally Uroos', 'ബീമാപള്ളി ഉറൂസ്', 'Spiritual Annual Event', 'ആത്മീയ സംഗമം'],
    ['Malayattoor Perunnal', 'മലയാറ്റൂർ പെരുന്നാൾ', 'Mountain Pilgrimage', 'മലകയറ്റവും പ്രാർത്ഥനയും'],
    ['Oachira Kettukazhcha', 'ഓച്ചിറ കെട്ടുകാഴ്ച', 'Historic Heritage Fair', 'ചരിത്രപരമായ ഉത്സവം'],
    ['Kalpathi Ratholsavam', 'കൽപ്പാത്തി രഥോത്സവം', 'Traditional Chariot Festival', 'പൈതൃകഗ്രാമത്തിലെ ആഘോഷം'],
    ['Chettikulangara Bharani', 'ചെട്ടികുളങ്ങര ഭരണി', 'Grand Cultural Procession', 'പ്രശസ്തമായ ഗ്രാമോത്സവം'],
    ['Sivarathri', 'ശിവരാത്രി', 'Night-long Devotional Vigil', 'രാത്രിയിലെ ഭക്തിസാന്ദ്രമായ ആചാരം'],
    ['Kuthiyottam', 'കുത്തിയോട്ടം', 'Devotional Step Dance', 'അനുഷ്ഠാന ചുവടുകൾ'],
    ['Kaalavela', 'കാളവേല', 'Straw Effigy Parade', 'വൈക്കോൽ പ്രതിമാ ഘോഷയാത്ര'],
    ['Ganamela', 'ഗാനമേള', 'Stage Audio Setup', 'സ്റ്റേജ് ഓഡിയോ സിസ്റ്റം'],
    ['Kalampaattu', 'കളംപാട്ട്', 'Floor Powder Drawing', 'പൊടിക്കളം വരയ്ക്കൽ'],
    ['Theeyattam', 'തീയാട്ടം', 'Torchlight Ritual', 'പന്തം കൊളുത്തിയുള്ള ചടങ്ങ്'],
    ['Ezhunnallathu', 'എഴുന്നള്ളത്ത്', 'Royal Procession', 'രാജകീയ ഘോഷയാത്ര'],
    ['Chenda Melam', 'ചെണ്ടമേളം', 'Cylindrical Drum Beat', 'താളമേളങ്ങൾ'],
    ['Thalappoli', 'താലപ്പൊലി', 'Lamp Bearing Procession', 'വിളക്കുകളേന്തിയുള്ള യാത്ര'],
    ['Vishu Kani', 'വിഷുക്കണി', 'Morning Auspicious Sight', 'പുലർച്ചെ കാണുന്ന കാഴ്ച'],
    ['Chutti Art', 'ചുട്ടി', 'Rice Paste Makeover', 'അരിമാവ് അലങ്കാരം']
  ],
  places: [
    ['Thrissur', 'തൃശ്ശൂർ', 'Central Heritage Town', 'സാംസ്കാരിക പ്രാധാന്യമുള്ള നഗരം'],
    ['Kollam', 'കൊല്ലം', 'Southern Waterfront District', 'തെക്കൻ ജില്ലയിലെ പ്രധാന ഇടം'],
    ['Kannur', 'കണ്ണൂർ', 'Northern Coastal District', 'വടക്കൻ പൈതൃക നാട്'],
    ['Kottayam', 'കോട്ടയം', 'Inland Rubber Hub', 'തോട്ടങ്ങളും അക്ഷരവുമുള്ള നാട്'],
    ['Palakkad', 'പാലക്കാട്', 'Border Gateway District', 'കാറ്റും പാടങ്ങളുമുള്ള അതിർത്തി'],
    ['Thiruvananthapuram', 'തിരുവനന്തപുരം', 'Administrative Headquarters', 'ഭരണസിരാകേന്ദ്രം'],
    ['Kasaragod', 'കാസർഗോഡ്', 'Northernmost Border Region', 'ഏറ്റവും വടക്കൻ ജില്ല'],
    ['Idukki', 'ഇടുക്കി', 'Mountain Hydro Hub', 'മലനിരകളും ഡാമുകളുമുള്ള ജില്ല'],
    ['Malappuram', 'മലപ്പുറം', 'Passionate Soccer Region', 'കളിയാവേശമുള്ള നാട്'],
    ['Guruvayur', 'ഗുരുവായൂർ', 'Famous Pilgrimage Town', 'പ്രസിദ്ധമായ തീർത്ഥാടന കേന്ദ്രം'],
    ['Bekal', 'ബേക്കൽ', 'Historic Fort Coast', 'ചരിത്രപരമായ കടൽത്തീരം'],
    ['Thekkady', 'തേക്കടി', 'Forest Wildlife Sanctuary', 'വന്യജീവി വിനോദസഞ്ചാര കേന്ദ്രം'],
    ['Kovalam', 'കോവളം', 'International Beach Resort', 'പ്രശസ്തമായ കടൽത്തീരം'],
    ['Ponmudi', 'പൊന്മുടി', 'Misty Hill Station', 'തണുപ്പുള്ള മലമുകൾ'],
    ['Athirappilly', 'അതിരപ്പിള്ളി', 'Waterfall Nature Attraction', 'വനത്തിനുള്ളിലെ ജലാശയം'],
    ['Kumarakom', 'കുമാരകം', 'Backwater Resort Village', 'കായൽ തീരത്തെ ഗ്രാമം'],
    ['Vagamon', 'വാഗമൺ', 'Green Meadows Hill', 'പുൽമേടുകളുള്ള മലയോരം'],
    ['Sultan Bathery', 'സുൽത്താൻ ബത്തേരി', 'Historic Forest Town', 'ചരിത്രമുള്ള വടക്കൻ പട്ടണം'],
    ['Fort Kochi', 'ഫോർട്ട് കൊച്ചി', 'Colonial Heritage Zone', 'പൈതൃകമുള്ള തീരപ്രദേശം'],
    ['Silent Valley', 'സൈലന്റ് വാലി', 'Deep Rainforest Reserve', 'നിശബ്ദമായ വനമേഖല'],
    ['Nelliyampathy', 'നെല്ലിയാമ്പതി', 'Scenic Mountain Range', 'തേയിലത്തോട്ടങ്ങളുള്ള മലയോരം'],
    ['Sabarimala', 'ശബരിമല', 'Dense Forest Shrine', 'വനമധ്യത്തിലെ തീർത്ഥാടനം'],
    ['Sree Padmanabhaswamy Temple', 'ശ്രീപത്മനാഭസ്വാമി ക്ഷേത്രം', 'Vault Heritage Structure', 'നിലവറകളുള്ള സ്മാരകം'],
    ['Thenmala', 'തെന്മല', 'Eco-Tourism Dam Zone', 'ഇക്കോ ടൂറിസം മേഖല'],
    ['Marari Beach', 'മരാരി ബീച്ച്', 'Coir Fishing Coast', 'കയർ നിർമ്മാണ തീരം'],
    ['Agasthyarkoodam', 'അഗസ്ത്യർകൂടം', 'Medicinal Herb Peak', 'ഔഷധസസ്യങ്ങളുടെ മല'],
    ['Banasura Sagar', 'ബാണാസുര സാഗർ', 'Earth Dam Reservoir', 'മണ്ണുകൊണ്ട് നിർമ്മിച്ച അണക്കെട്ട്'],
    ['Poonjar', 'പൂഞ്ഞാർ', 'Palace Valley', 'കൊട്ടാരമുള്ള താഴ്വര'],
    ['Muzhappilangad', 'മുഴപ്പിലങ്ങാട്', 'Drive-in Shore', 'വാഹനം ഓടിക്കാവുന്ന തീരം'],
    ['Kuttanad', 'കുട്ടനാട്', 'Below Sea Level Farming', 'സമുദ്രനിരപ്പിന് താഴെയുള്ള കൃഷി'],
    ['Pathanamthitta', 'പത്തനംതിട്ട', 'Pilgrims District', 'തീർത്ഥാടകരുടെ നാട്']
  ],
  food: [
    ['Idiyappam', 'ഇടിയപ്പം', 'Steamed Rice Preparation', 'അരിമാവ് കൊണ്ടുള്ള വിഭവം'],
    ['Dosa', 'ദോശ', 'Griddle Cooked Item', 'ചൂടോടെ ചുട്ടെടുക്കുന്നത്'],
    ['Sambar', 'സാമ്പാർ', 'Vegetable Gravy', 'പച്ചക്കറികൾ ചേർത്ത ഒഴിച്ചു കറി'],
    ['Avial', 'അവിയൽ', 'Mixed Vegetable Combination', 'പല പച്ചക്കറികൾ ചേർത്ത വിഭവം'],
    ['Thoran', 'തോരൻ', 'Grated Coconut Stir-fry', 'തേങ്ങ ചേർത്ത വറുത്തുപ്പേരി'],
    ['Olan', 'ഓലൻ', 'Coconut Milk Vegetable Stew', 'തേങ്ങാപ്പാൽ ചേർത്ത വിഭവം'],
    ['Kalan', 'കാളൻ', 'Yogurt Based Gravy', 'തൈര് ചേർത്ത കട്ടി കറി'],
    ['Erissery', 'എരിശ്ശേരി', 'Roasted Coconut Preparation', 'വറുത്ത തേങ്ങ ചേർത്ത കറി'],
    ['Inji Curry', 'ഇഞ്ചി കറി', 'Spicy Tangy Condiment', 'പുളിയും എരിവുമുള്ള വിഭവം'],
    ['Pappadam', 'പപ്പടം', 'Crunchy Meal Side', 'ഊണിനൊപ്പം പൊട്ടിച്ചു കഴിക്കുന്നത്'],
    ['Payasam', 'പായസം', 'Sweet Liquid Dessert', 'വിശേഷ ദിവസത്തെ മധുര വിഭവം'],
    ['Beef Fry', 'ബീഫ് ഫ്രൈ', 'Spiced Roast Meat', 'മസാല ചേർത്ത മാംസ വിഭവം'],
    ['Meen Curry', 'മീൻ കറി', 'Tangy Seafood Gravy', 'എരിവുള്ള കടൽ വിഭവം'],
    ['Porotta', 'പൊറോട്ട', 'Layered Flatbread', 'അടുക്കുകളുള്ള പ്രശസ്ത വിഭവം'],
    ['Malabar Biriyani', 'മലബാർ ബിരിയാണി', 'Aromatic Spiced Rice', 'സുഗന്ധമുള്ള റൈസ് വിഭവം'],
    ['Pathiri', 'പത്തിരി', 'Soft Rice Flatbread', 'അരിമാവ് കൊണ്ടുള്ള പലഹാരം'],
    ['Karimeen Pollichathu', 'കരിമീൻ പൊള്ളിച്ചത്', 'Banana Leaf Wrapped Seafood', 'ഇലയിൽ പൊതിഞ്ഞു വേവിച്ച വിഭവം'],
    ['Chicken Stew', 'ചിക്കൻ സ്റ്റ്യൂ', 'Mild Coconut Gravy', 'തേങ്ങാപ്പാൽ ചേർത്ത കറി'],
    ['Kothu Parotta', 'കൊത്ത് പൊറോട്ട', 'Street Food Mix', 'തട്ടുകടയിലെ പ്രശസ്ത വിഭവം'],
    ['Palappam', 'പാലപ്പം', 'Lacy Breakfast Item', 'പ്രഭാതത്തിലെ പ്രധാന വിഭവം'],
    ['Thalassery Biriyani', 'തലശ്ശേരി ബിരിയാണി', 'Special Rice Delicacy', 'വടക്കൻ കേരളത്തിലെ വിശേഷ വിഭവം'],
    ['Mutton Chaaps', 'മട്ടൺ ചാപ്സ്', 'Pepper Gravy Roast', 'കുരുമുളക് ചേർത്ത വിഭവം'],
    ['Kappa Biriyani', 'കപ്പ ബിരിയാണി', 'Tuber Meat Blend', 'കിഴങ്ങും ഇറച്ചിയും ചേർത്തത്'],
    ['Neyyappam Special', 'നെയ്യപ്പം', 'Fried Rice Batter Cake', 'വറുത്തെടുത്ത അരിമാവ് പലഹാരം'],
    ['Kallappam', 'കള്ളപ്പം', 'Fermented Rice Pancake', 'പുളിപ്പിച്ച അരിപ്പലഹാരം'],
    ['Chemeen Curry', 'ചെമ്മീൻ കരി', 'Kokum Seafood Stew', 'കുടംപുളി ചേർത്ത കറി'],
    ['Parippu Curry', 'പരിപ്പ് കറി', 'Yellow Lentil Mash', 'പരിപ്പ് വേവിച്ചത്'],
    ['Meen Peera', 'മീൻ പീര', 'Grated Coconut Seafood', 'തേങ്ങ അരച്ച വിഭവം'],
    ['Fish Moolie', 'ഫിഷ് മോളി', 'Coconut Milk Fish Stew', 'തേങ്ങാപ്പാലിലുള്ള മീൻ കറി'],
    ['Chicken 65', 'ചിക്കൻ 65', 'Deep Fried Spicy Bite', 'വറുത്തെടുത്ത മാംസ വിഭവം'],
    ['Chammanthi Podi', 'ചമ്മന്തിപ്പൊടി', 'Dry Ground Coconut Mix', 'ഉണക്കത്തേങ്ങ അരച്ചത്']
  ],
  bakery: [
    ['Cutlet', 'കട്ട്ലറ്റ്', 'Crumbed Spiced Snack', 'മൊരിഞ്ഞ ബേക്കറി സ്നാക്ക്'],
    ['Samosa', 'സമോസ', 'Filled Triangular Snack', 'ത്രികോണ രൂപത്തിലുള്ള പലഹാരം'],
    ['Bonda', 'ബോണ്ട', 'Round Deep Fried Snack', 'ഉരുണ്ട വറുത്ത പലഹാരം'],
    ['Parippu Vada', 'പരിപ്പ് വട', 'Crunchy Lentil Bite', 'കറുമുറെ കഴിക്കുന്ന വട'],
    ['Ela Ada', 'ഇല അട', 'Leaf Steamed Sweet', 'ഇലയിൽ പൊതിഞ്ഞു വേവിച്ചത്'],
    ['Achappam', 'അച്ചപ്പം', 'Molded Crispy Snack', 'അച്ചിൽ ചുട്ടെടുക്കുന്ന വിഭവം'],
    ['Unniyappam', 'ഉണ്ണിയപ്പം', 'Round Sweet Fritter', 'ഉരുണ്ട മധുര പലഹാരം'],
    ['Banana Chips', 'വാഴക്ക ചിപ്സ്', 'Crunchy Fried Slices', 'വറുത്തുപ്പേരി'],
    ['Sharkara Upperi', 'ശർക്കര ഉപ്പേരി', 'Jaggery Coated Snack', 'മധുരത്തിൽ പൊതിഞ്ഞ കഷണങ്ങൾ'],
    ['Kappa Chips', 'കപ്പ ചിപ്സ്', 'Spiced Tuber Crisps', 'എരിവുള്ള ചിപ്സ്'],
    ['Avalose Podi', 'അവലോസ് പൊടി', 'Roasted Flour Mix', 'വറുത്തുണ്ടാക്കുന്ന പൊടി'],
    ['Kozhalappam', 'കൊഴലപ്പം', 'Crispy Tube Snack', 'കുഴൽ രൂപത്തിലുള്ള പലഹാരം'],
    ['Kinnathappam', 'കിണ്ണത്തപ്പം', 'Steamed Sweet Cake', 'പാത്രത്തിൽ വേവിച്ച മധുരം'],
    ['Churuttu', 'ചുരുട്ട്', 'Rolled Sweet Pastry', 'ചുരുട്ടി വെച്ച മധുരപലഹാരം'],
    ['Halwa', 'ഹൽവ', 'Colorful Sweet Slab', 'ബേക്കറിയിലെ മധുര വിഭവം'],
    ['Sukhiyan', 'സുഖിയൻ', 'Sweet Lentil Fritter', 'മധുരം നിറച്ചു വറുത്ത പലഹാരം'],
    ['Bread Pakora', 'ബ്രെഡ് പക്കോട', 'Teatime Fried Slice', 'വൈകുന്നേരത്തെ ചൂടുള്ള പലഹാരം'],
    ['Laddoo', 'ലഡ്ഡു', 'Round Festive Sweet', 'ഉരുണ്ട മധുരപലഹാരം'],
    ['Jalebi', 'ജിലേബി', 'Syrup Coated Crispy Sweet', 'മധുരപാനീയത്തിൽ മുക്കിയ വിഭവം'],
    ['Meat Roll', 'മീറ്റ് റോൾ', 'Spiced Bakery Pastry', 'ബേക്കറിയിലെ എരിവുള്ള സ്നാക്ക്'],
    ['Boli', 'ബോളി', 'Yellow Gram Flatbread', 'മഞ്ഞ നിറമുള്ള മധുരപ്പൊടി'],
    ['Chatti Pathiri', 'ചട്ടി പത്തിരി', 'Layered Pastry Cake', 'അടുക്കുകളായുള്ള പലഹാരം'],
    ['Vettu Cake', 'വെട്ട് കേക്ക്', 'Cross Cut Dough Ball', 'കുറുകെ വരഞ്ഞ പലഹാരം'],
    ['Pakkavada', 'പക്കവട', 'Spiced Ribbon Crisps', 'എരിവുള്ള നാടൻ സ്നാക്ക്'],
    ['Kayyappam', 'കയ്യപ്പം', 'Banana Fritter Ball', 'പഴം ചേർത്ത ഉണ്ടപ്പലഹാരം'],
    ['Ilayappam', 'ഇലയപ്പം', 'Leaf Wrapped Dumpling', 'ഇലയിൽ പൊതിഞ്ഞത്'],
    ['Mothagam', 'മോദകം', 'Sweet Filled Steamed Ball', 'മധുരം നിറച്ച കൊഴുക്കട്ട'],
    ['Mutta Puff', 'മുട്ട പഫ്', 'Layered Egg Pastry', 'അടുക്കുകളുള്ള ബേക്കറി വിഭവം'],
    ['Cream Bun', 'ക്രീം ബൺ', 'Sweet Filled Bread', 'മധുരം തേച്ച റൊട്ടി'],
    ['Mixture', 'മിക്സ്ചർ', 'Assorted Savory Crunch', 'പലതരം വറുത്തവയുടെ മിശ്രിതം'],
    ['Pahadi Halwa', 'കോഴിക്കോടൻ ഹൽവ', 'Black Sweet Slice', 'കറുത്ത മധുര വിഭവം']
  ],
  home: [
    ['Uruli', 'ഉരുളി', 'Heavy Cookware', 'വലിയ ഓട്ടുപാത്രം'],
    ['Para', 'പറ', 'Traditional Measuring Unit', 'പഴയകാല അളവുപാത്രം'],
    ['Kudam', 'കുടം', 'Water Storage Vessel', 'വെള്ളം സൂക്ഷിക്കുന്ന പാത്രം'],
    ['Chembu', 'ചെമ്പ്', 'Large Metal Boiler', 'വലിയ പാചക പാത്രം'],
    ['Ammikallu', 'അമ്മിക്കല്ല്', 'Stone Grinding Tool', 'അരയ്ക്കാൻ ഉപയോഗിക്കുന്ന കല്ല്'],
    ['Arakkallu', 'അരക്കല്ല്', 'Traditional Stone Grinder', 'ചമ്മന്തി അരയ്ക്കുന്ന ഉപകരണം'],
    ['Aattukallu', 'ആട്ടുകല്ല്', 'Heavy Grinding Stone', 'മാവടിക്കാനുള്ള കല്ല്'],
    ['Kindi', 'കിണ്ടി', 'Spouted Metal Vessel', 'പൂജയ്ക്കും മറ്റും ഉപയോഗിക്കുന്ന പാത്രം'],
    ['Thookkuvilakku', 'തൂക്കുവിളക്ക്', 'Hanging Metal Lamp', 'തൂക്കിയിടുന്ന വിളക്ക്'],
    ['Mundu', 'മുണ്ട്', 'Traditional Bottom Wear', 'പരമ്പരാഗത പുരുഷ വസ്ത്രം'],
    ['Kasavu Saree', 'കസവ് സാരി', 'Golden Border Saree', 'സ്വർണ്ണക്കരയുള്ള വസ്ത്രം'],
    ['Chirava', 'ചിരവ', 'Kitchen Grating Tool', 'അടുക്കളയിലെ ഇരിപ്പിടം'],
    ['Paathram', 'പാത്രം', 'General Utensil', 'അടുക്കളയിലെ പാത്രം'],
    ['Puttu Kutti', 'പുട്ടുകുറ്റി', 'Steaming Cylinder Tool', 'ആവിയിൽ വേവിക്കുന്ന കുറ്റി'],
    ['Vaal Kannadi', 'വാൽക്കണ്ണാടി', 'Handheld Brass Mirror', 'വിഷുക്കണിയിലെ കണ്ണാടി'],
    ['Kalam', 'കലം', 'Clay Cooking Pot', 'മൺപാത്രം'],
    ['Cheenachatti', 'ചീനച്ചട്ടി', 'Deep Frying Pan', 'വറുക്കാൻ ഉപയോഗിക്കുന്ന പാത്രം'],
    ['Kettle', 'കെറ്റിൽ', 'Water Boiling Pot', 'വെള്ളം തിളപ്പിക്കുന്ന ഉപകരണം'],
    ['Bharani', 'ഭരണി', 'Ceramic Pickle Jar', 'അച്ചാർ സൂക്ഷിക്കുന്ന ഭരണി'],
    ['Kattil', 'കട്ടിൽ', 'Bedroom Wooden Furniture', 'കിടക്കാൻ ഉപയോഗിക്കുന്നത്'],
    ['Oonjal', 'ഊഞ്ഞാൽ', 'Hanging Porch Seat', 'മുറ്റത്തോ വരാന്തയിലോ കെട്ടുന്നത്'],
    ['Chattuvam', 'ചട്ടുക്ക', 'Flat Stirring Spatula', 'ഇളക്കാനുള്ള ഉപകരണം'],
    ['Paya', 'പായ', 'Woven Grass Mat', 'പുല്ലുകൊണ്ട് മെടഞ്ഞത്'],
    ['Thiri', 'തിരി', 'Cotton Lamp Wick', 'വിളക്കിലിടുന്ന പരുത്തി'],
    ['Kindu Brass', 'ഓട്ടുപാത്രം', 'Metal Plate Vessel', 'ലോഹ പാത്രം'],
    ['Alavu Para', 'അളവുപാത്രം', 'Grain Measure Vessel', 'ധാന്യങ്ങൾ അളക്കുന്നത്'],
    ['Kindu Vessel', 'വാൽക്കിണ്ടി', 'Water Pouring Vessel', 'വെള്ളം ഒഴിക്കുന്ന പാത്രം'],
    ['Chappathi Kallu', 'ചപ്പാത്തി കല്ല്', 'Rolling Pin Base', 'മാവു പരത്തുന്ന ഉപകരണം'],
    ['Arippa', 'അരിപ്പ', 'Tea Strainer Mesh', 'അരിച്ചെടുക്കാൻ ഉപയോഗിക്കുന്നത്'],
    ['Choottu', 'ചൂട്ട്', 'Dry Palm Torch', 'രാത്രി വെളിച്ചം തരുന്ന ഓല'],
    ['Madaal', 'മടൽ', 'Palm Frond Base', 'തെങ്ങിന്റെ ഭാഗം']
  ],
  people: [
    ['Dileep', 'ദിലീപ്', 'Popular Entertainer', 'ജനപ്രിയ നായകൻ'],
    ['Suresh Gopi', 'സുരേഷ് ഗോപി', 'Action Dialogue Star', 'ആക്ഷൻ ഡയലോഗ് താരം'],
    ['Prithviraj', 'പൃഥ്വിരാജ്', 'Modern Cinema Lead', 'പ്രമുഖ യുവനായകൻ'],
    ['Tovino Thomas', 'ടൊവിനോ തോമസ്', 'Youth Action Star', 'ആവേശമുയർത്തുന്ന നായകൻ'],
    ['Nivin Pauly', 'നിവിൻ പോളി', 'Romantic Comedy Lead', 'റൊമാന്റിക് ഹീറോ'],
    ['Kunchacko Boban', 'കുഞ്ചാക്കോ ബോബൻ', 'Family Favorite Hero', 'കുടുംബ ചിത്രങ്ങളിലെ നായകൻ'],
    ['Jayaram', 'ജയറാം', 'Family Entertainer', 'കുടുംബ പ്രേക്ഷകരുടെ താരം'],
    ['Jayasurya', 'ജയസൂര്യ', 'Character Actor', 'വൈവിധ്യമുള്ള കഥാപാത്രങ്ങൾ ചെയ്യുന്ന നടൻ'],
    ['Parvathy Thiruvothu', 'പാർവതി തിരുവോത്ത്', 'Award Winning Actress', 'ശക്തമായ കഥാപാത്രങ്ങൾ ചെയ്യുന്ന നായിക'],
    ['Nazriya Nazim', 'നസ്രിയ നസീം', 'Charming Lead', 'പ്രേക്ഷകരുടെ പ്രിയ നായിക'],
    ['Anaswara Rajan', 'അനശ്വര രാജൻ', 'Young Generation Star', 'പുതിയ തലമുറയിലെ നായിക'],
    ['Aishwarya Lekshmi', 'ഐശ്വര്യ ലക്ഷ്മി', 'Popular Lead Actress', 'പ്രശസ്ത നായിക'],
    ['Asif Ali', 'ആസിഫ് അലി', 'Relatable Youth Lead', 'യുവാക്കളുടെ പ്രിയ താരം'],
    ['Basil Joseph', 'ബേസിൽ ജോസഫ്', 'Director & Actor', 'സംവിധായകനും നടനും'],
    ['Vineeth Sreenivasan', 'വിനീത് ശ്രീനിവാസൻ', 'Multi Talented Artist', 'പാട്ടുകാരനും സംവിധായകനും നടനും'],
    ['Dulquer Salmaan', 'ദുൽഖർ സൽമാൻ', 'Youth Icon Star', 'പുതിയ തലമുറയിലെ പ്രമുഖ നായകൻ'],
    ['Suraj Venjaramoodu', 'സുരാജ് വെഞ്ഞാറമൂട്', 'Comedy & Drama Legend', 'ചിരിപ്പിക്കുകയും കരയിക്കുകയും ചെയ്യുന്ന നടൻ'],
    ['Jagathy Sreekumar', 'ജഗതി ശ്രീകുമാർ', 'Evergreen Comedy Emperor', 'മലയാളിയുടെ എക്കാലത്തെയും പ്രിയ ഹാസ്യനടൻ'],
    ['Innocent', 'ഇന്നസെന്റ്', 'Beloved Character Star', 'തമാശയും സ്നേഹവുമുള്ള നടൻ'],
    ['Soubin Shahir', 'സൗബിൻ ഷാഹിർ', 'Natural Acting Talent', 'സ്വാഭാവിക അഭിനയ ശൈലിയുള്ള നടൻ'],
    ['Kalyani Priyadarshan', 'കല്യാണി പ്രിയദർശൻ', 'Modern Youth Actress', 'യുവനിരയിലെ ശ്രദ്ധേയയായ നായിക'],
    ['K. J. Yesudas', 'കെ. ജെ. യേശുദാസ്', 'Classical Concert Vocalist', 'കർണ്ണാട്ടിക് സംഗീതജ്ഞൻ'],
    ['K. S. Chithra', 'കെ. എസ്. ചിത്ര', 'Melody Pioneer', 'ഗാനരംഗത്തെ പ്രമുഖ'],
    ['Sanju Samson', 'സഞ്ജു സാംസൺ', 'Wicketkeeper Athlete', 'വിക്കറ്റ് കാക്കുന്ന കായികതാരം'],
    ['Shashi Tharoor', 'ശശി തരൂർ', 'English Lexicon Author', 'ഇംഗ്ലീഷ് പദപ്രയോഗങ്ങൾ അറിയുന്നയാൾ'],
    ['Sreenivasan', 'ശ്രീനിവാസൻ', 'Satirical Screenwriter', 'ആക്ഷേപഹാസ്യ എഴുത്തുകാരൻ'],
    ['Salim Kumar', 'സലിം കുമാർ', 'National Award Comedian', 'അംഗീകാരം നേടിയ ഹാസ്യനടൻ'],
    ['Urveshi', 'ഉർവ്വശി', 'Brilliant Character Lead', 'ശക്തമായ അഭിനയമികവുള്ള നായിക'],
    ['Mukesh', 'മുകേഷ്', 'Witty Dialogue Lead', 'സംഭാഷണങ്ങളിൽ തമാശയുള്ള നടൻ'],
    ['Biju Menon', 'ബിജു മേനോൻ', 'Deep Voice Actor', 'ഗംഭീര ശബ്ദമുള്ള താരം'],
    ['Pepe Antony', 'ആന്റണി വർഗ്ഗീസ്', 'Angamaly Action Lead', 'ആക്ഷൻ രംഗങ്ങളിലെ നായകൻ']
  ],
  life: [
    ['Panchayath', 'പഞ്ചായത്ത്', 'Local Administration', 'നാട്ടിൻപുറത്തെ ഭരണകൂടം'],
    ['Kudumbashree', 'കുടുംബശ്രീ', 'Women Self-help Group', 'വനിതകളുടെ കൂട്ടായ്മ'],
    ['Anganwadi', 'അങ്കണവാടി', 'Village Child Center', 'കുട്ടികളുടെ പരിപാലന കേന്ദ്രം'],
    ['Rubber Thottam', 'റബ്ബർ തോട്ടം', 'Agricultural Estate', 'പാൽ എടുക്കുന്ന തോട്ടം'],
    ['Tea Estate', 'തേയിലത്തോട്ടം', 'Hill Plantation', 'മലയോരത്തെ പച്ചപ്പ്'],
    ['Thengu', 'തെങ്ങ്', 'Signature Tropical Tree', 'കേരളത്തിന്റെ കൽപവൃക്ഷം'],
    ['Kuttanadan Padanilam', 'കുട്ടനാടൻ പാടനിലം', 'Vast Agricultural Fields', 'വിശാലമായ കാർഷിക നിലം'],
    ['Puzha', 'പുഴ', 'Flowing River', 'ഒഴുകുന്ന ജലാശയം'],
    ['Kaithari', 'കൈത്തറി', 'Handloom Weaving', 'പരമ്പരാഗത വസ്ത്ര നിർമ്മാണം'],
    ['Mazha', 'മഴ', 'Monsoon Weather', 'പ്രകൃതിയിലെ കാലാവസ്ഥ'],
    ['Tharavad', 'തറവാട്', 'Heritage Family Mansion', 'പൈതൃകമുള്ള വലിയ വീട്'],
    ['Naadan Pattu', 'നാടൻ പാട്ട്', 'Folk Musical Tradition', 'നാട്ടിൻപുറത്തെ പാട്ടുകൾ'],
    ['Kavala', 'കവല', 'Village Junction', 'ആളുകൾ കൂടുന്ന കവല'],
    ['Palli', 'പള്ളി', 'Place of Worship', 'ആരാധനാലയം'],
    ['Ambalam', 'അമ്പലം', 'Sacred Temple', 'ദൈവികമായ സ്ഥലം'],
    ['Lottery Ticket', 'ലോട്ടറി ടിക്കറ്റ്', 'Luck and Fortune Hope', 'ഭാഗ്യപരീക്ഷണം'],
    ['Hartal', 'ഹർത്താൽ', 'Public Shutdown Day', 'കടകളും വണ്ടികളും അടങ്ങുന്ന ദിവസം'],
    ['Vayanasala', 'വായനശാല', 'Village Library & Reading Room', 'പുസ്തകങ്ങളും പത്രങ്ങളും വായിക്കുന്ന ഇടം'],
    ['Chitty', 'ചിട്ടി', 'Monthly Savings Scheme', 'നാട്ടിൻപുറത്തെ സാമ്പത്തിക ഇടപാട്'],
    ['Kavukal', 'കാവ്', 'Sacred Forest Grove', 'പ്രകൃതിയും വിശ്വാസവും ചേർന്ന സ്ഥലം'],
    ['Kulam', 'കുളം', 'Village Bathing Pond', 'നാട്ടിൻപുറത്തെ ജലാശയം'],
    ['Milma', 'മിൽമ', 'Blue Packet Dairy', 'നീല കവറിലുള്ള ഉൽപ്പന്നം'],
    ['Bevco', 'ബെവ്കോ', 'Evening Queue Outlet', 'വൈകുന്നേരത്തെ വരി'],
    ['Akshaya Centre', 'അക്ഷയ കേന്ദ്രം', 'Digital Certificate Counter', 'രേഖകൾ ശരിയാക്കുന്ന സ്ഥലം'],
    ['Supplyco', 'സപ്ലൈകോ', 'Subsidized Ration Depot', 'സബ്സിഡി സാധനങ്ങൾ കിട്ടുന്നിടം'],
    ['Vidyabhyasa Loan', 'വിദ്യാഭ്യാസ വായ്പ', 'College Tuition Funding', 'പഠനത്തിനുള്ള ധനസഹായം'],
    ['Ration Kada', 'റേഷൻ കട', 'Essential Supply Store', 'നിത്യോപയോഗ സാധന വിതരണം'],
    ['Mahatma Gandhi NREGA', 'തൊഴിലുറപ്പ്', 'Village Morning Assembly', 'ഗ്രാമീണ തൊഴിൽ പദ്ധതി'],
    ['Current Bill', 'കറന്റ് ബിൽ', 'Monthly Electricity Meter', 'വൈദ്യുതി ഉപയോഗ രേഖ'],
    ['KSEB', 'കെഎസ്ഇബി', 'Power Board Authority', 'വൈദ്യുതി വകുപ്പ്'],
    ['Water Authority', 'വാട്ടർ അതോറിറ്റി', 'Pipe Supply Network', 'കുടിവെള്ള വിതരണം']
  ],
  vehicles: [
    ['Jankar', 'ജങ്കാർ', 'Waterway Ferry Craft', 'വാഹനങ്ങൾ കടത്തുന്ന ബോട്ട്'],
    ['Ferry', 'ഫെറി', 'Public Boat Transit', 'ജലമാർഗ്ഗമുള്ള യാത്രാ ബോട്ട്'],
    ['Chundan Vallam', 'ചുണ്ടൻ വള്ളം', 'Long Racing Craft', 'മത്സരത്തിന് ഉപയോഗിക്കുന്ന നീളമുള്ള വള്ളം'],
    ['Kettuvallam', 'കെട്ടുവള്ളം', 'Traditional Houseboat', 'പരമ്പരാഗത വലിയ തോണി'],
    ['Pickup', 'പിക്കപ്പ്', 'Goods Transport Vehicle', 'ചരക്കുകൾ കൊണ്ടുപോകുന്ന വണ്ടി'],
    ['Jeep', 'ജീപ്പ്', 'Hill Station Off-roader', 'മലയോരങ്ങളിൽ ഉപയോഗിക്കുന്ന വാഹനം'],
    ['Lorry', 'ലോറി', 'Heavy Cargo Truck', 'വലിയ ചരക്ക് വാഹനം'],
    ['Private Bus', 'പ്രൈവറ്റ് ബസ്', 'Speedy Passenger Bus', 'വേഗതയിലോടുന്ന സ്വകാര്യ ബസ്'],
    ['Tempo Traveller', 'ടെമ്പോ ട്രാവലർ', 'Group Tour Van', 'സംഘങ്ങളായി യാത്ര ചെയ്യുന്ന വാഹനം'],
    ['Scooter', 'സ്കൂട്ടർ', 'Two-wheeler Ride', 'നിത്യയാത്രയ്ക്ക് ഉപയോഗിക്കുന്ന വാഹനം'],
    ['Cycle', 'സൈക്കിൾ', 'Pedal Powered Transport', 'ചവിട്ടി ഓടിക്കുന്ന വാഹനം'],
    ['Mini Bus', 'മിനി ബസ്', 'Compact Route Bus', 'ചെറിയ യാത്രാ ബസ്'],
    ['Taxi', 'ടാക്സി', 'Hired Passenger Cab', 'വാടകയ്ക്ക് വിളിക്കുന്ന കാർ'],
    ['Train', 'ട്രെയിൻ', 'Railway Transport', 'തീവണ്ടി യാത്ര'],
    ['School Bus', 'സ്കൂൾ ബസ്', 'Student Transport', 'കുട്ടികളെ കൊണ്ടുപോകുന്ന വാഹനം'],
    ['Jik Jik Train', 'തീവണ്ടി', 'Long Distance Rail Journey', 'പാളത്തിലൂടെ ഓടുന്നത്'],
    ['Ambulance', 'ആംബുലൻസ്', 'Emergency Medical Vehicle', 'അടിയന്തര ആവശ്യത്തിന് ഓടുന്നത്'],
    ['Kochi Metro', 'കൊച്ചി മെട്രോ', 'Modern Urban Rail', 'നഗരത്തിലെ വേഗതയേറിയ യാത്ര'],
    ['Tractor', 'ട്രാക്ടർ', 'Farm Field Vehicle', 'കാർഷിക ആവശ്യത്തിന് ഉപയോഗിക്കുന്നത്'],
    ['Excavator', 'ജെസിബി', 'Heavy Earth Mover', 'നിർമ്മാണ പ്രവർത്തനങ്ങൾക്ക് ഉപയോഗിക്കുന്നത്'],
    ['Speed Boat', 'സ്പീഡ് ബോട്ട്', 'Fast Watercraft Ride', 'കായലിലൂടെ വേഗത്തിൽ കുതിക്കുന്നത്'],
    ['Peti Auto', 'പെട്ടി ഓട്ടോ', 'Small Cargo Carrier', 'സാധനങ്ങൾ കൊണ്ടുപോകുന്നത്'],
    ['Ambassador', 'അംബാസഡർ', 'Classic White Sedan', 'പഴയകാല സർക്കാർ വാഹനം'],
    ['Mahindra Jeep', 'മഹീന്ദ്ര ജീപ്പ്', 'Hill Track Vehicle', 'മലയോരങ്ങളിൽ ഓടുന്നത്'],
    ['Chavittu Vandi', 'ചവിട്ടുവണ്ടി', 'Pedal Powered Transport', 'ചവിട്ടി ഓടിക്കുന്നത്'],
    ['RX 100', 'ആർ എക്സ് 100', 'Two Stroke Bike', 'പഴയകാല സ്പീഡ് ബൈക്ക്'],
    ['Torrus Truck', 'ടോറസ്', 'Heavy Rock Carrier', 'വലിയ കല്ലുകൾ കൊണ്ടുപോകുന്നത്'],
    ['Fire Engine', 'ഫയർ ഫോഴ്സ്', 'Red Emergency Tanker', 'രക്ഷാപ്രവർത്തന വാഹനം'],
    ['Water Metro', 'വാട്ടർ മെട്രോ', 'Modern Electric Ferry', 'നൂതന ജലയാത്രാ സൗകര്യം'],
    ['Low Floor Bus', 'ലോ ഫ്ലോർ ബസ്', 'AC City Transit', 'നഗരത്തിലെ എസി യാത്രാ വണ്ടി'],
    ['Tourist Bus', 'ടൂറിസ്റ്റ് ബസ്', 'Music & Light Coach', 'പാട്ടും ലൈറ്റുമുള്ള യാത്രാ വണ്ടി']
  ],
  school: [
    ['Uniform', 'യൂണിഫോം', 'Institutional Attire', 'എല്ലാവരും ധരിക്കുന്ന ഒരേപോലത്തെ വസ്ത്രം'],
    ['School Bus', 'സ്കൂൾ ബസ്', 'Student Transit Vehicle', 'വിദ്യാർത്ഥികളുടെ യാത്രാ വാഹനം'],
    ['PT Period', 'പി ടി പിരീഡ്', 'Sports and Games Hour', 'കളിക്കാനായി കിട്ടുന്ന സമയം'],
    ['Annual Day', 'ആനുവൽ ഡേ', 'Yearly School Function', 'വാർഷിക കലാപരിപാടി'],
    ['Exam Hall', 'എക്സാം ഹാൾ', 'Silent Test Classroom', 'നിശബ്ദമായി പരീക്ഷ എഴുതുന്ന ഇടം'],
    ['Rank List', 'റാങ്ക് ലിസ്റ്റ്', 'Merit Score Results', 'വിജയികളുടെ വിവരങ്ങൾ'],
    ['College Union', 'കോളേജ് യൂണിയൻ', 'Student Council Group', 'വിദ്യാർത്ഥികളുടെ പ്രതിനിധി സഭ'],
    ['Batch', 'ബാച്ച്', 'Classmates Year Group', 'ഒന്നിച്ചു പഠിച്ച കൂട്ടുകാർ'],
    ['Farewell', 'ഫെയർവെൽ', 'Graduation Send-off', 'പഠനം കഴിഞ്ഞ് പിരിയുന്ന ദിവസം'],
    ['NSS', 'എൻ എസ് എസ്', 'Social Service Camp', 'സാമൂഹിക സേവന കൂട്ടായ്മ'],
    ['NCC', 'എൻ സി സി', 'Cadet Corps Training', 'ശിക്ഷണവും പരേഡുമുള്ള സേന'],
    ['Laboratory', 'ലബോറട്ടറി', 'Practical Experiment Room', 'പരീക്ഷണങ്ങൾ ചെയ്യുന്ന മുറി'],
    ['Library', 'ലൈബ്രറി', 'Quiet Book Room', 'പുസ്തകങ്ങൾ സൂക്ഷിക്കുന്ന മുറി'],
    ['Hostel', 'ഹോസ്റ്റൽ', 'Student Living Quarters', 'വിദ്യാർത്ഥികൾ താമസിക്കുന്ന ഹോസ്റ്റൽ മുറി'],
    ['Class Leader', 'ക്ലാസ് ലീഡർ', 'Student Representative', 'ക്ലാസ് നിയന്ത്രിക്കുന്ന വിദ്യാർത്ഥി'],
    ['Tour Trip', 'ഐവി / ടൂർ', 'Group Student Excursion', 'കൂട്ടുകാരോടൊത്തുള്ള യാത്ര'],
    ['Bench and Desk', 'ബെഞ്ചും ഡെസ്കും', 'Classroom Wooden Seating', 'ക്ലാസ് മുറിയിലെ ഇരിപ്പിടം'],
    ['Bell', 'സ്കൂൾ ബെൽ', 'Period Change Sound', 'സമയമാറ്റം അറിയിക്കുന്നത്'],
    ['Principal', 'പ്രിൻസിപ്പൽ', 'Head of Institution', 'സ്ഥാപനത്തിന്റെ പ്രധാന ചുമതലക്കാരൻ'],
    ['Assignment', 'അസൈൻമെന്റ്', 'Written Homework Task', 'എഴുതി സമർപ്പിക്കേണ്ട ജോലി'],
    ['Alumni Meet', 'പൂർവ്വവിദ്യാർത്ഥി സംഗമം', 'Old Classmates Reunion', 'പഴയ കൂട്ടുകാരുടെ ഒത്തുചേരൽ'],
    ['IV (Industrial Visit)', 'ഐവി', 'Final Year Tour', 'അവസാന വർഷ യാത്ര'],
    ['Tuition Class', 'ട്യൂഷൻ ക്ലാസ്', 'Evening Study Batch', 'വൈകുന്നേരത്തെ പഠനം'],
    ['Canara Bank Challan', 'ചെല്ലാൻ', 'Fee Payment Slip', 'ഫീസ് അടക്കാനുള്ള രേഖ'],
    ['Record Book', 'റെക്കോർഡ് ബുക്ക്', 'Lab Diagram Manual', 'ലാബ് വരകളുള്ള പുസ്തകം'],
    ['Study Leave', 'സ്റ്റഡി ലീവ്', 'Pre-Exam Preparation', 'പരീക്ഷാ മുന്നൊരുക്കം'],
    ['Youth Festival', 'യുവജനോത്സവം', 'Inter-College Competition', 'കലാമത്സരങ്ങൾ'],
    ['Progress Report', 'പ്രോഗ്രസ് റിപ്പോർട്ട്', 'Term Mark Evaluation', 'മാർക്ക് വിവരങ്ങളുള്ള രേഖ'],
    ['Geometry Box', 'ജോമട്രി ബോക്സ്', 'Compass & Ruler Case', 'വരയ്ക്കാൻ ഉപയോഗിക്കുന്ന പെട്ടി'],
    ['Slate and Pencil', 'സ്ലേറ്റും പെൻസിലും', 'Childhood Writing Tool', 'ആദ്യകാല പഠന ഉപകരണം'],
    ['School Bag', 'സ്കൂൾ ബാഗ്', 'Books Shoulder Carrier', 'പുസ്തകങ്ങൾ കൊണ്ടുപോകുന്നത്']
  ],
  sports: [
    ['Tug of War', 'വടംവലി', 'Team Rope Pulling', 'കയർ വലിക്കുന്ന മത്സരം'],
    ['Sevens Football', 'സെവൻസ് ഫുട്ബോൾ', 'Local 7-a-side Tournament', 'ചെറിയ മൈതാനത്തെ ആവേശ മത്സരം'],
    ['Kho Kho', 'ഖോ ഖോ', 'Sit & Chase Court Game', 'ഇരുന്നും ഓടിയും കളിക്കുന്നത്'],
    ['Badminton', 'ബാഡ്മിന്റൺ', 'Racket Court Sport', 'റാക്കറ്റും ഷട്ടിലും ഉപയോഗിക്കുന്ന കളി'],
    ['Swimming', 'നീന്തൽ', 'Water Pool Racing', 'വെള്ളത്തിലെ മത്സരം'],
    ['Athletics', 'അത്‌ലറ്റിക്സ്', 'Track and Field Events', 'കായിക മത്സര വേദി'],
    ['Javelin', 'ജാവലിൻ', 'Distance Throwing Event', 'ദൂരത്തേക്ക് എറിയുന്ന മത്സരം'],
    ['Relay', 'റിലേ', 'Team Sprint Event', 'കൈമാറി ഓടുന്ന മത്സരം'],
    ['Boat Race', 'വള്ളംകളി', 'Traditional River Race', 'കായലിലെ വേഗത മത്സരം'],
    ['Carrom', 'കാരംസ്', 'Indoor Board Game', 'ബോർഡിൽ കളിക്കുന്ന ഇൻഡോർ ഗെയിം'],
    ['Chess', 'ചെസ്സ്', 'Mind Strategy Game', 'ബുദ്ധി ഉപയോഗിക്കുന്ന ബോർഡ് ഗെയിം'],
    ['Kalari', 'കളരി', 'Martial Art Tradition', 'പരമ്പരാഗത അഭ്യാസ മുറ'],
    ['Long Jump', 'ലോംഗ് ജമ്പ്', 'Sand Pit Distance Leap', 'ദൂരത്തേക്ക് ചാടുന്ന മത്സരം'],
    ['High Jump', 'ഹൈ ജമ്പ്', 'Bar Clearance Leaping', 'ഉയരത്തിലേക്ക് ചാടുന്ന മത്സരം'],
    ['Throwball', 'ത്രോബോൾ', 'Over the Net Sport', 'ബോൾ എറിഞ്ഞു കളിക്കുന്നത്'],
    ['Table Tennis', 'ടേബിൾ ടെന്നീസ്', 'Indoor Table Racket Game', 'ഇൻഡോർ മത്സര വിനോദം'],
    ['Marathon', 'മാരത്തൺ', 'Long Distance Running Race', 'ദീർഘദൂര ഓട്ടമത്സരം'],
    ['Penalty Shootout', 'പെനാൽറ്റി ഷൂട്ടൗട്ട്', 'Tiebreaker Goal Kick', 'നിർണായകമായ ഗോൾ മത്സരം'],
    ['Trophy', 'ട്രോഫി', 'Tournament Winner Cup', 'വിജയികൾക്ക് നൽകുന്ന സമ്മാനം'],
    ['Umpire', 'അമ്പയർ', 'Match Referee Authority', 'കളിയുടെ വിധികർത്താവ്'],
    ['Gallery', 'ഗാലറി', 'Spectator Seating Stands', 'കാണികൾ ഇരിക്കുന്ന സ്ഥലം'],
    ['Kuttiyum Kolum', 'കുട്ടിയും കോലും', 'Wooden Stick Strike', 'മരക്കമ്പ് കൊണ്ടുള്ള കളി'],
    ['Kilithattu', 'കിളിത്തട്ട്', 'Court Crossing Dodge', 'വരകൾ കടന്നുള്ള കളി'],
    ['Talappanthukali', 'തലപ്പന്തുകളി', 'Coconut Leaf Ball Game', 'ഓലപ്പന്ത് കളി'],
    ['Nadan Panthu', 'നാടൻ പന്ത്', 'Leather Stitched Ball', 'തൊലി കൊണ്ടുണ്ടാക്കിയ പന്ത്'],
    ['Goli', 'ഗോലി', 'Glass Marble Aim', 'കണ്ണാടിച്ചില്ല് ഉണ്ടകൾ'],
    ['Lagori', 'ലഗോറി', 'Tile Stack Strike', 'ഓടുടുക്കുകൾ എറിഞ്ഞുവീഴ്ത്തൽ'],
    ['Arm Wrestling', 'പഞ്ചഗുസ്തി', 'Hand Strength Contest', 'കൈക്കരുത്ത് പരീക്ഷിക്കുന്നത്'],
    ['Kabaddi Court', 'കബഡി കോർട്ട്', 'Breath Control Game Area', 'ശ്വാസം പിടിച്ചു കളിക്കുന്ന വേദി'],
    ['Shuttle Racket', 'ഷട്ടിൽ റാക്കറ്റ്', 'Feather Birdie Game Tool', 'ഷട്ടിൽ കളിക്കുന്ന ഉപകരണം'],
    ['Foot Volley', 'ഫൂട്ട് വോളി', 'Leg Only Ball Game', 'കാലുകൊണ്ട് മാത്രം കളിക്കുന്നത്']
  ],
  gulf: [
    ['Abu Dhabi', 'അബുദാബി', 'Capital Emirate City', 'തലസ്ഥാന നഗരം'],
    ['Qatar', 'ഖത്തർ', 'Gas Rich Gulf Nation', 'പ്രസിദ്ധമായ ഗൾഫ് രാജ്യം'],
    ['Saudi', 'സൗദി', 'Largest Arabian Nation', 'വലിയ മരുഭൂമി രാജ്യം'],
    ['Oman', 'ഒമാൻ', 'Scenic Middle East Country', 'പ്രകൃതിഭംഗിയുള്ള ഗൾഫ് രാജ്യം'],
    ['Bahrain', 'ബഹ്റൈൻ', 'Island Arabian Kingdom', 'ദ്വീപ് രൂപത്തിലുള്ള രാജ്യം'],
    ['Kuwait', 'കുവൈറ്റ്', 'High Currency Gulf State', 'ഉയർന്ന കറൻസി മൂല്യമുള്ള രാജ്യം'],
    ['Visa', 'വിസ', 'Travel Permit Approval', 'വിദേശയാത്രയ്ക്കുള്ള അനുമതി'],
    ['Passport', 'പാസ്പോർട്ട്', 'International Travel Document', 'യാത്ര ചെയ്യാനുള്ള രേഖ'],
    ['Airport', 'എയർപോർട്ട്', 'Flight Terminal', 'വിമാനങ്ങൾ വന്നിറങ്ങുന്ന സ്ഥലം'],
    ['Remittance', 'റെമിറ്റൻസ്', 'Money Sent to Family', 'നാട്ടിലേക്ക് അയക്കുന്ന പണം'],
    ['Duty Free', 'ഡ്യൂട്ടി ഫ്രീ', 'Airport Shopping Zone', 'എയർപോർട്ടിലെ ഷോപ്പിംഗ് സ്ഥലം'],
    ['Perfume', 'പെർഫ്യൂം', 'Fragrant Gift Item', 'സുഗന്ധം പരത്തുന്ന സമ്മാനം'],
    ['Dates', 'ഈത്തപ്പഴം', 'Arabian Palm Fruit', 'മരുഭൂമിയിലെ മധുരമുള്ള പഴം'],
    ['Gold', 'സ്വർണം', 'Precious Metal Investment', 'വിലയേറിയ ആഭരണ വസ്തു'],
    ['Return Ticket', 'റിട്ടേൺ ടിക്കറ്റ്', 'Homeward Flight Booking', 'തിരികെ പോകാനുള്ള ടിക്കറ്റ്'],
    ['Norka', 'നോർക്ക', 'Expatriate Welfare Agency', 'പ്രവാസികളുടെ ക്ഷേമ സംഘടന'],
    ['Sharjah', 'ഷാർജ', 'Popular Emirate Hub', 'മലയാളികൾ ഏറെയുള്ള ഗൾഫ് നഗരം'],
    ['Baklava', 'ബക്ലാവ', 'Arabian Sweet Pastry', 'മധ്യപൂർവ്വേഷ്യയിലെ മധുരപലഹാരം'],
    ['Desert Safari', 'മരുഭൂമി സഫാരി', 'Sand Dune Adventure', 'മരുഭൂമിയിലെ സാഹസിക യാത്ര'],
    ['Burj Khalifa', 'ബുർജ് ഖലീഫ', 'World Famous Skyscraper', 'ലോകത്തിലെ ഏറ്റവും വലിയ കെട്ടിടം'],
    ['Vacation Leave', 'അവധി / ലീവ്', 'Annual Trip Home', 'നാട്ടിലേക്ക് വരുന്ന സന്തോഷ സമയം'],
    ['Dubai Gold Souk', 'ദുബായ് ഗോൾഡ് സൂക്ക്', 'Jewellery Market Lane', 'ആഭരണ വിപണി'],
    ['Khubus', 'കുബ്ബൂസ്', 'Round Arabian Bread', 'വട്ടത്തിലുള്ള അറേബ്യൻ റൊട്ടി'],
    ['Kafala', 'കഫാല', 'Sponsorship Regulations', 'സ്പോൺസർഷിപ്പ് നിയമം'],
    ['Perfume Attar', 'അത്തർ', 'Concentrated Fragrance Oil', 'സുഗന്ധദ്രവ്യം'],
    ['Qatar Airways', 'ഖത്തർ എയർവേയ്സ്', 'Gulf Connection Carrier', 'പ്രവാസികളുടെ വിമാനയാത്ര'],
    ['Shawarma Machine', 'ഷവർമ്മ മെഷീൻ', 'Rotating Grill Skewer', 'ഇറച്ചി കറങ്ങി വേവുന്നത്'],
    ['Oud Incense', 'ഊദ്', 'Aromatic Wood Smoke', 'സുഗന്ധമുള്ള പുക'],
    ['Lablabi / Hummus', 'ഹുമുസ്', 'Chickpea Dip Paste', 'അറേബ്യൻ ഭക്ഷണം കഴിക്കുമ്പോൾ കൂട്ടുന്നത്'],
    ['Dirham Currency', 'ദിർഹം', 'Expatriate Salary Note', 'ഗൾഫിലെ കറൻസി'],
    ['Emirates ID', 'എമിറേറ്റ്സ് ഐഡി', 'Residence Identity Card', 'ഗൾഫിലെ തിരിച്ചറിയൽ രേഖ']
  ]
};

Object.assign(window, { extraWords: window.extraWords });

var packs = [
  {id:'funny',name:'Funny Malayalam',icon:'😂',words:[['Pwoli','പൊളി','High Energy','വലിയ ആവേശം'],['Ayyayyo','അയ്യയ്യോ','Sudden Reaction','പെട്ടെന്നുള്ള പ്രതികരണം'],['Scene illa','സീൻ ഇല്ല','Calm Mindset','സമാധാനപരമായ അവസ്ഥ'],['Thallal','തള്ളൽ','Tall Tales','കൂട്ടുകാരുടെ സംസാരം'],['Kidu','കിടു','Great Impression','നല്ല അനുഭവം']]},
  {id:'movies',name:'Movies',icon:'🎬',words:[['Manichitrathazhu','മണിച്ചിത്രത്താഴ്','Ancient Mansion Mystery','പഴയ തറവാട്ടിലെ രഹസ്യം'],['Drishyam','ദൃശ്യം','Clever Cover-up','ബുദ്ധിപരമായ നീക്കങ്ങൾ'],['Kumbalangi Nights','കുമ്പളങ്ങി നൈറ്റ്സ്','Coastal Brotherhood','തീരദേശത്തെ ജീവിതം'],['Bangalore Days','ബാംഗ്ലൂർ ഡെയ്സ്','Cousins Bonding','ബന്ധുക്കളുടെ കൂട്ടായ്മ'],['Premam','പ്രേമം','Stages of Life','ജീവിതത്തിലെ വിവിധ ഘട്ടങ്ങൾ']]},
  {id:'characters',name:'Characters',icon:'🎯',words:[['Georgekutty','ജോർജ് കുട്ടി','Resourceful Protector','കുടുംബത്തെ സംരക്ഷിക്കുന്നവൻ'],['Nagavalli','നാഗവല്ലി','Legendary Persona','പഴയകാല ഓർമ്മകളുള്ള കഥാപാത്രം'],['Sethumadhavan','സേതുമാധവൻ','Misunderstood Youth','സാഹചര്യങ്ങളുടെ ഇര'],['Dasan','ദാസൻ','Jobless Aspiring Man','വലിയ സ്വപ്നങ്ങളുള്ള യുവാവ്'],['Mangalassery Neelakandan','മംഗലശ്ശേരി നീലകണ്ഠൻ','Powerful Feudal Figure','ഗ്രാമത്തിലെ പ്രബലനായ വ്യക്തി']]},
  {id:'festivals',name:'Festivals',icon:'🎉',words:[['Onam','ഓണം','Seasonal Celebration','സീസണലായ ആഘോഷം'],['Vishu','വിഷു','Traditional Calendar Event','പാരമ്പര്യ ആചാര ദിനം'],['Thrissur Pooram','തൃശ്ശൂർ പൂരം','Cultural Spectacle','വലിയ ജനക്കൂട്ടമുള്ള ഉത്സവം'],['Attukal Pongala','ആറ്റുകാൽ പൊങ്കാല','Devotional Gathering','ഭക്തിസാന്ദ്രമായ കൂട്ടായ്മ'],['Vallamkali','വള്ളംകളി','Backwater Competition','ജലത്തിൽ നടക്കുന്ന മത്സരം']]},
  {id:'places',name:'Places',icon:'📍',words:[['Kochi','കൊച്ചി','Coastal City','കടൽത്തീരത്തെ നഗരം'],['Munnar','മൂന്നാർ','Hill Destination','മലയോര വിനോദസഞ്ചാര ഇടം'],['Alappuzha','ആലപ്പുഴ','Waterway Tourism Town','കായലുകളുള്ള നാട്'],['Wayanad','വയനാട്','Green Plateau Region','പ്രകൃതിഭംഗിയുള്ള മലയോരം'],['Varkala','വർക്കല','Tourist Beach Cliff','തീരദേശ വിനോദ കേന്ദ്രം']]},
  {id:'food',name:'Kerala Food',icon:'🍛',words:[['Puttu','പുട്ട്','Steamed Breakfast Staple','ആവിയിൽ വേവിക്കുന്ന പ്രഭാതഭക്ഷണം'],['Appam','അപ്പം','Traditional Morning Bread','രാവിലെ കഴിക്കുന്ന പലഹാരം'],['Sadya','സദ്യ','Traditional Feast','വിശേഷ ദിവസത്തെ വലിയ ഭക്ഷണം'],['Kappa','കപ്പ','Root Vegetable Dish','കിഴങ്ങ് വർഗ്ഗത്തിൽപ്പെട്ടത്'],['Pazham Pori','പഴംപൊരി','Sweet Tea Accompaniment','ചായയ്ക്കൊപ്പമുള്ള മധുരം']]},
  {id:'bakery',name:'Bakery & Snacks',icon:'🥐',words:[['Chaya','ചായ','Popular Hot Drink','ചൂടുള്ള പാനീയം'],['Puffs','പഫ്സ്','Layered Bakery Pastry','ബേക്കറിയിലെ ബേക്കഡ് വിഭവം'],['Uzhunnu Vada','ഉഴുന്നു വട','Crispy Lentil Fritter','വട്ടത്തിൽ വറുത്തെടുത്ത പലഹാരം'],['Mutta Baji','മുട്ട ബജി','Fried Batter Snack','മാവിൽ മുക്കി വറുത്തത്'],['Kozhukkatta','കൊഴുക്കട്ട','Steamed Sweet Dumpling','ആവിയിൽ പുഴുങ്ങിയ മധുരം']]},
  {id:'home',name:'Household Items',icon:'🏠',words:[['Nilavilakku','നിലവിളക്ക്','Traditional Lighting','വീട്ടിലെ പരമ്പരാഗത വിളക്ക്'],['Thorthu','തോർത്തു','Daily Cotton Cloth','നിത്യസഹായ വസ്ത്രം'],['Muram','മുറം','Woven Bamboo Craft','മുള കൊണ്ടുള്ള ഉപകരണം'],['Chattukam','ചട്ടുകം','Kitchen Stirring Utensil','പാചകം ചെയ്യാൻ ഉപയോഗിക്കുന്നത്'],['Mundum Neriyathum','മുണ്ടും നേരിയതും','Traditional Attire','പരമ്പരാഗത വസ്ത്രധാരണം']]},
  {id:'people',name:'People',icon:'👥',words:[['Mohanlal','മോഹൻലാൽ','Acting Legend','മലയാള സിനിമയിലെ പ്രമുഖൻ'],['Mammootty','മമ്മൂട്ടി','Veteran Star','പ്രശസ്തനായ മുതിർന്ന നടൻ'],['Manju Warrier','മഞ്ജു വാര്യർ','Lead Actress','പ്രശസ്തയായ നായിക'],['Fahadh Faasil','ഫഹദ് ഫാസിൽ','Versatile Performer','വ്യത്യസ്ത കഥാപാത്രങ്ങൾ ചെയ്യുന്ന നടൻ'],['Shobana','ശോഭന','Dancer Star','നർത്തകിയായ പ്രശസ്ത നായിക']]},
  {id:'life',name:'Kerala Life',icon:'🌴',words:[['Chaya Kada','ചായക്കട','Local Gathering Spot','നാട്ടിൻപുറത്തെ കൂടിച്ചേരൽ സ്ഥലം'],['Kallu Shappu','കള്ള് ഷാപ്പ്','Rustic Food Junction','എരിവുള്ള നാടൻ വിഭവങ്ങൾ കിട്ടുന്ന സ്ഥലം'],['KSRTC','കെ എസ് ആർ ടി സി','Public Transportation','സർക്കാർ യാത്രാ സർവീസ്'],['Auto Rickshaw','ഓട്ടോ റിക്ഷ','Three Wheeler Transit','മൂന്നു ചക്ര യാത്രാ വണ്ടി'],['Tharavadu','തറവാട്','Ancestral Home','പഴയകാല കുടുംബ വീട്']]},
  {id:'vehicles',name:'Vehicles',icon:'🚌',words:[['Aanavandi','ആനവണ്ടി','State Transport Ride','സർക്കാറിന്റെ പ്രിയ വണ്ടി'],['Vallam','വള്ളം','Traditional Boat','കായലിലൂടെ സഞ്ചരിക്കുന്നത്'],['Autorickshaw','ഓട്ടോറിക്ഷ','Three Wheeler Taxi','നഗരങ്ങളിലെ വാടക വണ്ടി'],['Bullet','ബുള്ളറ്റ്','Classic Motorcycle','ഗംഭീര ശബ്ദമുള്ള ഇരുചക്ര വാഹനം'],['Houseboat','ഹൗസ്‌ബോട്ട്','Backwater Stay Vessel','കായലിൽ താമസിക്കാവുന്ന ബോട്ട്']]},
  {id:'school',name:'College & School',icon:'🎒',words:[['Kalolsavam','കലോത്സവം','Arts Competition','വിദ്യാർത്ഥികളുടെ കലാമേള'],['Arts Day','ആർട്സ് ഡേ','Campus Cultural Stage','ക്യാമ്പസിലെ ആഘോഷ വേദി'],['College Canteen','കോളേജ് കാന്റീൻ','Student Food Hangout','വിദ്യാർത്ഥികൾ ഭക്ഷണം കഴിക്കുന്ന സ്ഥലം'],['PTA Meeting','പി ടി എ മീറ്റിംഗ്','Parents & Teachers Meet','രക്ഷാകർത്താക്കളുടെയും അധ്യാപകരുടെയും യോഗം'],['Onam Celebration','ഓണാഘോഷം','Campus Festival Day','ക്യാമ്പസിലെ വിശേഷ ആഘോഷം']]},
  {id:'sports',name:'Sports',icon:'⚽',words:[['Football','ഫുട്ബോൾ','Popular Ground Game','മൈതാനത്ത് കളിക്കുന്ന കളി'],['Cricket','ക്രിക്കറ്റ്','Batting & Bowling Game','റൺസ് നേടുന്ന മത്സരം'],['Kabaddi','കബഡി','Team Tag Sport','ശ്വാസം പിടിച്ചു കളിക്കുന്ന മത്സരം'],['Volleyball','വോളിബോൾ','High Net Ball Game','നെറ്റിന് മുകളിലൂടെയുള്ള കളി'],['Vallamkali','വള്ളംകളി','Water Racing Sport','ജലത്തിലെ ആവേശ മത്സരം']]},
  {id:'gulf',name:'Gulf & NRI',icon:'✈️',words:[['Pravasi','പ്രവാസി','Overseas Resident','വിദേശത്ത് ജീവിക്കുന്ന മലയാളി'],['Dubai','ദുബായ്','Middle East Destination','പ്രസിദ്ധമായ ഗൾഫ് നഗരം'],['Gulf Money','ഗൾഫ് മണി','Foreign Earnings Remittance','വിദേശത്തു നിന്നും അയക്കുന്ന സമ്പത്ത്'],['Chakka','ചക്ക','Beloved Home Fruit','നാട്ടിലെ പ്രിയപ്പെട്ട പഴം'],['Naatilekku','നാട്ടിലേക്ക്','Homeward Vacation Journey','അവധിക്ക് വീട്ടിലേക്ക് വരുന്നത്']]}
];

Object.entries(window.extraWords || {}).forEach(([id, words]) => {
  const pack = packs.find(p => p.id === id);
  if (pack) {
    pack.words.push(...words.map(([latin, malayalam, hintLatin, hintMalayalam]) => [
      latin,
      malayalam,
      hintLatin || `Related to ${latin}`,
      hintMalayalam || `ബന്ധപ്പെട്ടത് ${malayalam || latin}`
    ]));
  }
});

if (typeof window !== 'undefined') window.packs = packs;
if (typeof module !== 'undefined' && module.exports) module.exports = { packs };
