import json

output = {}

data = {
  "intl_famous_people": [
    {"civ": "Albert Einstein", "i1": "Marie Curie", "i1m": "മേരി ക്യൂറി", "i2": "Stephen Hawking", "i2m": "സ്റ്റീഫൻ ഹോക്കിംഗ്", "r1e": "Both are legendary physicists who won Nobel Prizes.", "r1m": "ഇരുവരും നൊബേൽ സമ്മാനം നേടിയ പ്രശസ്തരായ ഭൗതികശാസ്ത്രജ്ഞരാണ്.", "r2e": "Both are iconic theoretical physicists.", "r2m": "ഇരുവരും പ്രശസ്തരായ സൈദ്ധാന്തിക ഭൗതികശാസ്ത്രജ്ഞരാണ്."},
    {"civ": "Leonardo da Vinci", "i1": "Vincent van Gogh", "i1m": "വിൻസെന്റ് വാൻ ഗോഗ്", "i2": "Pablo Picasso", "i2m": "പാബ്ലോ പിക്കാസോ", "r1e": "Both are globally recognized legendary European painters.", "r1m": "ഇരുവരും ലോകപ്രശസ്തരായ യൂറോപ്യൻ ചിത്രകാരന്മാരാണ്.", "r2e": "Both revolutionized the world of visual arts.", "r2m": "ഇരുവരും കലാരംഗത്ത് വിപ്ലവം സൃഷ്ടിച്ചവരാണ്."},
    {"civ": "Shakespeare", "i1": "Charles Dickens", "i1m": "ചാൾസ് ഡിക്കൻസ്", "i2": "Jane Austen", "i2m": "ജെയ്ൻ ഓസ്റ്റൺ", "r1e": "Both are foundational figures in classical English literature.", "r1m": "ഇരുവരും ക്ലാസിക്കൽ ഇംഗ്ലീഷ് സാഹിത്യത്തിലെ പ്രധാന വ്യക്തികളാണ്.", "r2e": "Both are renowned English writers with deeply analyzed works.", "r2m": "ഇരുവരും പ്രശസ്തരായ ഇംഗ്ലീഷ് എഴുത്തുകാരാണ്."},
    {"civ": "Napoleon", "i1": "Julius Caesar", "i1m": "ജൂലിയസ് സീസർ", "i2": "Alexander the Great", "i2m": "അലക്സാണ്ടർ ചക്രവർത്തി", "r1e": "Both were powerful military commanders who built vast empires.", "r1m": "ഇരുവരും വലിയ സാമ്രാജ്യങ്ങൾ കെട്ടിപ്പടുത്ത ശക്തരായ സൈനിക മേധാവികളായിരുന്നു.", "r2e": "Both are legendary conquerors from European history.", "r2m": "ഇരുവരും യൂറോപ്യൻ ചരിത്രത്തിലെ പ്രശസ്തരായ പോരാളികളാണ്."},
    {"civ": "Mahatma Gandhi", "i1": "Nelson Mandela", "i1m": "നെൽസൺ മണ്ടേല", "i2": "Martin Luther King Jr.", "i2m": "മാർട്ടിൻ ലൂഥർ കിംഗ്", "r1e": "Both are global icons of peaceful resistance and anti-colonialism.", "r1m": "ഇരുവരും സമാധാനപരമായ ചെറുത്തുനിൽപ്പിന്റെ ലോകപ്രശസ്തരായ പ്രതീകങ്ങളാണ്.", "r2e": "Both fought for civil rights using non-violent methods.", "r2m": "ഇരുവരും അഹിംസയിലൂടെ പൗരാവകാശങ്ങൾക്കായി പോരാടിയവരാണ്."},
    {"civ": "Abraham Lincoln", "i1": "George Washington", "i1m": "ജോർജ്ജ് വാഷിംഗ്ടൺ", "i2": "John F. Kennedy", "i2m": "ജോൺ എഫ് കെന്നഡി", "r1e": "Both are widely revered foundational US Presidents.", "r1m": "ഇരുവരും അമേരിക്കയുടെ പ്രശസ്തരായ പ്രസിഡന്റുമാരാണ്.", "r2e": "Both are famous US Presidents who were tragically assassinated.", "r2m": "ഇരുവരും കൊല്ലപ്പെട്ട പ്രശസ്തരായ അമേരിക്കൻ പ്രസിഡന്റുമാരാണ്."},
    {"civ": "Cleopatra", "i1": "Nefertiti", "i1m": "നെഫെർറ്റിറ്റി", "i2": "Joan of Arc", "i2m": "ജോവാൻ ഓഫ് ആർക്ക്", "r1e": "Both are legendary queens from ancient Egyptian history.", "r1m": "ഇരുവരും പുരാതന ഈജിപ്ഷ്യൻ ചരിത്രത്തിലെ പ്രശസ്തരായ രാജ്ഞിമാരാണ്.", "r2e": "Both are iconic female historical figures who led their nations.", "r2m": "ഇരുവരും തങ്ങളുടെ രാജ്യങ്ങളെ നയിച്ച പ്രശസ്തരായ വനിതകളാണ്."},
    {"civ": "Mozart", "i1": "Beethoven", "i1m": "ബീഥോവൻ", "i2": "Bach", "i2m": "ബാക്ക്", "r1e": "Both are highly celebrated classical music composers.", "r1m": "ഇരുവരും വളരെ പ്രശസ്തരായ ക്ലാസിക്കൽ സംഗീതജ്ഞരാണ്.", "r2e": "Both are legendary composers from the classical era.", "r2m": "ക്ലാസിക്കൽ കാലഘട്ടത്തിലെ പ്രശസ്തരായ സംഗീതജ്ഞരാണ് ഇരുവരും."},
    {"civ": "Nikola Tesla", "i1": "Thomas Edison", "i1m": "തോമസ് എഡിസൺ", "i2": "Alexander Graham Bell", "i2m": "അലക്സാണ്ടർ ഗ്രഹാം ബെൽ", "r1e": "Both are famous inventors associated with early electrical engineering.", "r1m": "ഇരുവരും ആദ്യകാല ഇലക്ട്രിക്കൽ എഞ്ചിനീയറിംഗുമായി ബന്ധപ്പെട്ട പ്രശസ്തരായ കണ്ടുപിടുത്തക്കാരാണ്.", "r2e": "Both made groundbreaking contributions to modern technology.", "r2m": "ഇരുവരും ആധുനിക സാങ്കേതികവിദ്യയ്ക്ക് മികച്ച സംഭാവനകൾ നൽകിയവരാണ്."},
    {"civ": "Sigmund Freud", "i1": "Carl Jung", "i1m": "കാൾ യുങ്", "i2": "Ivan Pavlov", "i2m": "ഇവാൻ പാവ്‌ലോവ്", "r1e": "Both are pioneering figures in the field of psychology and psychoanalysis.", "r1m": "ഇരുവരും മനശാസ്ത്രരംഗത്തെ പ്രശസ്തരായ വ്യക്തികളാണ്.", "r2e": "Both conducted foundational research in human behavior.", "r2m": "ഇരുവരും മനുഷ്യ സ്വഭാവത്തെക്കുറിച്ച് അടിസ്ഥാന ഗവേഷണങ്ങൾ നടത്തിയവരാണ്."},
    {"civ": "Charles Darwin", "i1": "Isaac Newton", "i1m": "ഐസക് ന്യൂട്ടൺ", "i2": "Galileo Galilei", "i2m": "ഗലീലിയോ ഗലീലി", "r1e": "Both are British scientists who fundamentally changed our understanding of nature.", "r1m": "പ്രകൃതിയെക്കുറിച്ചുള്ള നമ്മുടെ ധാരണ മാറ്റിയെഴുതിയ ബ്രിട്ടീഷ് ശാസ്ത്രജ്ഞരാണ് ഇരുവരും.", "r2e": "Both are legendary scientists who challenged historical beliefs.", "r2m": "ചരിത്രപരമായ വിശ്വാസങ്ങളെ ചോദ്യം ചെയ്ത പ്രശസ്തരായ ശാസ്ത്രജ്ഞരാണ് ഇരുവരും."},
    {"civ": "Pablo Picasso", "i1": "Salvador Dalí", "i1m": "സാൽവഡോർ ദാലി", "i2": "Claude Monet", "i2m": "ക്ലോഡ് മോനെറ്റ്", "r1e": "Both are legendary Spanish artists known for surreal and abstract works.", "r1m": "ഇരുവരും വിചിത്രമായ സൃഷ്ടികൾക്ക് പേരുകേട്ട പ്രശസ്തരായ സ്പാനിഷ് കലാകാരന്മാരാണ്.", "r2e": "Both are iconic painters who started major art movements.", "r2m": "പ്രധാനപ്പെട്ട കലാ മുന്നേറ്റങ്ങൾക്ക് തുടക്കം കുറിച്ച പ്രശസ്തരായ ചിത്രകാരന്മാരാണ് ഇരുവരും."},
    {"civ": "Alexander the Great", "i1": "Genghis Khan", "i1m": "ചെങ്കിസ് ഖാൻ", "i2": "Julius Caesar", "i2m": "ജൂലിയസ് സീസർ", "r1e": "Both are ancient conquerors who established massive empires.", "r1m": "വിശാലമായ സാമ്രാജ്യങ്ങൾ സ്ഥാപിച്ച പുരാതന പോരാളികളാണ് ഇരുവരും.", "r2e": "Both are legendary military leaders of antiquity.", "r2m": "ഇരുവരും പുരാതന കാലത്തെ പ്രശസ്തരായ സൈനിക നേതാക്കളാണ്."},
    {"civ": "Martin Luther King", "i1": "Malcolm X", "i1m": "മാൽക്കം എക്സ്", "i2": "Rosa Parks", "i2m": "റോസ പാർക്സ്", "r1e": "Both are prominent leaders of the American civil rights movement.", "r1m": "ഇരുവരും അമേരിക്കൻ പൗരാവകാശ പ്രസ്ഥാനത്തിലെ പ്രമുഖ നേതാക്കളാണ്.", "r2e": "Both are iconic figures who fought against racial discrimination.", "r2m": "വംശീയ വിവേചനത്തിനെതിരെ പോരാടിയ പ്രശസ്തരായ വ്യക്തികളാണ് ഇരുവരും."},
    {"civ": "Stephen Hawking", "i1": "Albert Einstein", "i1m": "ആൽബർട്ട് ഐൻസ്റ്റീൻ", "i2": "Richard Feynman", "i2m": "റിച്ചാർഡ് ഫെയ്ൻമാൻ", "r1e": "Both are legendary theoretical physicists known worldwide.", "r1m": "ഇരുവരും ലോകമെമ്പാടും അറിയപ്പെടുന്ന പ്രശസ്തരായ സൈദ്ധാന്തിക ഭൗതികശാസ്ത്രജ്ഞരാണ്.", "r2e": "Both are modern physicists who popularized complex science.", "r2m": "സങ്കീർണ്ണമായ ശാസ്ത്രത്തെ ജനകീയമാക്കിയ ആധുനിക ഭൗതികശാസ്ത്രജ്ഞരാണ് ഇരുവരും."}
  ],
  "intl_common_objects": [
    {"civ": "Phone", "i1": "Tablet", "i1m": "ടാബ്‌ലെറ്റ്", "i2": "Laptop", "i2m": "ലാപ്‌ടോപ്പ്", "r1e": "Both are touchscreen smart devices used for daily communication.", "r1m": "ദൈനംദിന ആശയവിനിമയത്തിനായി ഉപയോഗിക്കുന്ന സ്മാർട്ട് ഉപകരണങ്ങളാണ് ഇരുവരും.", "r2e": "Both are portable electronic devices used for work and media.", "r2m": "ജോലിക്കും വിനോദത്തിനുമായി ഉപയോഗിക്കുന്ന പോർട്ടബിൾ ഇലക്ട്രോണിക് ഉപകരണങ്ങളാണ് ഇവ."},
    {"civ": "Chair", "i1": "Sofa", "i1m": "സോഫ", "i2": "Stool", "i2m": "സ്റ്റൂൾ", "r1e": "Both are common types of seating furniture found in living rooms.", "r1m": "സ്വീകരണമുറികളിൽ കാണപ്പെടുന്ന ഇരിപ്പിടങ്ങളാണ് ഇവ രണ്ടും.", "r2e": "Both are basic furniture pieces designed for one person to sit on.", "r2m": "ഒരാൾക്ക് ഇരിക്കാൻ രൂപകൽപ്പന ചെയ്ത അടിസ്ഥാന ഫർണിച്ചറുകളാണ് ഇവ."},
    {"civ": "Laptop", "i1": "Desktop Computer", "i1m": "ഡെസ്ക്ടോപ്പ് കമ്പ്യൂട്ടർ", "i2": "Tablet", "i2m": "ടാബ്‌ലെറ്റ്", "r1e": "Both are primary computing devices used for daily work and browsing.", "r1m": "ദൈനംദിന ജോലികൾക്കായി ഉപയോഗിക്കുന്ന പ്രധാന കമ്പ്യൂട്ടിംഗ് ഉപകരണങ്ങളാണ് ഇവ.", "r2e": "Both are portable computing devices with screens.", "r2m": "സ്ക്രീനുള്ള പോർട്ടബിൾ കമ്പ്യൂട്ടിംഗ് ഉപകരണങ്ങളാണ് ഇവ രണ്ടും."},
    {"civ": "Umbrella", "i1": "Raincoat", "i1m": "റെയിൻകോട്ട്", "i2": "Parasol", "i2m": "പാരാസോൾ", "r1e": "Both are essential items used specifically for protection against rain.", "r1m": "മഴയിൽ നിന്ന് സംരക്ഷണം നേടാൻ ഉപയോഗിക്കുന്ന അവശ്യവസ്തുക്കളാണ് ഇവ.", "r2e": "Both are portable canopies used for protection against weather.", "r2m": "കാലാവസ്ഥയിൽ നിന്ന് സംരക്ഷണം നൽകുന്ന ഉപകരണങ്ങളാണ് ഇവ രണ്ടും."},
    {"civ": "Toothbrush", "i1": "Toothpaste", "i1m": "ടൂത്ത് പേസ്റ്റ്", "i2": "Floss", "i2m": "ഫ്ലോസ്", "r1e": "Both are essential daily items used directly for dental hygiene.", "r1m": "ദന്ത ശുചിത്വത്തിനായി ഉപയോഗിക്കുന്ന അവശ്യ ദൈനംദിന വസ്തുക്കളാണ് ഇവ.", "r2e": "Both are necessary tools used for cleaning teeth.", "r2m": "പല്ല് വൃത്തിയാക്കാൻ ഉപയോഗിക്കുന്ന അത്യാവശ്യ ഉപകരണങ്ങളാണ് ഇവ."},
    {"civ": "Clock", "i1": "Watch", "i1m": "വാച്ച്", "i2": "Hourglass", "i2m": "മണൽഘടികാരം", "r1e": "Both are common devices specifically designed to tell the time.", "r1m": "സമയം അറിയാൻ പ്രത്യേകം രൂപകൽപ്പന ചെയ്ത സാധാരണ ഉപകരണങ്ങളാണ് ഇവ.", "r2e": "Both are traditional timekeeping devices.", "r2m": "പരമ്പരാഗതമായി സമയം അളക്കാൻ ഉപയോഗിക്കുന്ന ഉപകരണങ്ങളാണ് ഇവ രണ്ടും."},
    {"civ": "Mirror", "i1": "Window", "i1m": "ജനൽ", "i2": "Glass", "i2m": "ഗ്ലാസ്", "r1e": "Both are common household installations made of clear or reflective glass.", "r1m": "ഗ്ലാസ് കൊണ്ട് നിർമ്മിച്ച വീട്ടുപകരണങ്ങളാണ് ഇവ രണ്ടും.", "r2e": "Both are fragile glass objects found in bathrooms and bedrooms.", "r2m": "ബാത്ത്റൂമുകളിലും കിടപ്പുമുറികളിലും കാണപ്പെടുന്ന ഗ്ലാസ് വസ്തുക്കളാണ് ഇവ."},
    {"civ": "Pillow", "i1": "Blanket", "i1m": "പുതപ്പ്", "i2": "Cushion", "i2m": "കുഷ്യൻ", "r1e": "Both are soft bedding items essential for a comfortable sleep.", "r1m": "സുഖപ്രദമായ ഉറക്കത്തിന് ആവശ്യമായ മൃദുവായ കിടക്ക ഉപകരണങ്ങളാണ് ഇവ.", "r2e": "Both are soft, stuffed items placed on furniture for comfort.", "r2m": "സൗകര്യത്തിനായി ഫർണിച്ചറുകളിൽ ഉപയോഗിക്കുന്ന മൃദുവായ വസ്തുക്കളാണ് ഇവ."},
    {"civ": "Key", "i1": "Lock", "i1m": "പൂട്ട്", "i2": "Padlock", "i2m": "പാഡ്‌ലോക്ക്", "r1e": "Both are essential metal components of a typical security mechanism.", "r1m": "സുരക്ഷാ സംവിധാനത്തിന്റെ അത്യാവശ്യ ലോഹ ഭാഗങ്ങളാണ് ഇവ.", "r2e": "Both are hardware items used to secure doors and boxes.", "r2m": "വാതിലുകളും പെട്ടികളും സുരക്ഷിതമാക്കാൻ ഉപയോഗിക്കുന്ന വസ്തുക്കളാണ് ഇവ."},
    {"civ": "Pen", "i1": "Pencil", "i1m": "പെൻസിൽ", "i2": "Marker", "i2m": "മാർക്കർ", "r1e": "Both are basic handheld writing instruments used every day in schools and offices.", "r1m": "സ്കൂളുകളിലും ഓഫീസുകളിലും ഉപയോഗിക്കുന്ന അടിസ്ഥാന എഴുത്തുപകരണങ്ങളാണ് ഇവ.", "r2e": "Both are common stationery items used for drawing or writing.", "r2m": "എഴുതാനും വരയ്ക്കാനും ഉപയോഗിക്കുന്ന സാധാരണ സ്റ്റേഷനറി വസ്തുക്കളാണ് ഇവ."},
    {"civ": "Book", "i1": "Notebook", "i1m": "നോട്ട്ബുക്ക്", "i2": "Magazine", "i2m": "മാസിക", "r1e": "Both are bound collections of paper pages used for reading or writing.", "r1m": "വായിക്കാനോ എഴുതാനോ ഉപയോഗിക്കുന്ന കടലാസ് താളുകളുടെ ശേഖരങ്ങളാണ് ഇവ.", "r2e": "Both are common printed reading materials.", "r2m": "സാധാരണയായി അച്ചടിച്ച വായനാ സാമഗ്രികളാണ് ഇവ രണ്ടും."},
    {"civ": "Glasses", "i1": "Contact Lens", "i1m": "കോൺടാക്റ്റ് ലെൻസ്", "i2": "Sunglasses", "i2m": "സൺഗ്ലാസ്സ്", "r1e": "Both are common optical items worn to correct or protect vision.", "r1m": "കാഴ്ച ശരിയാക്കാനോ സംരക്ഷിക്കാനോ ധരിക്കുന്ന വസ്തുക്കളാണ് ഇവ.", "r2e": "Both are wearable items placed over the eyes.", "r2m": "കണ്ണുകൾക്ക് മുകളിൽ ധരിക്കുന്ന ഉപകരണങ്ങളാണ് ഇവ രണ്ടും."},
    {"civ": "Wallet", "i1": "Purse", "i1m": "പേഴ്സ്", "i2": "Backpack", "i2m": "ബാക്ക്പാക്ക്", "r1e": "Both are common personal accessories used for carrying money and cards.", "r1m": "പണവും കാർഡുകളും കൊണ്ടുപോകാൻ ഉപയോഗിക്കുന്ന വ്യക്തിഗത സാധനങ്ങളാണ് ഇവ.", "r2e": "Both are daily carry items designed to hold personal belongings.", "r2m": "വ്യക്തിപരമായ സാധനങ്ങൾ സൂക്ഷിക്കാൻ ഉപയോഗിക്കുന്ന വസ്തുക്കളാണ് ഇവ."},
    {"civ": "Fork", "i1": "Spoon", "i1m": "സ്പൂൺ", "i2": "Knife", "i2m": "കത്തി", "r1e": "Both are standard metal dining utensils used for eating meals.", "r1m": "ഭക്ഷണം കഴിക്കാൻ ഉപയോഗിക്കുന്ന സാധാരണ ലോഹ ഉപകരണങ്ങളാണ് ഇവ.", "r2e": "Both are common pieces of cutlery found in any kitchen.", "r2m": "ഏതൊരു അടുക്കളയിലും കാണപ്പെടുന്ന സാധാരണ ഉപകരണങ്ങളാണ് ഇവ."},
    {"civ": "Candle", "i1": "Torch", "i1m": "ടോർച്ച്", "i2": "Lantern", "i2m": "റാന്തൽ", "r1e": "Both are common portable sources of light used during power outages.", "r1m": "വൈദ്യുതി തടസ്സങ്ങളിൽ ഉപയോഗിക്കുന്ന സാധാരണ പോർട്ടബിൾ വെളിച്ച സ്രോതസ്സുകളാണ് ഇവ.", "r2e": "Both are traditional tools used to illuminate dark spaces.", "r2m": "ഇരുണ്ട ഇടങ്ങൾ പ്രകാശിപ്പിക്കാൻ ഉപയോഗിക്കുന്ന പരമ്പരാഗത ഉപകരണങ്ങളാണ് ഇവ."}
  ],
  "intl_nature": [
    {"civ": "Ocean", "i1": "Sea", "i1m": "കടൽ", "i2": "Lake", "i2m": "തടാകം", "r1e": "Both are massive, naturally occurring bodies of saltwater.", "r1m": "ഭൂമിയിലെ വലിയ പ്രകൃതിദത്ത ഉപ്പുവെള്ള ശേഖരങ്ങളാണ് ഇവ രണ്ടും.", "r2e": "Both are large natural bodies of water.", "r2m": "വലിയ പ്രകൃതിദത്ത ജലാശയങ്ങളാണ് ഇവ രണ്ടും."},
    {"civ": "Forest", "i1": "Jungle", "i1m": "കാട്", "i2": "Woods", "i2m": "മരക്കൂട്ടം", "r1e": "Both are large natural ecosystems dominated by dense trees.", "r1m": "ഇടതൂർന്ന മരങ്ങളുള്ള വലിയ പ്രകൃതിദത്ത ആവാസവ്യവസ്ഥകളാണ് ഇവ.", "r2e": "Both are natural environments filled with vegetation and wildlife.", "r2m": "സസ്യജാലങ്ങളും വന്യജീവികളും നിറഞ്ഞ പ്രകൃതിദത്ത പരിതസ്ഥിതികളാണ് ഇവ."},
    {"civ": "Mountain", "i1": "Hill", "i1m": "കുന്ന്", "i2": "Volcano", "i2m": "അഗ്നിപർവ്വതം", "r1e": "Both are significant natural elevations of the earth's surface.", "r1m": "ഭൂപ്രതലത്തിലെ വലിയ പ്രകൃതിദത്ത ഉയരങ്ങളാണ് ഇവ രണ്ടും.", "r2e": "Both are prominent geological formations rising above the landscape.", "r2m": "ഭൂപ്രകൃതിക്ക് മുകളിൽ ഉയർന്നുനിൽക്കുന്ന ഭൗമശാസ്ത്രപരമായ രൂപങ്ങളാണിവ."},
    {"civ": "River", "i1": "Lake", "i1m": "തടാകം", "i2": "Stream", "i2m": "അരുവി", "r1e": "Both are major natural freshwater bodies found across continents.", "r1m": "ഭൂഖണ്ഡങ്ങളിലുടനീളം കാണപ്പെടുന്ന പ്രധാന പ്രകൃതിദത്ത ശുദ്ധജല സ്രോതസ്സുകളാണ് ഇവ.", "r2e": "Both are flowing natural watercourses.", "r2m": "പ്രകൃതിദത്തമായി ഒഴുകുന്ന ജലപാതകളാണിവ."},
    {"civ": "Desert", "i1": "Savanna", "i1m": "സവന്ന", "i2": "Tundra", "i2m": "തുണ്ട്ര", "r1e": "Both are massive natural biomes known for extremely harsh climates.", "r1m": "കഠിനമായ കാലാവസ്ഥയ്ക്ക് പേരുകേട്ട വലിയ പ്രകൃതിദത്ത പ്രദേശങ്ങളാണിവ.", "r2e": "Both are barren landscapes with very little rainfall.", "r2m": "വളരെ കുറഞ്ഞ മഴ ലഭിക്കുന്ന വരണ്ട പ്രദേശങ്ങളാണിവ."},
    {"civ": "Volcano", "i1": "Earthquake", "i1m": "ഭൂകമ്പം", "i2": "Geyser", "i2m": "ഉഷ്ണനീരുറവ", "r1e": "Both are powerful geological phenomena originating from beneath the earth's crust.", "r1m": "ഭൂമിയുടെ അടിയിൽ നിന്ന് ഉണ്ടാകുന്ന ശക്തമായ ഭൗമ പ്രതിഭാസങ്ങളാണിവ.", "r2e": "Both are natural features associated with geothermal activity.", "r2m": "ഭൂമിയുടെ താപവുമായി ബന്ധപ്പെട്ട പ്രകൃതിദത്ത സവിശേഷതകളാണിവ."},
    {"civ": "Rainbow", "i1": "Aurora", "i1m": "അറോറ", "i2": "Eclipse", "i2m": "ഗ്രഹണം", "r1e": "Both are spectacular atmospheric optical phenomena in the sky.", "r1m": "ആകാശത്തെ മനോഹരമായ പ്രകൃതിദത്ത ഒപ്റ്റിക്കൽ പ്രതിഭാസങ്ങളാണിവ.", "r2e": "Both are colorful visual events occurring in the atmosphere.", "r2m": "അന്തരീക്ഷത്തിൽ സംഭവിക്കുന്ന വർണ്ണാഭമായ കാഴ്ചകളാണിവ."},
    {"civ": "Storm", "i1": "Hurricane", "i1m": "ചുഴലിക്കാറ്റ്", "i2": "Tornado", "i2m": "ടൊർണാഡോ", "r1e": "Both are intense and destructive meteorological weather events.", "r1m": "തീവ്രവും വിനാശകരവുമായ കാലാവസ്ഥാ പ്രതിഭാസങ്ങളാണിവ.", "r2e": "Both are severe weather systems with strong winds.", "r2m": "ശക്തമായ കാറ്റുള്ള കഠിനമായ കാലാവസ്ഥാ സംവിധാനങ്ങളാണിവ."},
    {"civ": "Coral Reef", "i1": "Kelp Forest", "i1m": "കെൽപ്പ് വനം", "i2": "Mangrove", "i2m": "കണ്ടൽക്കാട്", "r1e": "Both are extremely diverse and vibrant underwater ecosystems.", "r1m": "വളരെ വൈവിധ്യമാർന്ന സജീവമായ വെള്ളത്തിനടിയിലെ ആവാസവ്യവസ്ഥകളാണിവ.", "r2e": "Both are vital marine habitats supporting oceanic life.", "r2m": "സമുദ്രജീവികളെ പിന്തുണയ്ക്കുന്ന പ്രധാന സമുദ്ര ആവാസവ്യവസ്ഥകളാണിവ."},
    {"civ": "Waterfall", "i1": "Geyser", "i1m": "ഉഷ്ണനീരുറവ", "i2": "River", "i2m": "നദി", "r1e": "Both are dynamic natural water features involving fast-moving water.", "r1m": "വേഗത്തിൽ ചലിക്കുന്ന ജലമുള്ള ചലനാത്മക പ്രകൃതിദത്ത സവിശേഷതകളാണിവ.", "r2e": "Both are beautiful geological features involving falling or erupting water.", "r2m": "വെള്ളം ഒഴുകുകയോ പൊട്ടിത്തെറിക്കുകയോ ചെയ്യുന്ന മനോഹരമായ ഭൗമ സവിശേഷതകളാണിവ."},
    {"civ": "Glacier", "i1": "Iceberg", "i1m": "മഞ്ഞുമല", "i2": "Snow", "i2m": "മഞ്ഞ്", "r1e": "Both are massive, naturally occurring formations made entirely of ice.", "r1m": "പൂർണ്ണമായും മഞ്ഞുകൊണ്ട് നിർമ്മിച്ച വലിയ പ്രകൃതിദത്ത രൂപങ്ങളാണിവ.", "r2e": "Both are large frozen geographical features found in polar regions.", "r2m": "ധ്രുവപ്രദേശങ്ങളിൽ കാണപ്പെടുന്ന വലിയ മരവിച്ച ഭൂമിശാസ്ത്രപരമായ സവിശേഷതകളാണിവ."},
    {"civ": "Canyon", "i1": "Gorge", "i1m": "ചെരിവ്", "i2": "Valley", "i2m": "താഴ്വര", "r1e": "Both are deep, steep-sided natural geographical landforms carved by water.", "r1m": "ജലം സൃഷ്ടിച്ച ആഴമേറിയതും ചെങ്കുത്തായതുമായ പ്രകൃതിദത്ത ഭൂപ്രകൃതികളാണിവ.", "r2e": "Both are large depressions in the earth's surface.", "r2m": "ഭൂപ്രതലത്തിലെ വലിയ കുഴികളാണിവ."},
    {"civ": "Meadow", "i1": "Prairie", "i1m": "പുൽമേട്", "i2": "Pasture", "i2m": "മേച്ചിൽപ്പുറം", "r1e": "Both are large, open natural landscapes dominated by grass.", "r1m": "പുല്ലുകൾ നിറഞ്ഞ വലിയ തുറസ്സായ പ്രകൃതിദത്ത പ്രദേശങ്ങളാണിവ.", "r2e": "Both are flat, grassy ecological areas.", "r2m": "പരന്ന, പുല്ലുള്ള പാരിസ്ഥിതിക പ്രദേശങ്ങളാണിവ."},
    {"civ": "Cave", "i1": "Cavern", "i1m": "ഗുഹ", "i2": "Tunnel", "i2m": "തുരങ്കം", "r1e": "Both are large, dark natural underground cavities or chambers.", "r1m": "വലിയ, ഇരുണ്ട പ്രകൃതിദത്ത ഭൂഗർഭ അറകളാണിവ.", "r2e": "Both are deep rocky hollows found in mountains or underground.", "r2m": "പർവ്വതങ്ങളിലോ ഭൂമിക്കടിയിലോ കാണപ്പെടുന്ന ആഴത്തിലുള്ള പാറകളുള്ള കുഴികളാണിവ."},
    {"civ": "Swamp", "i1": "Marsh", "i1m": "ചതുപ്പ്", "i2": "Bog", "i2m": "ചതുപ്പുനിലം", "r1e": "Both are dense, natural wetland ecosystems rich in biodiversity.", "r1m": "ജൈവവൈവിധ്യത്താൽ സമ്പന്നമായ ഇടതൂർന്ന പ്രകൃതിദത്ത തണ്ണീർത്തട ആവാസവ്യവസ്ഥകളാണിവ.", "r2e": "Both are muddy, waterlogged natural areas.", "r2m": "ചെളി നിറഞ്ഞ, വെള്ളം കെട്ടിനിൽക്കുന്ന പ്രകൃതിദത്ത പ്രദേശങ്ങളാണിവ."}
  ],
  "intl_disney": [
    {"civ": "Simba", "i1": "Mufasa", "i1m": "മുഫാസ", "i2": "Scar", "i2m": "സ്കാർ", "r1e": "Both are iconic main lion characters from the Disney movie The Lion King.", "r1m": "ദി ലയൺ കിംഗ് എന്ന ഡിസ്നി സിനിമയിലെ പ്രധാന സിംഹ കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are royalty in the Pride Lands from The Lion King.", "r2m": "ദി ലയൺ കിംഗ് സിനിമയിലെ പ്രധാന രാജകീയ കഥാപാത്രങ്ങളാണ് ഇവർ."},
    {"civ": "Elsa", "i1": "Anna", "i1m": "അന്ന", "i2": "Olaf", "i2m": "ഒലാഫ്", "r1e": "Both are central royal characters from the popular Disney movie Frozen.", "r1m": "ഫ്രോസൺ എന്ന പ്രശസ്തമായ ഡിസ്നി സിനിമയിലെ പ്രധാന രാജകീയ കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are major Disney figures associated with winter and ice.", "r2m": "ശൈത്യകാലവും മഞ്ഞുമായി ബന്ധപ്പെട്ട പ്രധാന ഡിസ്നി കഥാപാത്രങ്ങളാണ് ഇവർ."},
    {"civ": "Moana", "i1": "Maui", "i1m": "മൗയി", "i2": "Ariel", "i2m": "ഏരിയൽ", "r1e": "Both are lead characters in a Disney movie closely tied to the ocean.", "r1m": "സമുദ്രവുമായി അടുത്ത ബന്ധമുള്ള ഡിസ്നി സിനിമയിലെ പ്രധാന കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are iconic Polynesian-inspired Disney characters.", "r2m": "പ്രശസ്തരായ പോളിനേഷ്യൻ ഡിസ്നി കഥാപാത്രങ്ങളാണ് ഇവർ."},
    {"civ": "Mulan", "i1": "Pocahontas", "i1m": "പോക്കഹോണ്ടാസ്", "i2": "Jasmine", "i2m": "ജാസ്മിൻ", "r1e": "Both are brave, culturally iconic Disney heroines who saved their people.", "r1m": "തങ്ങളുടെ ആളുകളെ രക്ഷിച്ച ധീരരായ ഡിസ്നി നായികമാരാണ് ഇരുവരും.", "r2e": "Both are legendary strong female warriors in Disney animation.", "r2m": "ഡിസ്നി അനിമേഷനിലെ ശക്തരായ വനിതാ പോരാളികളാണ് ഇവർ."},
    {"civ": "Aladdin", "i1": "Genie", "i1m": "ജീനി", "i2": "Jafar", "i2m": "ജാഫർ", "r1e": "Both are the most central iconic characters from the Disney movie Aladdin.", "r1m": "അലാഡിൻ എന്ന ഡിസ്നി സിനിമയിലെ ഏറ്റവും പ്രധാനപ്പെട്ട കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are key characters from the fictional city of Agrabah.", "r2m": "അഗ്രാബ എന്ന സാങ്കൽപ്പിക നഗരത്തിലെ പ്രധാന കഥാപാത്രങ്ങളാണ് ഇവർ."},
    {"civ": "Shrek", "i1": "Donkey", "i1m": "ഡോങ്കി", "i2": "Fiona", "i2m": "ഫിയോണ", "r1e": "Both are the most iconic, hilarious main characters from the DreamWorks Shrek series.", "r1m": "ഷ്രെക്ക് പരമ്പരയിലെ ഏറ്റവും പ്രശസ്തവും രസകരവുമായ പ്രധാന കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are non-human animated heroes from famous fairy tale movies.", "r2m": "പ്രശസ്തമായ സിനിമകളിലെ അമാനുഷികരായ ആനിമേറ്റഡ് നായകന്മാരാണ് ഇവർ."},
    {"civ": "Woody", "i1": "Buzz Lightyear", "i1m": "ബസ് ലൈറ്റ്ഇയർ", "i2": "Jessie", "i2m": "ജെസ്സി", "r1e": "Both are the famous leading toy characters in Pixar's Toy Story franchise.", "r1m": "പിക്സാറിന്റെ ടോയ് സ്റ്റോറി പരമ്പരയിലെ പ്രശസ്തരായ കളിപ്പാട്ട കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are classic animated action figures from Toy Story.", "r2m": "ടോയ് സ്റ്റോറിയിലെ ക്ലാസിക് ആനിമേറ്റഡ് കളിപ്പാട്ടങ്ങളാണിവർ."},
    {"civ": "Nemo", "i1": "Marlin", "i1m": "മാർലിൻ", "i2": "Dory", "i2m": "ഡോറി", "r1e": "Both are central clownfish characters in a massive Pixar ocean adventure.", "r1m": "പിക്സാറിന്റെ സമുദ്ര സാഹസിക സിനിമയിലെ പ്രധാന ക്ലൗൺഫിഷ് കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are famous animated fish from finding Nemo.", "r2m": "ഫൈൻഡിംഗ് നീമോയിലെ പ്രശസ്തരായ മത്സ്യ കഥാപാത്രങ്ങളാണിവർ."},
    {"civ": "Rapunzel", "i1": "Flynn Rider", "i1m": "ഫ്ലിൻ റൈഡർ", "i2": "Mother Gothel", "i2m": "മദർ ഗൊഥെൽ", "r1e": "Both are the iconic lead characters in the Disney movie Tangled.", "r1m": "ടാങ്കിൾഡ് എന്ന ഡിസ്നി സിനിമയിലെ പ്രശസ്തരായ പ്രധാന കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are central figures in a modern Disney fairy tale adaptation.", "r2m": "ഒരു ആധുനിക ഡിസ്നി സിനിമയിലെ പ്രധാന കഥാപാത്രങ്ങളാണിവർ."},
    {"civ": "Belle", "i1": "Beast", "i1m": "ബീസ്റ്റ്", "i2": "Gaston", "i2m": "ഗാസ്റ്റൺ", "r1e": "Both are the absolute core characters of Disney's Beauty and the Beast.", "r1m": "ഡിസ്നിയുടെ ബ്യൂട്ടി ആൻഡ് ദി ബീസ്റ്റിലെ പ്രധാന കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are classic figures from a famous French-inspired Disney story.", "r2m": "പ്രശസ്തമായ ഒരു ഫ്രഞ്ച് ഡിസ്നി കഥയിലെ ക്ലാസിക് കഥാപാത്രങ്ങളാണിവർ."},
    {"civ": "Cinderella", "i1": "Snow White", "i1m": "സ്നോ വൈറ്റ്", "i2": "Aurora", "i2m": "അറോറ", "r1e": "Both are foundational, classic original Disney princesses with famous stories.", "r1m": "പ്രശസ്തമായ കഥകളുള്ള ക്ലാസിക് ഡിസ്നി രാജകുമാരിമാരാണ് ഇരുവരും.", "r2e": "Both are iconic Disney royalty who suffer under evil stepmothers.", "r2m": "ദുഷ്ടയായ രണ്ടാനമ്മയുടെ കീഴിൽ കഷ്ടപ്പെടുന്ന പ്രശസ്ത ഡിസ്നി രാജകുമാരിമാരാണ് ഇവർ."},
    {"civ": "Bambi", "i1": "Dumbo", "i1m": "ഡംബോ", "i2": "Thumper", "i2m": "തമ്പർ", "r1e": "Both are extremely famous, beloved classic Disney animal protagonists.", "r1m": "വളരെ പ്രശസ്തരായ, പ്രിയപ്പെട്ട ക്ലാസിക് ഡിസ്നി മൃഗ കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are titular young animal heroes of vintage Disney animation.", "r2m": "പഴയ ഡിസ്നി ആനിമേഷനിലെ യുവ മൃഗ നായകന്മാരാണ് ഇവർ."},
    {"civ": "Pinocchio", "i1": "Jiminy Cricket", "i1m": "ജിമിനി ക്രിക്കറ്റ്", "i2": "Geppetto", "i2m": "ജെപ്പറ്റോ", "r1e": "Both are the most central, inseparable characters in the Disney classic Pinocchio.", "r1m": "പിനോച്ചിയോ എന്ന ഡിസ്നി ക്ലാസിക്കിലെ ഏറ്റവും പ്രധാനപ്പെട്ട കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are iconic figures from an early classic Disney moral tale.", "r2m": "ആദ്യകാല ഡിസ്നി കഥയിലെ പ്രശസ്തരായ കഥാപാത്രങ്ങളാണിവർ."},
    {"civ": "Tarzan", "i1": "Jane", "i1m": "ജെയ്ൻ", "i2": "Kerchak", "i2m": "കെർചാക്", "r1e": "Both are the legendary main characters from Disney's jungle adventure Tarzan.", "r1m": "ഡിസ്നിയുടെ ടാർസൻ എന്ന ജംഗിൾ സാഹസിക സിനിമയിലെ പ്രധാന കഥാപാത്രങ്ങളാണ് ഇരുവരും.", "r2e": "Both are iconic humans who adapt to the African jungle in Disney.", "r2m": "ആഫ്രിക്കൻ കാടുകളുമായി പൊരുത്തപ്പെടുന്ന പ്രശസ്തരായ മനുഷ്യ കഥാപാത്രങ്ങളാണിവർ."},
    {"civ": "Stitch", "i1": "Lilo", "i1m": "ലിലോ", "i2": "Jumba", "i2m": "ജുംബ", "r1e": "Both are the iconic duo from a famous Hawaiian Disney animated movie.", "r1m": "പ്രശസ്തമായ ഒരു ഹവായിയൻ ഡിസ്നി ആനിമേറ്റഡ് സിനിമയിലെ ജോഡികളാണ് ഇരുവരും.", "r2e": "Both are central misunderstood characters in a modern Disney sci-fi film.", "r2m": "ഒരു ആധുനിക ഡിസ്നി സിനിമയിലെ തെറ്റിദ്ധരിക്കപ്പെട്ട പ്രധാന കഥാപാത്രങ്ങളാണിവർ."}
  ],
  "intl_places": [
    {"civ": "Eiffel Tower", "i1": "Big Ben", "i1m": "ബിഗ് ബെൻ", "i2": "Statue of Liberty", "i2m": "സ്റ്റാച്യു ഓഫ് ലിബർട്ടി", "r1e": "Both are globally recognized, massive iconic architectural monuments in Europe.", "r1m": "യൂറോപ്പിലെ ലോകപ്രശസ്തമായ വലിയ വാസ്തുവിദ്യാ സ്മാരകങ്ങളാണ് ഇരുവരും.", "r2e": "Both are famous towering metal structures built as national symbols.", "r2m": "ദേശീയ ചിഹ്നങ്ങളായി നിർമ്മിച്ച പ്രശസ്തമായ വലിയ ലോഹ ഘടനകളാണിവ."},
    {"civ": "Colosseum", "i1": "Pantheon", "i1m": "പന്തിയോൺ", "i2": "Parthenon", "i2m": "പാർഥെനോൺ", "r1e": "Both are incredibly famous, surviving massive structures from Ancient Rome.", "r1m": "പുരാതന റോമിൽ നിന്നുള്ള അവശേഷിക്കുന്ന വളരെ പ്രശസ്തമായ വലിയ ഘടനകളാണിവ.", "r2e": "Both are legendary classical stone monuments in modern Italy.", "r2m": "ആധുനിക ഇറ്റലിയിലെ പ്രശസ്തമായ ക്ലാസിക്കൽ കൽസ്മാരകങ്ങളാണിവ."},
    {"civ": "Taj Mahal", "i1": "Qutub Minar", "i1m": "കുത്തബ് മിനാർ", "i2": "Red Fort", "i2m": "ചെങ്കോട്ട", "r1e": "Both are legendary, globally recognized historical monuments in India.", "r1m": "ഇന്ത്യയിലെ ലോകപ്രശസ്തമായ ചരിത്ര സ്മാരകങ്ങളാണ് ഇരുവരും.", "r2e": "Both are massive iconic structures built by ancient Indian empires.", "r2m": "പുരാതന ഇന്ത്യൻ സാമ്രാജ്യങ്ങൾ നിർമ്മിച്ച വലിയ പ്രശസ്തമായ ഘടനകളാണിവ."},
    {"civ": "Great Wall", "i1": "Forbidden City", "i1m": "വിലക്കപ്പെട്ട നഗരം", "i2": "Terracotta Army", "i2m": "ടെറാക്കോട്ട സൈന്യം", "r1e": "Both are massive, historically critical UNESCO World Heritage sites in China.", "r1m": "ചൈനയിലെ ചരിത്രപരമായി വളരെ പ്രധാനപ്പെട്ട യുനെസ്കോ ലോക പൈതൃക കേന്ദ്രങ്ങളാണിവ.", "r2e": "Both are legendary ancient mega-projects built by Chinese emperors.", "r2m": "ചൈനീസ് ചക്രവർത്തിമാർ നിർമ്മിച്ച പ്രശസ്തമായ പുരാതന നിർമ്മാണങ്ങളാണിവ."},
    {"civ": "Statue of Liberty", "i1": "Golden Gate Bridge", "i1m": "ഗോൾഡൻ ഗേറ്റ് ബ്രിഡ്ജ്", "i2": "Mount Rushmore", "i2m": "മൗണ്ട് റഷ്മോർ", "r1e": "Both are incredibly famous, colossal national landmarks in the United States.", "r1m": "അമേരിക്കൻ ഐക്യനാടുകളിലെ വളരെ പ്രശസ്തമായ വലിയ ദേശീയ സ്മാരകങ്ങളാണിവ.", "r2e": "Both are iconic American monumental structures recognized worldwide.", "r2m": "ലോകമെമ്പാടും അംഗീകരിക്കപ്പെട്ട പ്രശസ്തമായ അമേരിക്കൻ ഘടനകളാണിവ."},
    {"civ": "Sydney Opera House", "i1": "Harbour Bridge", "i1m": "ഹാർബർ ബ്രിഡ്ജ്", "i2": "Burj Khalifa", "i2m": "ബുർജ് ഖലീഫ", "r1e": "Both are the most iconic, globally recognized structural landmarks of Sydney.", "r1m": "സിഡ്നിയിലെ ലോകപ്രശസ്തമായ വാസ്തുവിദ്യാ സ്മാരകങ്ങളാണ് ഇവ രണ്ടും.", "r2e": "Both are famous modern architectural wonders.", "r2m": "പ്രശസ്തമായ ആധുനിക വാസ്തുവിദ്യാ വിസ്മയങ്ങളാണിവ."},
    {"civ": "Machu Picchu", "i1": "Chichen Itza", "i1m": "ചിച്ചെൻ ഇറ്റ്സ", "i2": "Petra", "i2m": "പെട്ര", "r1e": "Both are legendary, extremely well-preserved ancient ruins in Latin America.", "r1m": "ലാറ്റിനമേരിക്കയിലെ വളരെ നന്നായി സംരക്ഷിക്കപ്പെട്ടിട്ടുള്ള പുരാതന അവശിഷ്ടങ്ങളാണിവ.", "r2e": "Both are iconic stone cities built by ancient civilizations.", "r2m": "പുരാതന നാഗരികതകൾ നിർമ്മിച്ച പ്രശസ്തമായ കൽ നഗരങ്ങളാണിവ."},
    {"civ": "Stonehenge", "i1": "Avebury", "i1m": "ഏവ്ബറി", "i2": "Easter Island", "i2m": "ഈസ്റ്റർ ദ്വീപ്", "r1e": "Both are mysterious, globally famous ancient megalithic stone monuments.", "r1m": "നിഗൂഢവും ലോകപ്രശസ്തവുമായ പുരാതന കൽസ്മാരകങ്ങളാണിവ.", "r2e": "Both are iconic prehistoric circles of standing stones in England.", "r2m": "ഇംഗ്ലണ്ടിലെ പ്രശസ്തമായ ചരിത്രാതീത ശിലാ വൃത്തങ്ങളാണിവ."},
    {"civ": "Niagara Falls", "i1": "Victoria Falls", "i1m": "വിക്ടോറിയ വെള്ളച്ചാട്ടം", "i2": "Angel Falls", "i2m": "ഏഞ്ചൽ വെള്ളച്ചാട്ടം", "r1e": "Both are incredibly famous, massive, spectacular international waterfalls.", "r1m": "വളരെ പ്രശസ്തവും വലുതുമായ അന്താരാഷ്ട്ര വെള്ളച്ചാട്ടങ്ങളാണിവ.", "r2e": "Both are gigantic natural water wonders that border two countries.", "r2m": "രണ്ട് രാജ്യങ്ങളുടെ അതിർത്തിയിലുള്ള വലിയ പ്രകൃതിദത്ത ജല വിസ്മയങ്ങളാണിവ."},
    {"civ": "Angkor Wat", "i1": "Borobudur", "i1m": "ബോറോബുദൂർ", "i2": "Prambanan", "i2m": "പ്രമ്പാനൻ", "r1e": "Both are massive, historically profound ancient temple complexes in Southeast Asia.", "r1m": "തെക്കുകിഴക്കൻ ഏഷ്യയിലെ വലിയതും ചരിത്രപരമായി പ്രധാനപ്പെട്ടതുമായ പുരാതന ക്ഷേത്ര സമുച്ചയങ്ങളാണിവ.", "r2e": "Both are legendary religious stone monuments.", "r2m": "പ്രശസ്തമായ മതപരമായ കൽസ്മാരകങ്ങളാണിവ."},
    {"civ": "Alhambra", "i1": "Sagrada Familia", "i1m": "സഗ്രാഡ ഫാമിലിയ", "i2": "Taj Mahal", "i2m": "താജ് മഹൽ", "r1e": "Both are profoundly famous, iconic architectural masterpieces located in Spain.", "r1m": "സ്പെയിനിലെ വളരെ പ്രശസ്തമായ വാസ്തുവിദ്യാ വിസ്മയങ്ങളാണിവ.", "r2e": "Both are legendary monumental buildings heavily visited by tourists.", "r2m": "വിനോദസഞ്ചാരികൾ ധാരാളമായി സന്ദർശിക്കുന്ന പ്രശസ്തമായ വലിയ കെട്ടിടങ്ങളാണിവ."},
    {"civ": "Mount Everest", "i1": "K2", "i1m": "കെ2", "i2": "Mount Kilimanjaro", "i2m": "മൗണ്ട് കിളിമഞ്ചാരോ", "r1e": "Both are globally famous, extreme high-altitude mountain peaks.", "r1m": "ലോകപ്രശസ്തമായ വലിയ ഉയരമുള്ള പർവ്വത കൊടുമുടികളാണിവ.", "r2e": "Both are legendary and dangerous mountains in the Himalayas.", "r2m": "ഹിമാലയത്തിലെ പ്രശസ്തവും അപകടകരവുമായ പർവ്വതങ്ങളാണിവ."},
    {"civ": "Amazon River", "i1": "Nile River", "i1m": "നൈൽ നദി", "i2": "Ganges", "i2m": "ഗംഗ", "r1e": "Both are incredibly long, famous massive river systems vital to their continents.", "r1m": "അതാത് ഭൂഖണ്ഡങ്ങൾക്ക് വളരെ പ്രധാനപ്പെട്ടതും പ്രശസ്തവുമായ വലിയ നദീതടങ്ങളാണിവ.", "r2e": "Both are legendary continental rivers.", "r2m": "പ്രശസ്തമായ ഭൂഖണ്ഡ നദികളാണിവ."},
    {"civ": "Grand Canyon", "i1": "Bryce Canyon", "i1m": "ബ്രൈസ് കാന്യോൺ", "i2": "Yellowstone", "i2m": "യെല്ലോസ്റ്റോൺ", "r1e": "Both are massively famous, visually stunning natural rock formations in the US.", "r1m": "അമേരിക്കയിലെ വളരെ പ്രശസ്തവും മനോഹരവുമായ പ്രകൃതിദത്ത പാറക്കൂട്ടങ്ങളാണിവ.", "r2e": "Both are legendary national parks featuring deep gorges.", "r2m": "ആഴത്തിലുള്ള താഴ്‌വരകളുള്ള പ്രശസ്തമായ ദേശീയ ഉദ്യാനങ്ങളാണിവ."},
    {"civ": "Times Square", "i1": "Piccadilly Circus", "i1m": "പിക്കാഡിലി സർക്കസ്", "i2": "Shibuya Crossing", "i2m": "ഷിബുയ ക്രോസിംഗ്", "r1e": "Both are incredibly busy, neon-lit iconic commercial intersections in major global cities.", "r1m": "വലിയ നഗരങ്ങളിലെ വളരെ തിരക്കേറിയതും പ്രശസ്തവുമായ വാണിജ്യ ജംഗ്ഷനുകളാണിവ.", "r2e": "Both are famous urban tourist hotspots known for giant screens.", "r2m": "വലിയ സ്ക്രീനുകൾക്ക് പേരുകേട്ട പ്രശസ്തമായ നഗര വിനോദസഞ്ചാര കേന്ദ്രങ്ങളാണിവ."}
  ]
}

for cat, words in data.items():
    output[cat] = []
    for w in words:
        output[cat].append({
            "civWord": w["civ"],
            "civWordMal": "",
            "imposters": [
                {
                    "word": w["i1"],
                    "wordMal": w["i1m"],
                    "relationEN": w["r1e"],
                    "relationML": w["r1m"]
                },
                {
                    "word": w["i2"],
                    "wordMal": w["i2m"],
                    "relationEN": w["r2e"],
                    "relationML": w["r2m"]
                }
            ]
        })

with open("C:/Users/HP/Desktop/Imposter/scratch/chunk_4_done.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)
