import json

RELATIONS = {
    ("Chaya","Kaappi"): ("Both are hot brewed drinks served in small glasses at Kerala tea stalls, one made from tea leaves and the other from coffee beans.", "ചായയും കാപ്പിയും കേരളത്തിലെ ചായക്കടകളിൽ ചെറിയ ഗ്ലാസ്സിൽ വിളമ്പുന്ന ചൂടുള്ള പാനീയങ്ങളാണ്, ഒന്ന് ചായ ഇലകൾ കൊണ്ടും മറ്റൊന്ന് കോഫി പൊടി കൊണ്ടും ഉണ്ടാക്കുന്നു."),
    ("Chaya","Kattan Chaya"): ("Both are tea-based hot drinks; Chaya is milky and sweet while Kattan Chaya is strong black tea without milk.", "ചായയും കട്ടൻ ചായയും ചായ ഇലകൾ കൊണ്ട് ഉണ്ടാക്കുന്ന ഗ്ലാസ്സ് പാനീയങ്ങളാണ്; ചായ പഞ്ചസാരയും പാലും ഉള്ളതും കട്ടൻ ചായ കറുത്ത ദ്രാവകവുമാണ്."),
    ("Puffs","Samosa"): ("Both are crispy deep-fried or baked snacks with a stuffed filling sold at Kerala bakeries.", "പഫ്സും സമോസയും കേരള ബേക്കറികളിൽ വിൽക്കുന്ന, ഫില്ലിംഗ് നിറഞ്ഞ, പൊരിച്ചതോ ബേക്ക് ചെയ്തതോ ആയ ഒരുതരം ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Puffs","Cutlet"): ("Both are popular bakery snacks in Kerala with a crispy outer layer and a savory filling inside.", "പഫ്സും കട്ട്‌ലറ്റും കേരളത്തിൽ ജനപ്രിയമായ ബേക്കറി ലഘുഭക്ഷണങ്ങളാണ്, രണ്ടിനും പുറത്ത് ക്രിസ്‌പി പൂശ്ശും അകത്ത് മസാലചേർന്ന ഫില്ലിംഗും ഉണ്ട്."),
    ("Uzhunnu Vada","Parippu Vada"): ("Both are fried Kerala snacks made from ground lentil batter served hot with chutney at tea stalls.", "ഉഴുന്ന് വടയും പരിപ്പ് വടയും കേരള ചായക്കടകളിൽ ചട്ണിയോടൊപ്പം ചൂടോടെ വിളമ്പുന്ന, അരച്ച പരിപ്പ് ബാറ്ററിൽ നിർമ്മിക്കുന്ന വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Uzhunnu Vada","Ulli Vada"): ("Both are round deep-fried vada snacks from Kerala, differing mainly in the batter—urad dal vs onion.", "ഉഴുന്ന് വടയും ഉള്ളി വടയും കേരളത്തിൽ നിന്നുള്ള ഉരുണ്ട, ആഴത്തിൽ വറുത്ത വട ലഘുഭക്ഷണങ്ങളാണ്; ബാറ്ററിൽ ഒന്ന് ഉഴുന്നും മറ്റൊന്ന് ഉള്ളിയും ഉപയോഗിക്കുന്നു."),
    ("Mutta Baji","Pazhampori"): ("Both are egg or banana coated in batter and deep-fried, common evening snacks in Kerala.", "മുട്ട ബജിയും പഴംപൊരിയും ബാറ്ററിൽ മുക്കി വറുത്ത, കേരളത്തിൽ വൈകുന്നേരം സർവ്വസാധാരണമായ ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Mutta Baji","Mulaku Baji"): ("Both are baji snacks deep-fried in a gram-flour batter, one uses egg and the other uses green chilli.", "മുട്ട ബജിയും മുളക് ബജ്ജിയും കടലമാവ് ബാറ്ററിൽ ആഴത്തിൽ വറുത്ത ബജ്ജി ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് മുട്ടയും മറ്റൊന്ന് പച്ചമുളകും ഉപയോഗിക്കുന്നു."),
    ("Kozhukkatta","Ela Ada"): ("Both are steamed sweet rice dumplings with a coconut and jaggery filling, popular as Kerala festival snacks.", "കൊഴുക്കട്ടയും ഇല അടയും ഒരേ തേങ്ങ-ശർക്കര ഫില്ലിംഗ് ഉള്ള, ആവിയിൽ വേവിക്കുന്ന ചോറ് കൊണ്ടുള്ള മധുര ലഘുഭക്ഷണങ്ങളാണ്, കേരള ഉത്സവ നേരങ്ങളിൽ ജനപ്രിയമാണ്."),
    ("Kozhukkatta","Modakam"): ("Both are steamed rice flour dumplings filled with sweet coconut and jaggery, one is Kerala-style and the other is used in Ganesh Chaturthi.", "കൊഴുക്കട്ടയും മോദകവും ഒരേ തേങ്ങ-ശർക്കര ഫില്ലിംഗ് ഉള്ള ആരിടിമാവ് ഉരുളകളാണ്; ഒന്ന് കേരള ശൈലിയും മറ്റൊന്ന് ഗണേശ ചതുർഥി ആഘോഷങ്ങളിൽ ഉപയോഗിക്കുന്നതുമാണ്."),
    ("Cutlet","Meat Roll"): ("Both are popular Kerala bakery snacks with a spiced meat filling, the cutlet is flat and the roll is cylindrical.", "കട്ട്‌ലറ്റും മീറ്റ് റോളും ഒരേ മസാലക്കറി ഫില്ലിംഗ് ഉള്ള ജനപ്രിയ കേരള ബേക്കറി ലഘുഭക്ഷണങ്ങളാണ്; കട്ട്‌ലറ്റ് പരന്നതും റോൾ ഉരുണ്ടതുമാണ്."),
    ("Cutlet","Samosa"): ("Both are savory deep-fried snacks with spiced stuffing popular at Kerala tea shops, served alongside evening tea.", "കട്ട്‌ലറ്റും സമോസയും കേരള ചായക്കടകളിൽ ജനപ്രിയ, മസാലചേർന്ന ഫില്ലിംഗ് ഉള്ള, ആഴത്തിൽ വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Samosa","Puffs"): ("Both are triangle or rectangular snacks with a savory filling, sold from glass cases at Kerala bakeries.", "സമോസയും പഫ്സും ഒരേ കേരള ബേക്കറികളിൽ ഗ്ലാസ് കൂടുകളിൽ വിൽക്കുന്ന, മസാലചേർന്ന ഫില്ലിംഗ് ഉള്ള ത്രികോണ അല്ലെങ്കിൽ ചതുർഭുജ ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Samosa","Meat Roll"): ("Both are stuffed and fried snacks sold at bakeries across Kerala, one with a pastry shell and one with a bread crumb coating.", "സമോസയും മീറ്റ് റോളും കേരളത്തിലുടനീളം ബേക്കറികളിൽ വിൽക്കുന്ന, ഫില്ലിംഗ് ഉള്ള വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് പേസ്ട്രി ഷെൽ ഉള്ളതും മറ്റൊന്ന് ബ്രഡ് ക്രം പൂശ്ശ് ഉള്ളതുമാണ്."),
    ("Bonda","Sukhiyan"): ("Both are round, deep-fried sweet snacks made with coconut and lentil fillings, popular at tea stalls.", "ബൊണ്ടയും സൂഖിയനും ഒരേ ഉരുണ്ട, ആഴത്തിൽ വറുത്ത, തേങ്ങ-പരിപ്പ് ഫില്ലിംഗ് ഉള്ള മധുര ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Bonda","Uzhunnu Vada"): ("Both are lentil-based deep-fried snacks served hot with coconut chutney as a tea-time snack in Kerala.", "ബൊണ്ടയും ഉഴുന്ന് വടയും കേരളത്തിൽ ചായ സമയത്ത് തേങ്ങ ചട്ണിയോടൊപ്പം ചൂടോടെ വിളമ്പുന്ന, പരിപ്പ് ആധാരിതമായ, ആഴത്തിൽ വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Parippu Vada","Uzhunnu Vada"): ("Both are flat, round deep-fried lentil vadas, staple snacks at Kerala tea shops with coconut chutney.", "പരിപ്പ് വടയും ഉഴുന്ന് വടയും കേരള ചായക്കടകളിൽ തേങ്ങ ചട്ണിയോടൊപ്പം നൽകുന്ന, പരിപ്പ് കൊണ്ട് ഉണ്ടാക്കുന്ന, പരന്ന, ഉരുണ്ട, ആഴത്തിൽ വറുത്ത പ്രധാന ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Parippu Vada","Ulli Vada"): ("Both are crispy deep-fried vada snacks served at Kerala tea stalls, with a crunchy exterior and soft core.", "പരിപ്പ് വടയും ഉള്ളി വടയും കേരള ചായക്കടകളിൽ വിളമ്പുന്ന, പുറത്ത് ക്രിസ്‌പിയും അകത്ത് മൃദുലവുമായ, ആഴത്തിൽ വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Ela Ada","Kozhukkatta"): ("Both are sweet rice dumplings with coconut-jaggery filling made during Kerala festivals like Vishu and Onam.", "ഇല അടയും കൊഴുക്കട്ടയും കേരളത്തിൽ വിഷു, ഓണം എന്നീ ആഘോഷങ്ങളിൽ ഉണ്ടാക്കുന്ന, തേങ്ങ-ശർക്കര ഫില്ലിംഗ് ഉള്ള, മധുര ചോറ് ഉരുളകളാണ്."),
    ("Ela Ada","Ilayappam"): ("Both are steamed rice dishes wrapped or cooked in banana leaves, carrying the distinct aroma of the leaf.", "ഇല അടയും ഇലയപ്പവും വാഴ ഇലകളിൽ പൊതിഞ്ഞ് അല്ലെങ്കിൽ ആ ഇലയ്ക്ക് മേൽ ഉണ്ടാക്കുന്ന, ആ ഇലയുടെ സ്വന്തം സുഗന്ധം ഉള്ള, ആവിയിൽ വേവിക്കുന്ന ചോറ് ഭക്ഷണങ്ങളാണ്."),
    ("Achappam","Kuzhalappam"): ("Both are crispy deep-fried rice flour snacks from Kerala, one is rose-cookie shaped and the other is cylindrical.", "അച്ചപ്പവും കുഴലപ്പവും കേരളത്തിൽ നിന്നുള്ള, ആരിടിമാവ് കൊണ്ട് ഉണ്ടാക്കുന്ന, ക്രിസ്‌പി, ആഴത്തിൽ വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് റോസ് കുക്കി ആകൃതിയിലും മറ്റൊന്ന് കുഴൽ ആകൃതിയിലുമാണ്."),
    ("Achappam","Murukku"): ("Both are crunchy deep-fried rice flour snacks traditionally made at home for Kerala festivals and celebrations.", "അച്ചപ്പവും മുറുക്കും കേരള ഉത്സവങ്ങൾക്കും ആഘോഷങ്ങൾക്കും വേണ്ടി വീടുകളിൽ ഉണ്ടാക്കുന്ന, ആരിടിമാവ് കൊണ്ടുള്ള, ക്രഞ്ചി, ആഴത്തിൽ വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Unniyappam","Neyyappam"): ("Both are small round rice flour pancakes fried in iron moulds with coconut and jaggery, a beloved Kerala sweet.", "ഉണ്ണിയപ്പവും നെയ്യപ്പവും ഇരുമ്പ് അച്ചുകളിൽ തേങ്ങയും ശർക്കരയും ഉള്ള ആരിടിമാവ് കൊണ്ട് ഉണ്ടാക്കുന്ന, ഉരുണ്ട ചെറിയ, കേരളത്തിൽ ഏറ്റവും പ്രിയപ്പെട്ട മധുരങ്ങളാണ്."),
    ("Unniyappam","Kinnathappam"): ("Both are soft, sweet steamed or fried rice snacks made with jaggery and coconut as festival treats in Kerala.", "ഉണ്ണിയപ്പവും കിണ്ണത്തപ്പവും ശർക്കരയും തേങ്ങയും ഉള്ള, കേരളത്തിൽ ഉത്സവ വേളകളിൽ ഉണ്ടാക്കുന്ന, മൃദുലമായ, മധുര, ആരിടിമാവ് ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Banana Chips","Kappa Chips"): ("Both are thin, crispy fried chips made from Kerala crops—one from raw banana and the other from tapioca.", "ബനാന ചിപ്സും കപ്പ ചിപ്സും കേരളത്തിൽ ഉൽഭവിക്കുന്ന ഉൽഭവ വസ്തുക്കൾ കൊണ്ടുള്ള, നേർത്ത, ക്രിസ്‌പി, വറുത്ത ചിപ്സ് ആണ്; ഒന്ന് പച്ചക്കദളി കൊണ്ടും മറ്റൊന്ന് കപ്പ കൊണ്ടുമാണ്."),
    ("Banana Chips","Sharkara Upperi"): ("Both are made from raw banana slices in Kerala—banana chips are savory and Sharkara Upperi is coated with jaggery.", "ബനാന ചിപ്സും ശർക്കര ഉപ്പേരിയും കേരളത്തിൽ പച്ചക്കദളി ഉപയോഗിച്ചാണ് ഉണ്ടാക്കുന്നത്; ബനാന ചിപ്സ് ഉപ്പ് സ്വഭാവം ഉള്ളതും ശർക്കര ഉപ്പേരി ശർക്കരപ്പൂ പൂശ്ശ് ഉള്ളതുമാണ്."),
    ("Sharkara Upperi","Banana Chips"): ("Both are banana-based crunchy snacks from Kerala, one sweet and jaggery-coated, one salted and crispy.", "ശർക്കര ഉപ്പേരിയും ബനാന ചിപ്സും കേരളത്തിൽ നിന്നുള്ള, ക്കദളി ആധാരിതമായ ക്രഞ്ചി ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് മധുരവും ശർക്കരപ്പൂ ഉള്ളതും, മറ്റൊന്ന് ഉപ്പ് ചേർന്ന ക്രിസ്‌പിയും ആണ്."),
    ("Sharkara Upperi","Achappam"): ("Both are traditional Onam and festival sweets made at home in Kerala with rice flour or banana as the base.", "ശർക്കര ഉപ്പേരിയും അച്ചപ്പവും കേരളത്തിൽ ഓണം, ഉത്സവ വേളകളിൽ ആരിടിമാവ് അല്ലെങ്കിൽ ക്കദളി ആധാരമായി വീടുകളിൽ ഉണ്ടാക്കുന്ന, പരമ്പരാഗത മധുര ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Kappa Chips","Banana Chips"): ("Both are crunchy sliced chips from Kerala, made from root vegetables or plantain, sold by roadside shops.", "കപ്പ ചിപ്സും ബനാന ചിപ്സും കേരളത്തിൽ റോഡ് വക്കിലെ കടകളിൽ വിൽക്കുന്ന, ചോറ് സസ്യങ്ങൾ അല്ലെങ്കിൽ ക്കദളി കൊണ്ടുള്ള, ക്രഞ്ചി, അരിഞ്ഞ ചിപ്സ് ആണ്."),
    ("Kappa Chips","Pakkavada"): ("Both are crunchy, oil-fried Kerala snacks sold in shops with tea, one from tapioca and one from rice flour strips.", "കപ്പ ചിപ്സും പക്കാവടയും കേരളത്തിൽ ചായക്കൊപ്പം കടകളിൽ വിൽക്കുന്ന, ക്രഞ്ചി, എണ്ണയിൽ വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് കപ്പ കൊണ്ടും മറ്റൊന്ന് ആരിടിമാവ് കൊണ്ടുമാണ്."),
    ("Avalose Podi","Avalose Unda"): ("Both are made from the same roasted rice flour base—Avalose Podi is loose powder and Avalose Unda is a ball.", "അവലോസ് പൊടിയും അവലോസ് ഉണ്ടയും ഒരേ വറുത്ത ആരിടിപ്പൊടി ആധാരത്തിൽ ഉണ്ടാക്കുന്നതാണ്; അവലോസ് പൊടി അടിത്തള്ളൽ രൂപത്തിലും അവലോസ് ഉണ്ട ഉരുള ആകൃതിയിലുമാണ്."),
    ("Avalose Podi","Churuttu"): ("Both are traditional Kerala sweets made from roasted rice flour and jaggery, one is powdery and one is rolled.", "അവലോസ് പൊടിയും ചുരുട്ടും കേരളത്തിൽ വറുത്ത ആരിടിപ്പൊടിയും ശർക്കരയും ഉപയോഗിച്ച് ഉണ്ടാക്കുന്ന, പരമ്പരാഗത മധുരങ്ങളാണ്; ഒന്ന് പൊടിരൂപത്തിലും മറ്റൊന്ന് ചുരുൾ ആകൃതിയിലുമാണ്."),
    ("Kozhalappam","Achappam"): ("Both are crispy, deep-fried Kerala festival snacks made from rice flour using specially shaped moulds.", "കുഴലപ്പവും അച്ചപ്പവും ആരിടിമാവ് ഉപയോഗിച്ച്, പ്രത്യേക ആകൃതി ഉള്ള ഉപകരണങ്ങൾ ഉപയോഗിച്ച് ഉണ്ടാക്കുന്ന, കേരള ഉത്സവ ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Kozhalappam","Murukku"): ("Both are crispy hollow or spiral-shaped fried rice snacks that make a crunching sound when eaten.", "കുഴലപ്പവും മുറുക്കും ആഴത്തിൽ വറുത്ത, ഉള്ളൊ ഒഴിഞ്ഞ അല്ലെങ്കിൽ ചുരുൾ ആകൃതിയിലുള്ള, കഴിക്കുമ്പോൾ ക്രഞ്ചി ശബ്ദം ഉണ്ടാക്കുന്ന ആരിടി ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Kinnathappam","Kalathappam"): ("Both are soft, steamed Kerala rice sweets cooked in vessels—one in a plate and the other in an earthen pot.", "കിണ്ണത്തപ്പവും കലത്തപ്പവും കേരളത്തിൽ പാത്രങ്ങളിൽ ആവിയിൽ പാകം ചെയ്യുന്ന, മൃദുലമായ, ആരിടി മധുരങ്ങളാണ്; ഒന്ന് തട്ടത്തിലും മറ്റൊന്ന് മൺ കലത്തിലുമാണ്."),
    ("Kinnathappam","Unniyappam"): ("Both are soft, sweet Kerala rice snacks with jaggery and coconut, enjoyed during festivals and celebrations.", "കിണ്ണത്തപ്പവും ഉണ്ണിയപ്പവും ശർക്കരയും തേങ്ങയും ഉള്ള, ഉത്സവങ്ങളിൽ ആസ്വദിക്കുന്ന, മൃദുലമായ, മധുര കേരള ആരിടി ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Churuttu","Avalose Unda"): ("Both are rolled or ball-shaped traditional Kerala sweets made from rice flour and coconut with jaggery.", "ചുരുട്ടും അവലോസ് ഉണ്ടയും ആരിടിമാവ്, തേങ്ങ, ശർക്കര ഉപയോഗിച്ചുണ്ടാക്കുന്ന, ചുരൾ ആകൃതിയിലോ ഉരുള ആകൃതിയിലോ ഉള്ള, പരമ്പരാഗത കേരള മധുരങ്ങളാണ്."),
    ("Churuttu","Kuzhalappam"): ("Both are cylindrical-shaped crispy snacks made from rice flour and used as festival treats in Kerala homes.", "ചുരുട്ടും കുഴലപ്പവും ആരിടിമാവ് കൊണ്ടുണ്ടാക്കുന്ന, കേരള ഉത്സവ ലഘുഭക്ഷണങ്ങളായ, കുഴൽ ആകൃതിയിലുള്ള ക്രിസ്‌പി ഭക്ഷണങ്ങളാണ്."),
    ("Halwa","Jalebi"): ("Both are intensely sweet Indian desserts made with sugar syrup—Halwa is dense and Jalebi is syrup-soaked spirals.", "ഹൽവയും ജിലേബിയും ഒരേ പഞ്ചസാര സിറപ്പ് ഉപയോഗിച്ചുണ്ടാക്കുന്ന, തീക്ഷ്ണ മധുര ഇന്ത്യൻ ഡെസർട്ടുകളാണ്; ഹൽവ കട്ടിയുള്ളതും ജിലേബി സിറപ്പ് കുതിർന്ന ചുരുളുകളുമാണ്."),
    ("Halwa","Laddoo"): ("Both are festive Indian sweets gifted during celebrations—Halwa is a soft dessert and Laddoo is a round ball.", "ഹൽവയും ലഡ്ഡൂവും ഉത്സവ വേളകളിൽ സമ്മാനമായി നൽകുന്ന, ഇന്ത്യൻ മധുരങ്ങളാണ്; ഹൽവ മൃദുലമായ ഡെസർട്ടും ലഡ്ഡൂ ഉരുണ്ട ഉരുളയുമാണ്."),
    ("Sukhiyan","Bonda"): ("Both are round, deep-fried Kerala snacks with a sweet filling of coconut and green gram inside.", "സൂഖിയനും ബൊണ്ടയും ഒരേ തേങ്ങ-ചെറുപയർ ഫില്ലിംഗ് ഉള്ള, ഉരുണ്ട, ആഴത്തിൽ വറുത്ത, കേരള ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Sukhiyan","Modakam"): ("Both are sweet-filled rice or wheat dumplings with green gram and coconut, offered as prasadam in temples.", "സൂഖിയനും മോദകവും ചെറുപയറും തേങ്ങയും ഉള്ള, ദേവാലയങ്ങളിൽ പ്രസാദമായി നൽകുന്ന, മധുര ഫില്ലിംഗ് ഉള്ള, ആരിടി അല്ലെങ്കിൽ ഗോതമ്പ് ഉരുളകളാണ്."),
    ("Bread Pakora","Pazhampori"): ("Both are batter-coated and deep-fried snacks served hot—one uses bread slices and the other uses banana.", "ബ്രഡ് പകോടയും പഴംപൊരിയും ബാറ്ററിൽ മുക്കി ആഴത്തിൽ വറുത്ത, ചൂടോടെ നൽകുന്ന ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് ബ്രഡ് ഉപയോഗിക്കുന്നതും മറ്റൊന്ന് ക്കദളി ഉപയോഗിക്കുന്നതുമാണ്."),
    ("Bread Pakora","Mutta Baji"): ("Both are gram-flour batter fried snacks—one using bread and one using egg—popular in Kerala evening tea time.", "ബ്രഡ് പകോടയും മുട്ട ബജിയും കടലമാവ് ബാറ്ററിൽ വറുത്ത ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് ബ്രഡ് ഉള്ളതും മറ്റൊന്ന് മുട്ട ഉള്ളതും ആണ്, കേരളത്തിൽ വൈകുന്നേര ചായ സമയത്ത് ജനപ്രിയമാണ്."),
    ("Laddoo","Jalebi"): ("Both are Indian sweets made with sugar and deep-frying, popular during festivals and given as gifts.", "ലഡ്ഡൂവും ജിലേബിയും ഉത്സവ വേളകളിൽ ജനപ്രിയ, പഞ്ചസാരയും, ആഴ്ത്തി വറുക്കലും ഉള്ള ഇന്ത്യൻ മധുരങ്ങളാണ്."),
    ("Laddoo","Halwa"): ("Both are traditional Indian festival sweets—Laddoo is sphere-shaped and Halwa is a soft dessert pudding.", "ലഡ്ഡൂവും ഹൽവയും ഒരേ ഉത്സവ ആചാരം ഉള്ള, പരമ്പരാഗത ഇന്ത്യൻ മധുരങ്ങളാണ്; ലഡ്ഡൂ ഗോളാകൃതിയിലും ഹൽവ മൃദുലമായ ഡെസർട്ട് പുഡ്ഡിംഗ് ആകൃതിയിലുമാണ്."),
    ("Jalebi","Laddoo"): ("Both are brightly colored, festive Indian sweets distributed during weddings and celebrations.", "ജിലേബിയും ലഡ്ഡൂവും വിവാഹങ്ങളിലും ആഘോഷങ്ങളിലും വിതരണം ചെയ്യുന്ന, തിളങ്ങുന്ന നിറത്തിലുള്ള, ഉത്സവ ഇന്ത്യൻ മധുരങ്ങളാണ്."),
    ("Jalebi","Halwa"): ("Both are hot, sweet Indian desserts served during festivals—Jalebi is syrupy spirals and Halwa is a dense pudding.", "ജിലേബിയും ഹൽവയും ഉത്സവ വേളകളിൽ ഗ്രഹിക്കുന്ന, ചൂടുള്ള, മധുര ഇന്ത്യൻ ഡെസർട്ടുകളാണ്; ജിലേബി സിറപ്പ് ചുരുളുകളും ഹൽവ കട്ടി പുഡ്ഡിംഗ് ആകൃതിയിലുമാണ്."),
    ("Meat Roll","Cutlet"): ("Both are popular Kerala bakery snacks with minced meat filling, one is flat and crumbed and one is cylindrical.", "മീറ്റ് റോളും കട്ട്‌ലറ്റും ഒരേ അരിഞ്ഞ ഇറച്ചി ഫില്ലിംഗ് ഉള്ള, ജനപ്രിയ കേരള ബേക്കറി ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് പരന്നതും ബ്രഡ്ക്രം ഉള്ളതും, മറ്റൊന്ന് കുഴൽ ആകൃതിയിലുമാണ്."),
    ("Meat Roll","Samosa"): ("Both are stuffed snacks with a crispy outer shell sold side by side at Kerala bakeries with tea.", "മീറ്റ് റോളും സമോസയും ക്രിസ്‌പി പൊതിഞ്ഞ, ഫില്ലിംഗ് ഉള്ള ലഘുഭക്ഷണങ്ങളാണ്, കേരള ബേക്കറികളിൽ ചായക്കൊപ്പം തൊട്ടടുത്ത് വിൽക്കുന്നത്."),
    ("Boli","Payasam"): ("Both are Kerala festival sweets traditionally made during Onam and Vishu, one is a stuffed flatbread and the other a pudding.", "ബോളിയും പായസവും ഒരേ ഓണം, വിഷു ഉത്സവ ആചാരം ഉള്ള, കേരള മധുരങ്ങളാണ്; ബോളി ഫില്ലിംഗ് ഉള്ള ചപ്പാത്തി ആകൃതിയും പായസം ഒഴുകുന്ന ഡെസർട്ടുമാണ്."),
    ("Boli","Halwa"): ("Both are sweet, soft, festive South Indian desserts made with dal or wheat, typical at Kerala celebrations.", "ബോളിയും ഹൽവയും ദൽ അല്ലെങ്കിൽ ഗോതമ്പ് ഉള്ള, കേരള ആഘോഷങ്ങളിൽ ഉണ്ടാക്കുന്ന, മൃദുലമായ, ഉത്സവ ദക്ഷിണ ഇന്ത്യൻ ഡെസർട്ടുകളാണ്."),
    ("Chatti Pathiri","Meat Roll"): ("Both are layered or rolled baked dishes with a spiced meat filling, popular in Malabar Kerala cuisine.", "ചട്ടി പത്തിരിയും മീറ്റ് റോളും മലബാർ കേരള പാചകരീതിയിൽ ജനപ്രിയ, മസാലചേർന്ന ഇറച്ചി ഫില്ലിംഗ് ഉള്ള, ആലയിൽ ആക്കിയ ഭക്ഷണങ്ങളാണ്."),
    ("Chatti Pathiri","Samosa"): ("Both are pastry-covered snacks with a spiced filling, common in Kerala Muslim households and bakeries.", "ചട്ടി പത്തിരിയും സമോസയും കേരള മുസ്ലിം ഗൃഹങ്ങളിലും ബേക്കറികളിലും സർവ്വസാധാരണ, മസാല ഫില്ലിംഗ് ഉള്ള, പേസ്ട്രി പൊതിഞ്ഞ ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Vettu Cake","Plum Cake"): ("Both are popular Christmas sweets sold at Kerala bakeries, one is a diamond-shaped fried cake and the other is a fruit-studded baked one.", "വേറ്റ് കേക്കും പ്ലം കേക്കും കേരള ബേക്കറികളിൽ ക്രിസ്തുമസ് കാലത്ത് ജനപ്രിയ മധുരങ്ങളാണ്; ഒന്ന് ഡയമണ്ട് ആകൃതിയിൽ വറുത്ത കേക്കും, മറ്റൊന്ന് പഴങ്ങൾ ചേർന്ന ബേക്ക് ചെയ്ത കേക്കുമാണ്."),
    ("Vettu Cake","Bonda"): ("Both are round or diamond-shaped deep-fried sweet snacks enjoyed with tea at Kerala bakeries.", "വേറ്റ് കേക്കും ബൊണ്ടയും കേരള ബേക്കറികളിൽ ചായക്കൊപ്പം ആസ്വദിക്കുന്ന, ഉരുണ്ടതോ ഡയമണ്ട് ആകൃതിയോ ഉള്ള, ആഴത്തിൽ വറുത്ത മധുര ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Pakkavada","Mixture"): ("Both are crunchy fried Kerala snacks made from rice flour, typically sold in shops in bulk and mixed with spices.", "പക്കാവടയും മിക്സ്ചറും ആരിടിമാവ് കൊണ്ടുള്ള, കടകളിൽ ബൾക്കായി വിൽക്കുന്ന, ക്രഞ്ചി, ആഴ്ത്തി വറുത്ത, കേരള ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Pakkavada","Murukku"): ("Both are thin, crispy rice flour snacks deep-fried and eaten with tea, one is flat strips and one is spiral-shaped.", "പക്കാവടയും മുറുക്കും ആഴ്ത്തി വറുത്ത, ചായക്കൊപ്പം കഴിക്കുന്ന, നേർത്ത, ക്രിസ്‌പി ആരിടിമാവ് ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് പരന്ന നാടകളും, മറ്റൊന്ന് ചുരൾ ആകൃതിയിലുമാണ്."),
    ("Kayyappam","Neyyappam"): ("Both are round, pan-fried sweet rice snacks from Kerala cooked in special iron moulds with jaggery and coconut.", "കൈയ്യപ്പവും നെയ്യപ്പവും ഒരേ ശർക്കരയും തേങ്ങയും ഉള്ള, പ്രത്യേക ഇരുമ്പ് അച്ചുകളിൽ ഉണ്ടാക്കുന്ന, ഉരുണ്ട, ഗ്രഹിക്കുന്ന, മധുര ആരിടി ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Kayyappam","Unniyappam"): ("Both are traditional Kerala rice sweet pancakes made in cast iron moulds and enjoyed as temple prasadam.", "കൈയ്യപ്പവും ഉണ്ണിയപ്പവും ദേവാലയ പ്രസാദമായി ആസ്വദിക്കുന്ന, ഇരുമ്പ് അച്ചുകളിൽ ഉണ്ടാക്കുന്ന, പരമ്പരാഗത കേരള ആരിടി മധുര ഉരുളകളാണ്."),
    ("Ilayappam","Ela Ada"): ("Both are steamed rice dishes folded in banana leaves with a sweet coconut-jaggery filling from Kerala.", "ഇലയപ്പവും ഇല അടയും ഒരേ മധുര തേങ്ങ-ശർക്കര ഫില്ലിംഗ് ഉള്ള, ആവിയിൽ വേവിക്കുന്ന, വാഴ ഇലകളിൽ ഉണ്ടാക്കുന്ന, കേരള ആരിടി ഭക്ഷണങ്ങളാണ്."),
    ("Ilayappam","Kozhukkatta"): ("Both are steamed sweet rice dumplings with coconut and jaggery filling, made during festivals in Kerala.", "ഇലയപ്പവും കൊഴുക്കട്ടയും ഒരേ ഉത്സവ ആചാരം ഉള്ള, തേങ്ങ-ശർക്കര ഫില്ലിംഗ് ഉള്ള, ആവിയിൽ വേവിക്കുന്ന, കേരള ആരിടി ഉരുളകളാണ്."),
    ("Mothagam","Kozhukkatta"): ("Both are steamed rice dumplings with a sweet filling that are virtually indistinguishable from the outside.", "മോതകവും കൊഴുക്കട്ടയും ആഴത്തിൽ ഒരേ ആകൃതിയിൽ ഒരേ ഫില്ലിംഗ് ഉള്ള ആവിയിൽ വേവിക്കുന്ന ആരിടി ഉരുളകളാണ്."),
    ("Mothagam","Sukhiyan"): ("Both are sweet green gram and coconut-filled round dumplings offered as prasadam in South Indian temples.", "മോതകവും സൂഖിയനും ദക്ഷിണ ഇന്ത്യൻ ദേവാലയങ്ങളിൽ പ്രസാദമായി നൽകുന്ന, ചെറുപയറ്-തേങ്ങ ഫില്ലിംഗ് ഉള്ള, ഉരുണ്ട, മധുര ഉരുളകളാണ്."),
    ("Mutta Puff","Meat Puff"): ("Both are golden-baked puff pastry snacks sold at Kerala bakeries, one filled with egg and one with spiced meat.", "മുട്ട പഫ്ഫും മീറ്റ് പഫ്ഫും ഒരേ കേരള ബേക്കറികളിൽ വിൽക്കുന്ന, ഉൾഭരിച്ച പേസ്ട്രി ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് മുട്ടയും മറ്റൊന്ന് മസാലചേർന്ന ഇറച്ചിയും ഉള്ളതാണ്."),
    ("Mutta Puff","Chicken Puff"): ("Both are flaky puff pastry baked snacks with an egg or chicken filling popular at every Kerala bakery.", "മുട്ട പഫ്ഫും ചിക്കൻ പഫ്ഫും ഒരേ പൊളിഞ്ഞ പേസ്ട്രി ബേക്ക് ലഘുഭക്ഷണങ്ങളാണ്; ഒന്ന് മുട്ടയും മറ്റൊന്ന് ചിക്കനും ഉള്ളതാണ്."),
    ("Cream Bun","Jam Roll"): ("Both are sweet bakery breads from Kerala—Cream Bun is filled with fresh cream and Jam Roll is rolled with fruit jam.", "ക്രീം ബണ്ണും ജാം റോളും ഒരേ കേരള ബേക്കറി ബ്രഡ് ലഘുഭക്ഷണങ്ങളാണ്; ക്രീം ബൺ ഫ്രഷ് ക്രീം ഉള്ളതും ജാം റോൾ ഫ്രൂട്ട് ജാം ഉള്ളതുമാണ്."),
    ("Cream Bun","Cup Cake"): ("Both are individual-sized sweet baked goods enjoyed with tea at Kerala bakeries, with cream or frosting toppings.", "ക്രീം ബണ്ണും കപ്പ് കേക്കും ഒരേ ചായക്കൊപ്പം ആസ്വദിക്കുന്ന, ക്രീം അല്ലെങ്കിൽ ഫ്രോസ്റ്റിംഗ് ഉള്ള, ഒറ്റ ആൾ ആകൃതിയിൽ ഉള്ള, കേരള ബേക്കറി മധുര ഭക്ഷണങ്ങളാണ്."),
    ("Mixture","Pakkavada"): ("Both are crunchy, spiced Kerala tea-time snacks made from rice flour and gram flour sold loose in shops.", "മിക്സ്ചറും പക്കാവടയും ആരിടിമാവ്, കടലമാവ് കൊണ്ടുള്ള, ക്രഞ്ചി, മസാലചേർന്ന, ചായ സമയ ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Mixture","Murukku"): ("Both are crispy, seasoned rice flour snacks that are sold together in the same shops as tea-time accompaniments.", "മിക്സ്ചറും മുറുക്കും ഒരേ കടകളിൽ ചായ സമയ ലഘുഭക്ഷണങ്ങളായി, ക്രിസ്‌പി, സ്പൈസ്ഡ് ആരിടിമാവ് ലഘുഭക്ഷണങ്ങളാണ്."),
    ("Pahadi Halwa","Kozhikodan Halwa"): ("Both are popular Kerala halwa varieties—Pahadi is made in Thrissur and Kozhikodan is Kozhikode's iconic black halwa.", "പഹാടി ഹൽവയും കോഴിക്കോടൻ ഹൽവയും കേരളത്തിൽ ജനപ്രിയ ഹൽവ ഇനങ്ങളാണ്; ഒന്ന് തൃശ്ശൂരിലും മറ്റൊന്ന് കോഴിക്കോടിന്റെ പ്രതീകമായ കറുത്ത ഹൽവയുമാണ്."),
    ("Pahadi Halwa","Jalebi"): ("Both are intensely sweet, syrupy Indian festival sweets enjoyed by people of all ages in Kerala.", "പഹാടി ഹൽവയും ജിലേബിയും കേരളത്തിൽ എല്ലാ പ്രായക്കാരും ആസ്വദിക്കുന്ന, ശക്തമായ മധുരം ഉള്ള, സിറപ്പ് ഉള്ള ഇന്ത്യൻ ഉത്സവ മധുരങ്ങളാണ്."),
}

with open("scratch/rel_chunk_1.json", "r", encoding="utf-8") as f:
    chunk = json.load(f)

fixed = 0
for pack in chunk:
    for word in pack["words"]:
        cv = word["civWord"]
        for imp in word["imposters"]:
            key = (cv, imp["word"])
            if key in RELATIONS:
                imp["relationEN"], imp["relationML"] = RELATIONS[key]
                fixed += 1

print(f"Fixed {fixed} bakery relations")

with open("scratch/rel_chunk_1_done.json", "w", encoding="utf-8") as f:
    json.dump(chunk, f, indent=2, ensure_ascii=False)
